-- MySQL Script generated by MySQL Workbench
-- Sat Jul 17 18:31:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema globetrotterv1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema globetrotterv1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `globetrotterv1` DEFAULT CHARACTER SET utf8 ;
USE `globetrotterv1` ;

-- -----------------------------------------------------
-- Table `globetrotterv1`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`location` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`location` (
  `location_id` VARCHAR(36) NOT NULL,
  `location_name` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  `postal_code` VARCHAR(255) NULL DEFAULT NULL,
  `latitude` DECIMAL(10,7) NULL DEFAULT NULL,
  `longitude` DECIMAL(10,7) NULL DEFAULT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `globetrotterv1`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`user` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`user` (
  `user_id` VARCHAR(36) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `globetrotterv1`.`registered_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`registered_user` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`registered_user` (
  `user` VARCHAR(36) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password_hashed` VARCHAR(255) NOT NULL,
  `preferred_currency` VARCHAR(3) NULL DEFAULT NULL,
  `primary_phone_country_code` VARCHAR(2) NULL DEFAULT NULL,
  `primary_phone_number` VARCHAR(10) NULL DEFAULT NULL,
  `secondary_phone_country_code` VARCHAR(2) NULL DEFAULT NULL,
  `secondary_phone_number` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`user`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  CONSTRAINT `FKregistered221452`
    FOREIGN KEY (`user`)
    REFERENCES `globetrotterv1`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `globetrotterv1`.`trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`trip` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`trip` (
  `owner` VARCHAR(36) NOT NULL,
  `trip_id` VARCHAR(36) NOT NULL,
  `trip_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`owner`, `trip_id`),
  UNIQUE INDEX `trip_id` (`trip_id` ASC) VISIBLE,
  UNIQUE INDEX `trip_name` (`trip_name` ASC) VISIBLE,
  CONSTRAINT `FKtrip488903`
    FOREIGN KEY (`owner`)
    REFERENCES `globetrotterv1`.`registered_user` (`user`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `globetrotterv1`.`activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`activity` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`activity` (
  `trip_owner` VARCHAR(36) NOT NULL,
  `trip` VARCHAR(36) NOT NULL,
  `activity_id` VARCHAR(36) NOT NULL,
  `start_time` TIMESTAMP NOT NULL,
  `end_time` TIMESTAMP NOT NULL,
  `start_location` VARCHAR(36) NOT NULL,
  `end_location` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`trip_owner`, `trip`, `activity_id`),
  UNIQUE INDEX `activity_id` (`activity_id` ASC) VISIBLE,
  INDEX `FKactivity647625` (`start_location` ASC) VISIBLE,
  INDEX `FKactivity775543` (`end_location` ASC) VISIBLE,
  CONSTRAINT `FKactivity647625`
    FOREIGN KEY (`start_location`)
    REFERENCES `globetrotterv1`.`location` (`location_id`),
  CONSTRAINT `FKactivity775543`
    FOREIGN KEY (`end_location`)
    REFERENCES `globetrotterv1`.`location` (`location_id`),
  CONSTRAINT `FKactivity816498`
    FOREIGN KEY (`trip_owner` , `trip`)
    REFERENCES `globetrotterv1`.`trip` (`owner` , `trip_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `globetrotterv1`.`service_provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`service_provider` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`service_provider` (
  `service_provider_id` VARCHAR(36) NOT NULL,
  `service_provider_name` VARCHAR(255) NOT NULL,
  `location` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`service_provider_id`),
  INDEX `FKservice_pr758271` (`location` ASC) VISIBLE,
  CONSTRAINT `FKservice_pr758271`
    FOREIGN KEY (`location`)
    REFERENCES `globetrotterv1`.`location` (`location_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `globetrotterv1`.`airline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`airline` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`airline` (
  `service_provider` VARCHAR(36) NOT NULL,
  `airline_code` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`service_provider`, `airline_code`),
  UNIQUE INDEX `service_provider` (`service_provider` ASC) VISIBLE,
  UNIQUE INDEX `airline_code` (`airline_code` ASC) VISIBLE,
  CONSTRAINT `FKairline30762`
    FOREIGN KEY (`service_provider`)
    REFERENCES `globetrotterv1`.`service_provider` (`service_provider_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `globetrotterv1`.`airport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`airport` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`airport` (
  `location` VARCHAR(36) NOT NULL,
  `iata_code` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`location`, `iata_code`),
  UNIQUE INDEX `location` (`location` ASC) VISIBLE,
  UNIQUE INDEX `iata_code` (`iata_code` ASC) VISIBLE,
  CONSTRAINT `FKairport228490`
    FOREIGN KEY (`location`)
    REFERENCES `globetrotterv1`.`location` (`location_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `globetrotterv1`.`currency_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`currency_code` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`currency_code` (
  `code` VARCHAR(3) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `globetrotterv1`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`file` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`file` (
  `owner` VARCHAR(36) NOT NULL,
  `file_id` VARCHAR(36) NOT NULL,
  `folder_path` VARCHAR(255) NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `extension` VARCHAR(5) NULL DEFAULT NULL,
  `full_file_path` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`owner`, `file_id`),
  UNIQUE INDEX `full_file_path` (`full_file_path` ASC) VISIBLE,
  CONSTRAINT `FKfile63262`
    FOREIGN KEY (`owner`)
    REFERENCES `globetrotterv1`.`registered_user` (`user`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `globetrotterv1`.`flight_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`flight_activity` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`flight_activity` (
  `trip_owner` VARCHAR(36) NOT NULL,
  `trip` VARCHAR(36) NOT NULL,
  `activity` VARCHAR(36) NOT NULL,
  `flight_offer_json_data` VARCHAR(4095) NOT NULL,
  PRIMARY KEY (`trip_owner`, `trip`, `activity`),
  UNIQUE INDEX `activity` (`activity` ASC) VISIBLE,
  CONSTRAINT `FKflight_act74694`
    FOREIGN KEY (`trip_owner` , `trip` , `activity`)
    REFERENCES `globetrotterv1`.`activity` (`trip_owner` , `trip` , `activity_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `globetrotterv1`.`guest_to_trip_association`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`guest_to_trip_association` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`guest_to_trip_association` (
  `trip_owner` VARCHAR(36) NOT NULL,
  `trip` VARCHAR(36) NOT NULL,
  `guest` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`trip_owner`, `trip`, `guest`),
  INDEX `FKguest_to_t184907` (`guest` ASC) VISIBLE,
  CONSTRAINT `FKguest_to_t161724`
    FOREIGN KEY (`trip_owner` , `trip`)
    REFERENCES `globetrotterv1`.`trip` (`owner` , `trip_id`)
    ON DELETE CASCADE,
  CONSTRAINT `FKguest_to_t184907`
    FOREIGN KEY (`guest`)
    REFERENCES `globetrotterv1`.`user` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `globetrotterv1`.`home_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`home_location` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`home_location` (
  `user` VARCHAR(36) NOT NULL,
  `location` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`user`, `location`),
  UNIQUE INDEX `user` (`user` ASC) VISIBLE,
  INDEX `FKhome_locat943937` (`location` ASC) VISIBLE,
  CONSTRAINT `FKhome_locat112639`
    FOREIGN KEY (`user`)
    REFERENCES `globetrotterv1`.`registered_user` (`user`)
    ON DELETE CASCADE,
  CONSTRAINT `FKhome_locat943937`
    FOREIGN KEY (`location`)
    REFERENCES `globetrotterv1`.`location` (`location_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `globetrotterv1`.`hotel_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`hotel_activity` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`hotel_activity` (
  `trip_owner` VARCHAR(36) NOT NULL,
  `trip` VARCHAR(36) NOT NULL,
  `activity` VARCHAR(36) NOT NULL,
  `hotel_offer_json_data` VARCHAR(4095) NOT NULL,
  PRIMARY KEY (`trip_owner`, `trip`, `activity`),
  UNIQUE INDEX `activity` (`activity` ASC) VISIBLE,
  CONSTRAINT `FKhotel_acti533323`
    FOREIGN KEY (`trip_owner` , `trip` , `activity`)
    REFERENCES `globetrotterv1`.`activity` (`trip_owner` , `trip` , `activity_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `globetrotterv1`.`photo_album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`photo_album` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`photo_album` (
  `trip_owner` VARCHAR(36) NOT NULL,
  `trip` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`trip_owner`, `trip`),
  UNIQUE INDEX `trip` (`trip` ASC) VISIBLE,
  CONSTRAINT `FKphoto_albu409387`
    FOREIGN KEY (`trip_owner` , `trip`)
    REFERENCES `globetrotterv1`.`trip` (`owner` , `trip_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `globetrotterv1`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`photo` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`photo` (
  `trip_owner` VARCHAR(36) NOT NULL,
  `trip` VARCHAR(36) NOT NULL,
  `file_owner` VARCHAR(36) NOT NULL,
  `file` VARCHAR(36) NOT NULL,
  `photo_id` VARCHAR(36) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `is_profile_photo` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`trip_owner`, `trip`, `file_owner`, `file`, `photo_id`),
  UNIQUE INDEX `photo_id` (`photo_id` ASC) VISIBLE,
  INDEX `FKphoto844459` (`file_owner` ASC, `file` ASC) VISIBLE,
  CONSTRAINT `FKphoto844459`
    FOREIGN KEY (`file_owner` , `file`)
    REFERENCES `globetrotterv1`.`file` (`owner` , `file_id`),
  CONSTRAINT `FKphoto969782`
    FOREIGN KEY (`trip_owner` , `trip`)
    REFERENCES `globetrotterv1`.`photo_album` (`trip_owner` , `trip`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `globetrotterv1`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`review` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`review` (
  `reviewer` VARCHAR(36) NOT NULL,
  `service_provider` VARCHAR(36) NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`reviewer`, `service_provider`),
  INDEX `FKreview587606` (`service_provider` ASC) VISIBLE,
  CONSTRAINT `FKreview587606`
    FOREIGN KEY (`service_provider`)
    REFERENCES `globetrotterv1`.`service_provider` (`service_provider_id`),
  CONSTRAINT `FKreview785100`
    FOREIGN KEY (`reviewer`)
    REFERENCES `globetrotterv1`.`registered_user` (`user`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `globetrotterv1`.`service_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `globetrotterv1`.`service_record` ;

CREATE TABLE IF NOT EXISTS `globetrotterv1`.`service_record` (
  `trip_owner` VARCHAR(36) NOT NULL,
  `trip` VARCHAR(36) NOT NULL,
  `activity` VARCHAR(36) NOT NULL,
  `service_provider` VARCHAR(36) NOT NULL,
  `service_record_id` VARCHAR(36) NOT NULL,
  `json_data` VARCHAR(510) NULL DEFAULT NULL,
  PRIMARY KEY (`trip_owner`, `trip`, `activity`, `service_provider`, `service_record_id`),
  UNIQUE INDEX `service_record_id` (`service_record_id` ASC) VISIBLE,
  INDEX `FKservice_re130192` (`service_provider` ASC) VISIBLE,
  CONSTRAINT `FKservice_re130192`
    FOREIGN KEY (`service_provider`)
    REFERENCES `globetrotterv1`.`service_provider` (`service_provider_id`),
  CONSTRAINT `FKservice_re747461`
    FOREIGN KEY (`trip_owner` , `trip` , `activity`)
    REFERENCES `globetrotterv1`.`activity` (`trip_owner` , `trip` , `activity_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

USE `globetrotterv1` ;

-- -----------------------------------------------------
-- procedure usp_create_activity
-- -----------------------------------------------------

USE `globetrotterv1`;
DROP procedure IF EXISTS `globetrotterv1`.`usp_create_activity`;

DELIMITER $$
USE `globetrotterv1`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_create_activity`(
	IN p_trip_owner VARCHAR(36),
	IN p_trip VARCHAR(36),
	IN p_start_time TIMESTAMP,
	IN p_end_time TIMESTAMP,
	IN p_start_location VARCHAR(36),
	IN p_end_location VARCHAR(36),
	IN p_service_provider VARCHAR(36)	
)
BEGIN
	DECLARE v_uuid VARCHAR(36);
	DECLARE v_trip VARCHAR(36);
	SELECT trip_id INTO v_trip FROM trip WHERE trip.trip_id = p_trip;
	SELECT uuid() INTO v_uuid;
	IF ISNULL(v_trip) THEN
		SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'Cannot create activity for trip that does not exist.';
	ELSE
		INSERT INTO activity (trip_owner, trip, activity_id, start_time, end_time, start_location, end_location, service_provider) VALUES (p_trip_owner, p_trip, v_uuid, p_start_time, p_end_time, p_start_location, p_end_location,  p_service_provider);
	END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure usp_create_airline
-- -----------------------------------------------------

USE `globetrotterv1`;
DROP procedure IF EXISTS `globetrotterv1`.`usp_create_airline`;

DELIMITER $$
USE `globetrotterv1`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_create_airline`(
	IN p_iata_code VARCHAR(7),
	IN p_airline_name VARCHAR(255)	
)
BEGIN
	DECLARE v_uuid VARCHAR(36);
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
	END;
	START TRANSACTION;
		SELECT uuid() INTO v_uuid;
		INSERT INTO service_provider (service_provider_id, service_provider_name) VALUES (v_uuid, p_airline_name);
		INSERT INTO airline (airline_code, service_provider) VALUES (p_iata_code, v_uuid);
	COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure usp_create_airport
-- -----------------------------------------------------

USE `globetrotterv1`;
DROP procedure IF EXISTS `globetrotterv1`.`usp_create_airport`;

DELIMITER $$
USE `globetrotterv1`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_create_airport`(
	IN p_airport_name VARCHAR(255),
	IN p_city VARCHAR(255),
	IN p_country VARCHAR(2),
	IN p_iata_code VARCHAR(3),
	IN p_latitude DECIMAL(10, 7),
	IN p_longitude DECIMAL(10, 7)	
)
BEGIN
	DECLARE v_uuid VARCHAR(36);
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
	END;
	START TRANSACTION;
		SELECT uuid() INTO v_uuid;
		INSERT INTO location (location_id, location_name, city, country, latitude, longitude) VALUES (v_uuid, p_airport_name, p_city, p_country, p_latitude, p_longitude);
		INSERT INTO airport (location, iata_code) VALUES (v_uuid, p_iata_code);
	COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure usp_create_review
-- -----------------------------------------------------

USE `globetrotterv1`;
DROP procedure IF EXISTS `globetrotterv1`.`usp_create_review`;

DELIMITER $$
USE `globetrotterv1`$$
CREATE PROCEDURE `usp_create_review`(
	IN p_reviewer VARCHAR(36),
	IN p_review_content VARCHAR(255),
	IN p_service_provider VARCHAR(36)
)
BEGIN
	DECLARE v_uuid VARCHAR(36);
	SELECT uuid() INTO v_uuid;
	INSERT INTO review (reviewer, content, service_provider) VALUES (p_reviewer, p_review_content, p_service_provider);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure usp_create_trip
-- -----------------------------------------------------

USE `globetrotterv1`;
DROP procedure IF EXISTS `globetrotterv1`.`usp_create_trip`;

DELIMITER $$
USE `globetrotterv1`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_create_trip`(
	IN p_owner VARCHAR(36),
	IN p_trip_name VARCHAR(255)	
)
BEGIN
	DECLARE v_uuid VARCHAR(36);
	SELECT uuid() INTO v_uuid;
	INSERT INTO trip (owner, trip_id, trip_name) VALUES (p_owner, v_uuid, p_trip_name);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure usp_delete_activity
-- -----------------------------------------------------

USE `globetrotterv1`;
DROP procedure IF EXISTS `globetrotterv1`.`usp_delete_activity`;

DELIMITER $$
USE `globetrotterv1`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_delete_activity`(
	IN p_activity_id VARCHAR(36)
)
BEGIN
	DELETE FROM activity WHERE activity.activity_id = p_activity_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure usp_delete_review
-- -----------------------------------------------------

USE `globetrotterv1`;
DROP procedure IF EXISTS `globetrotterv1`.`usp_delete_review`;

DELIMITER $$
USE `globetrotterv1`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_delete_review`(
	IN p_review_id VARCHAR(36)
)
BEGIN
	DELETE FROM review WHERE review.review_id = p_review_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure usp_delete_trip
-- -----------------------------------------------------

USE `globetrotterv1`;
DROP procedure IF EXISTS `globetrotterv1`.`usp_delete_trip`;

DELIMITER $$
USE `globetrotterv1`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_delete_trip`(
	IN p_trip_id VARCHAR(36)
)
BEGIN
	DELETE FROM trip WHERE trip.trip_id = p_trip_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure usp_create_user
-- -----------------------------------------------------

USE `globetrotterv1`;
DROP procedure IF EXISTS `globetrotterv1`.`usp_create_user`;

DELIMITER $$
USE `globetrotterv1`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_create_user`(
	IN p_email VARCHAR(255),
    OUT o_user_id VARCHAR(36)
)
BEGIN
	DECLARE v_uuid VARCHAR(36);
	SELECT uuid() INTO v_uuid;
	INSERT INTO `user` (user_id, email) VALUES (v_uuid, p_email);
    SET o_user_id = v_uuid;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure usp_register_user
-- -----------------------------------------------------

USE `globetrotterv1`;
DROP procedure IF EXISTS `globetrotterv1`.`usp_register_user`;

DELIMITER $$
USE `globetrotterv1`$$
CREATE PROCEDURE `usp_register_user`(
	IN p_email VARCHAR(255),
    IN p_username VARCHAR(255),
    IN p_password_hashed VARCHAR(255),
	IN p_preferred_currency VARCHAR(3),
	IN p_primary_phone_country_code VARCHAR(2),
    IN p_primary_phone_number VARCHAR(10),
    IN p_secondary_phone_country_code VARCHAR(2),
	IN p_secondary_phone_number VARCHAR(10)
)
BEGIN
    DECLARE v_user_id VARCHAR(36);
    SELECT `user_id` INTO v_user_id FROM `user` WHERE `user`.email = p_email;
    IF (v_user_id IS NULL) THEN
		CALL usp_create_user(p_email, v_user_id);
    END IF;
	INSERT INTO registered_user (`user`, username, password_hashed, preferred_currency,
		primary_phone_country_code, primary_phone_number, secondary_phone_country_code, secondary_phone_number)
        VALUES (v_user_id, p_username, p_password_hashed, p_preferred_currency, p_primary_phone_country_code, p_primary_phone_number,
        p_secondary_phone_country_code, p_secondary_phone_number);
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
