CALL CreateAirline('02Q', 'Titan Airways');
CALL CreateAirline('04Q', 'Tradewind Aviation');
CALL CreateAirline('05Q', 'Comlux Aviation, AG');
CALL CreateAirline('06Q', 'Master Top Linhas Aereas Ltd.');
CALL CreateAirline('07Q', 'Flair Airlines Ltd.');
CALL CreateAirline('09Q', 'Swift Air, LLC');
CALL CreateAirline('0BQ', 'DCA');
CALL CreateAirline('0CQ', 'ACM AIR CHARTER GmbH');
CALL CreateAirline('0GQ', 'Inter Island Airways, d/b/a Inter Island Air');
CALL CreateAirline('0HQ', 'Polar Airlines de Mexico d/b/a Nova Air');
CALL CreateAirline('0J', 'JetClub AG');
CALL CreateAirline('0JQ', 'Vision Airlines');
CALL CreateAirline('0LQ', 'Metropix UK, LLP.');
CALL CreateAirline('0MQ', 'Multi-Aero, Inc. d/b/a Air Choice One');
CALL CreateAirline('0OQ', 'Open Skies');
CALL CreateAirline('0Q', 'Flying Service N.V.');
CALL CreateAirline('0QQ', 'TAG Aviation (UK) Ltd.');
CALL CreateAirline('0RQ', 'TAG Aviation Espana S.L.');
CALL CreateAirline('0TQ', 'Corporatejets, XXI');
CALL CreateAirline('0UQ', 'Comlux Malta, Ltd.');
CALL CreateAirline('0VQ', 'Ocean Sky (UK) Limited');
CALL CreateAirline('0WQ', 'Avjet Corporation');
CALL CreateAirline('0YQ', 'Comlux Malta Ltd.');
CALL CreateAirline('10Q', 'Swiss Air Ambulance');
CALL CreateAirline('12Q', 'Unijet');
CALL CreateAirline('13Q', 'Chartright Air Inc.');
CALL CreateAirline('14Q', 'London Air Services Limited');
CALL CreateAirline('15Q', 'Air Alsie A/S');
CALL CreateAirline('16', 'PSA Airlines Inc.');
CALL CreateAirline('17', 'Piedmont Airlines');
CALL CreateAirline('17Q', 'Albinati Aeronautics SA');
CALL CreateAirline('1AQ', 'Charter Air Transport, Inc.');
CALL CreateAirline('1BQ', 'Dynamic Airways, LLC');
CALL CreateAirline('1DQ', 'Island Airlines LLC');
CALL CreateAirline('1EQ', 'KaiserAir, Inc.');
CALL CreateAirline('1FQ', 'Alsek Air');
CALL CreateAirline('1HQ', 'International Jet Management GmbH');
CALL CreateAirline('1I', 'Sky Trek International Airlines');
CALL CreateAirline('1IQ', 'Jet link AG');
CALL CreateAirline('1JQ', 'Exec Direct Aviation Services Limited');
CALL CreateAirline('1LQ', 'Bertelsmann Aviation GmbH');
CALL CreateAirline('1MQ', 'Twin Cities Air Service LLC');
CALL CreateAirline('1NQ', 'JSC The 224th Flight Unit State Airlines');
CALL CreateAirline('1PQ', 'Makani Kai Air Charters');
CALL CreateAirline('1QQ', 'City Wings Inc dba Seaflight');
CALL CreateAirline('1RQ', 'Sun Air Express LLC dba Sun Air International');
CALL CreateAirline('1SQ', 'Star Marianas Air Inc.');
CALL CreateAirline('1TQ', 'Rhoades Aviation dba Transair');
CALL CreateAirline('1UQ', 'Gainjet Aviation SA');
CALL CreateAirline('1VQ', 'Scott Air LLC dba Island Air Express');
CALL CreateAirline('1WQ', 'Ultimate JetCharters LLC dba Ultimate Air Shuttle');
CALL CreateAirline('1XQ', 'Dassault Falcon Service');
CALL CreateAirline('2E', 'Smokey Bay Air Inc.');
CALL CreateAirline('2F', 'Frontier Flying Service');
CALL CreateAirline('2K', 'Aerolineas Galapagos S A Aerogal');
CALL CreateAirline('2M', 'Midway Express Airlines');
CALL CreateAirline('2O', 'Island Air Service');
CALL CreateAirline('2R', 'Regal Air');
CALL CreateAirline('2T', 'Canada 3000 Airlines Ltd.');
CALL CreateAirline('2U', 'Valley Air Express Inc.');
CALL CreateAirline('37', 'Zeal 320');
CALL CreateAirline('3C', 'Regions Air, Inc.');
CALL CreateAirline('3F', 'Pacific Airways, Inc.');
CALL CreateAirline('3M', 'Silver Airways');
CALL CreateAirline('3S', 'AeroLogic GmbH');
CALL CreateAirline('3U', 'Sichuan Airlines Co Ltd.');
CALL CreateAirline('4B', 'Boutique Air');
CALL CreateAirline('4B (1)', 'Olson Air Service');
CALL CreateAirline('4C', 'Aerovias de Intergracian Regional');
CALL CreateAirline('4E', 'Tanana Air Service');
CALL CreateAirline('4E (1)', 'British Airtours Limited');
CALL CreateAirline('4H', 'Belize Trans Air');
CALL CreateAirline('4M', 'LAN Argentina');
CALL CreateAirline('4M (1)', 'Lan Dominica');
CALL CreateAirline('4N', 'Air North');
CALL CreateAirline('4O', 'ABC Aerolineas SA de CV dba Interjet');
CALL CreateAirline('4R', 'Regent Air Corporation');
CALL CreateAirline('4S', 'Sol Air (Aero Hunduras)');
CALL CreateAirline('4S (1)', 'Conner Air Lines Inc.');
CALL CreateAirline('4T', 'Belair Airlines Ltd.');
CALL CreateAirline('4W', 'Warbelow');
CALL CreateAirline('4Y', 'Yute Air Aka Flight Alaska');
CALL CreateAirline('5B', 'Bellair Inc.');
CALL CreateAirline('5C', 'C.A.L Cargo Airlines');
CALL CreateAirline('5D', 'Aerolitoral');
CALL CreateAirline('5F', 'Arctic Circle Air Service');
CALL CreateAirline('5G', 'Skyservice Airlines, Inc.');
CALL CreateAirline('5G (1)', 'Queen Air');
CALL CreateAirline('5J', 'Private Jet Expeditions');
CALL CreateAirline('5L', 'Aerosur');
CALL CreateAirline('5V', 'Tatonduk Outfitters Limited d/b/a Everts Air Alaska and Everts Air Cargo');
CALL CreateAirline('5X', 'United Parcel Service');
CALL CreateAirline('5Y', 'Atlas Air Inc.');
CALL CreateAirline('6A', 'Aviacsa Airlines');
CALL CreateAirline('6B', 'TUIfly Nordic A.B.');
CALL CreateAirline('6C', 'Cape Smythe Air Service');
CALL CreateAirline('6F', 'Laker Airways Inc.');
CALL CreateAirline('6H', 'Israir Airlines');
CALL CreateAirline('6P', 'Pacific East Air Inc.');
CALL CreateAirline('6R', 'Aerounion Aerotransporte de Carga Union SA de CV');
CALL CreateAirline('6U', 'Air Ukraine');
CALL CreateAirline('6Y', 'Nicaraguense De Aviacion Sa');
CALL CreateAirline('7B', 'Krasair');
CALL CreateAirline('7C', 'Jeju Air Co Ltd.');
CALL CreateAirline('7F', 'First Air');
CALL CreateAirline('7G', 'MK Airlines Ltd.');
CALL CreateAirline('7G (1)', 'Bellair Inc. (1)');
CALL CreateAirline('7H', 'Era Aviation');
CALL CreateAirline('7I', 'Insel Air International B V');
CALL CreateAirline('7M', 'Aeromonterrey S.A.');
CALL CreateAirline('7N', 'Inland Aviation Services');
CALL CreateAirline('7P', 'Apa International Air S.A.');
CALL CreateAirline('7Q', 'Pan American World Airways Dominicana');
CALL CreateAirline('7S', 'Arctic Transportation');
CALL CreateAirline('7S (1)', 'Skystar International Inc.');
CALL CreateAirline('7Z', 'Lb Limited');
CALL CreateAirline('8C', 'Air Transport International');
CALL CreateAirline('8D', 'Servant Air Inc.');
CALL CreateAirline('8E', 'Bering Air Inc.');
CALL CreateAirline('8F', 'Wilburs Inc.');
CALL CreateAirline('8J', 'Jetall Airways');
CALL CreateAirline('8L', 'Servicio Aereo Leo Lopez');
CALL CreateAirline('8N', 'Flagship Airlines Inc.');
CALL CreateAirline('8Q', 'Baker Aviation Inc.');
CALL CreateAirline('8R', 'Edelweiss Air Ag');
CALL CreateAirline('8V', 'Wright Air Service');
CALL CreateAirline('9E', 'Endeavor Air Inc.');
CALL CreateAirline('9J', 'Pacific Island Aviation');
CALL CreateAirline('9K', 'Cape Air');
CALL CreateAirline('9L', 'Colgan Air');
CALL CreateAirline('9M', 'Central Mountain Air');
CALL CreateAirline('9N', 'ANA & JP Express Co. Ltd.');
CALL CreateAirline('9R', 'Flagship Express Services');
CALL CreateAirline('9S', 'Southern Air Inc.');
CALL CreateAirline('9T', 'TravelspanGT, Inc. S.A.');
CALL CreateAirline('9V', 'Avior Airlines, C.A.');
CALL CreateAirline('9W', 'Jet Airways (India) Limited');
CALL CreateAirline('A0', 'Elysair d/b/a L''Avion');
CALL CreateAirline('A2', 'Cielos De Peru');
CALL CreateAirline('A4', 'Southern Wind Airlines');
CALL CreateAirline('A7', 'Air Comet S.A.');
CALL CreateAirline('A7 (1)', 'Air 21');
CALL CreateAirline('AA', 'American Airlines Inc.');
CALL CreateAirline('AAA', 'Associated Aviation Act.');
CALL CreateAirline('AAB', 'Antilles Air Boats Inc.');
CALL CreateAirline('AAE', 'AAA Airlines');
CALL CreateAirline('AAI', 'Audi Air Inc.');
CALL CreateAirline('AAL', 'Argosy Air Lines Inc.');
CALL CreateAirline('AAP', 'Armstrong Air Service Inc.');
CALL CreateAirline('AAQ', 'Advance Air Charters');
CALL CreateAirline('AAR', 'Altair Airlines Inc.');
CALL CreateAirline('AAT', 'Air Sunshine Inc.');
CALL CreateAirline('AAV', 'Alpine Air');
CALL CreateAirline('AAZ', 'Alaska Aeronautical Indust.');
CALL CreateAirline('AB', 'Air Berlin PLC and CO');
CALL CreateAirline('ABH', 'Air Bahia');
CALL CreateAirline('ABI', 'Airbama Incorporated');
CALL CreateAirline('ABO', 'Aeronaves Boringuena Inc.');
CALL CreateAirline('ABX', 'ABX Air, Inc.');
CALL CreateAirline('AC', 'Air Canada');
CALL CreateAirline('ACA', 'Alaska Central Airways Inc.');
CALL CreateAirline('ACD', 'Academy Airlines');
CALL CreateAirline('ACG', 'Air Cargo Express Inc.');
CALL CreateAirline('ACH', 'Island Airlines Hawaii Inc.');
CALL CreateAirline('ACI', 'AAA-Action Air Carrier Inc.');
CALL CreateAirline('ACJ', 'Atlantic Coast Jet Inc.');
CALL CreateAirline('ACK', 'Air Central Inc.');
CALL CreateAirline('ACL', 'Check-Air Inc.');
CALL CreateAirline('ACN', 'Alliance Airlines');
CALL CreateAirline('ACO', 'Air Cargo Enterprises Inc.');
CALL CreateAirline('ACP', 'Air Chaparral Inc.');
CALL CreateAirline('ACQ', 'Aeronautica De Cancun');
CALL CreateAirline('ACS', 'Alamo Commuter Airlines');
CALL CreateAirline('ACT', 'Air Central Inc. (1)');
CALL CreateAirline('ACW', 'Transwest Air Express');
CALL CreateAirline('AD', 'Avia Leasing Company');
CALL CreateAirline('ADB', 'Antonov Company');
CALL CreateAirline('ADQ', 'Aeronaves Del Peru');
CALL CreateAirline('ADR', 'Adirondack Airlines');
CALL CreateAirline('ADV', 'Advantage Airlines');
CALL CreateAirline('AE', 'Air Europe Limited');
CALL CreateAirline('AEC', 'Astec Air East Inc.');
CALL CreateAirline('AED', 'Air East Of Delaware Inc.');
CALL CreateAirline('AEF', 'Aero Freight');
CALL CreateAirline('AEO', 'Aero Coach');
CALL CreateAirline('AEQ', 'Air Caravane Inc.');
CALL CreateAirline('AEX', 'Air Excursions LLC (1)');
CALL CreateAirline('AF', 'Compagnie Natl Air France');
CALL CreateAirline('AFA', 'American Flag Airlines Inc.');
CALL CreateAirline('AFE', 'Air Florida Express');
CALL CreateAirline('AFG', 'American Flight Group');
CALL CreateAirline('AFQ', 'Aero B Venezuela C.A.');
CALL CreateAirline('AFS', 'Arcata Flying Service');
CALL CreateAirline('AGA', 'Air Cargo America Inc.');
CALL CreateAirline('AGQ', 'Argo S. A.');
CALL CreateAirline('AHA', 'Air Alpha');
CALL CreateAirline('AHC', 'Air Hawaii');
CALL CreateAirline('AHQ', 'Air National');
CALL CreateAirline('AI', 'National Aviation Company of India Limited d/b/a Air India');
CALL CreateAirline('AIA', 'All Island Air');
CALL CreateAirline('AIC', 'Air Caribbean');
CALL CreateAirline('AIE', 'Air Express Inc.');
CALL CreateAirline('AIG', 'Airgo Inc.');
CALL CreateAirline('AIK', 'Air Ketchum Idaho Inc.');
CALL CreateAirline('AIM', 'Air Mont. Inc.');
CALL CreateAirline('AIN', 'Air Indiana');
CALL CreateAirline('AIQ', 'Norontair');
CALL CreateAirline('AIT', 'Airways International');
CALL CreateAirline('AIY', 'Alliance Air');
CALL CreateAirline('AJ', 'Air Micronesia Inc.');
CALL CreateAirline('AJQ', 'Aerodynamics Inc.');
CALL CreateAirline('AKQ', 'Airmark Airlines Inc.');
CALL CreateAirline('AL', 'Skyway Airlines');
CALL CreateAirline('ALD', 'Allied Airlines');
CALL CreateAirline('ALE', 'Air-Lift Associates Inc.');
CALL CreateAirline('ALI', 'Brandt Air');
CALL CreateAirline('ALK', 'Air Link Airways');
CALL CreateAirline('ALL', 'All Seasons Air Pacific');
CALL CreateAirline('ALQ', 'Alberta Northern Airlines');
CALL CreateAirline('ALS', 'Air L.A.');
CALL CreateAirline('ALT', 'Altus Airlines');
CALL CreateAirline('ALU', 'Aleutian Air');
CALL CreateAirline('ALX', 'Atlanta Express');
CALL CreateAirline('AM', 'Aeromexico');
CALL CreateAirline('AMA', 'North American Airlines Inc.');
CALL CreateAirline('AME', 'Americair Inc.');
CALL CreateAirline('AMI', 'American Inter-Island Inc.');
CALL CreateAirline('AMQ', 'Ameristar Air Cargo');
CALL CreateAirline('AMR', 'AvAir');
CALL CreateAirline('AMT', 'American Air Transport');
CALL CreateAirline('ANB', 'Air Nebraska Inc.');
CALL CreateAirline('ANC', 'Atlantic Air');
CALL CreateAirline('AND', 'Southcentral Air Inc.');
CALL CreateAirline('ANI', 'Dash Air Corporation');
CALL CreateAirline('ANM', 'Airways Of New Mexico Inc.');
CALL CreateAirline('ANO', 'Metro Air Northeast Vermont');
CALL CreateAirline('ANT', 'Air North/Nenana');
CALL CreateAirline('AO', 'Aviacion Y Comercio S.A.');
CALL CreateAirline('AOI', 'Trans New York');
CALL CreateAirline('AON', 'Action Airlines');
CALL CreateAirline('AOQ', 'Aerovias S.A.');
CALL CreateAirline('AOR', 'Air New Orleans');
CALL CreateAirline('APE', 'Air Cape');
CALL CreateAirline('APH', 'Alpha Air');
CALL CreateAirline('API', 'Arizona Pacific Inc.');
CALL CreateAirline('APL', 'Appalachian Flying Service');
CALL CreateAirline('APN', 'Aspen Airways Inc.');
CALL CreateAirline('APQ', 'Alas De Transporte International');
CALL CreateAirline('APS', 'Air Spirit Inc.');
CALL CreateAirline('APY', 'Air Polynesia Inc.');
CALL CreateAirline('AQQ', 'Air Charter (Safa)');
CALL CreateAirline('AR', 'Aerolineas Argentinas');
CALL CreateAirline('ARA', 'Air Resorts Airlines');
CALL CreateAirline('ARB', 'Air Caribe International');
CALL CreateAirline('ARD', 'Airlift International');
CALL CreateAirline('ARI', 'Arizona Aero Corp.');
CALL CreateAirline('ARM', 'Airmarc Airlines Inc.');
CALL CreateAirline('ARN', 'Arnold Aviation');
CALL CreateAirline('ARO', 'Air Oregon');
CALL CreateAirline('ARP', 'Airspur Helicopters Inc.');
CALL CreateAirline('ARQ', 'Aerovias Colombianas Arca');
CALL CreateAirline('ARR', 'Arrowhead Airways Inc.');
CALL CreateAirline('ARS', 'Air Sedona');
CALL CreateAirline('ARZ', 'Arizona Airways');
CALL CreateAirline('AS', 'Alaska Airlines Inc.');
CALL CreateAirline('ASC', 'Air South Inc.');
CALL CreateAirline('ASD', 'Amistad Airlines');
CALL CreateAirline('ASH', 'Air South');
CALL CreateAirline('ASI', 'Alpine Air Services Inc.');
CALL CreateAirline('ASN', 'Air Casino');
CALL CreateAirline('ASP', 'Asap Air Inc.');
CALL CreateAirline('ASQ', 'Aerosur (1)');
CALL CreateAirline('ASR', 'Astor Air');
CALL CreateAirline('AST', 'Astro Airways');
CALL CreateAirline('ASU', 'Air South (1)');
CALL CreateAirline('ASW', 'Sunrise Airlines Inc.');
CALL CreateAirline('AT', 'Royal Air Maroc');
CALL CreateAirline('ATH', 'Air Southeast');
CALL CreateAirline('ATN', 'Air Atlantic Airlines Inc.');
CALL CreateAirline('ATO', 'Pacific National Airways');
CALL CreateAirline('ATQ', 'Aero Tranportes Panamenos');
CALL CreateAirline('ATS', 'Atlantis Airlines Inc.');
CALL CreateAirline('ATT', 'Aerotransit Inc.');
CALL CreateAirline('ATX', 'Air Carolina');
CALL CreateAirline('AUX', 'Austin Express Inc.');
CALL CreateAirline('AV', 'Aerovias Nacl De Colombia');
CALL CreateAirline('AVA', 'Air Vectors Airways');
CALL CreateAirline('AVC', 'Av Center Inc.');
CALL CreateAirline('AVG', 'Airvantage');
CALL CreateAirline('AVI', 'Aero Virgin Islands Corp.');
CALL CreateAirline('AVL', 'Aviation Sales');
CALL CreateAirline('AVQ', 'Aero Laguna S.A. De C.V.');
CALL CreateAirline('AVR', 'Air Vermont Inc.');
CALL CreateAirline('AVS', 'Aviation Services');
CALL CreateAirline('AVZ', 'Southern Jersey Airways');
CALL CreateAirline('AWA', 'Air West Airlines');
CALL CreateAirline('AWQ', 'Aermediterranea S.P.A.');
CALL CreateAirline('AX', 'Trans States Airlines');
CALL CreateAirline('AXQ', 'Aeron International Airlines Inc.');
CALL CreateAirline('AY', 'Finnair Oy');
CALL CreateAirline('AYQ', 'Aerodan S.A. De C.V.');
CALL CreateAirline('AZ', 'Compagnia Aerea Italiana');
CALL CreateAirline('AZP', 'Arizona Pacific Airways');
CALL CreateAirline('AZQ', 'Anglo Airlines Ltd.');
CALL CreateAirline('B6', 'JetBlue Airways');
CALL CreateAirline('BA', 'British Airways Plc');
CALL CreateAirline('BAA', 'Aero International Airlines');
CALL CreateAirline('BAC', 'Business Aircraft Corp.');
CALL CreateAirline('BAH', 'Brennan & Hargreaves Inc.');
CALL CreateAirline('BAK', 'Bankair Inc.');
CALL CreateAirline('BAN', 'Bangor International Air');
CALL CreateAirline('BAQ', 'Aero Rentas De Coahuila S.A. De C.V.');
CALL CreateAirline('BAR', 'Bard-Air Corp.');
CALL CreateAirline('BAT', 'West Penn Commuter');
CALL CreateAirline('BAY', 'Burlington Aeroplane Co.');
CALL CreateAirline('BBQ', 'Balair Ag');
CALL CreateAirline('BC', 'Skymark Airlines Inc.');
CALL CreateAirline('BCA', 'Baja Cortez Airlines');
CALL CreateAirline('BCQ', 'Bradley Air Services Ltd.');
CALL CreateAirline('BD', 'British Midland Airways Ltd.');
CALL CreateAirline('BDE', 'Jet Express');
CALL CreateAirline('BDQ', 'Aerotaxis De Aguascalientes S.A. De C.V.');
CALL CreateAirline('BE', 'Braniff International Airlines Inc.');
CALL CreateAirline('BEA', 'Business Express Airlines');
CALL CreateAirline('BEN', 'Bennington Aviation Inc.');
CALL CreateAirline('BEQ', 'Air Belgium');
CALL CreateAirline('BES', 'Aeroservices Executive');
CALL CreateAirline('BEY', 'Beyer Aviation');
CALL CreateAirline('BF', 'Markair Inc.');
CALL CreateAirline('BFG', 'Million Air');
CALL CreateAirline('BFQ', 'Buffalo Airways Inc.');
CALL CreateAirline('BG', 'Biman Bangladesh Airlines');
CALL CreateAirline('BGQ', 'Airbus Transport Internat''l');
CALL CreateAirline('BHK', 'Blackhawk Airways Inc.');
CALL CreateAirline('BHO', 'Bighorn Airways Inc.');
CALL CreateAirline('BHQ', 'Turks Air Ltd. (1)');
CALL CreateAirline('BIA', 'Big Island Air');
CALL CreateAirline('BIQ', 'Servicios Aeronauticos Z S.A. De C.V.');
CALL CreateAirline('BIR', 'Birchwood Air Service');
CALL CreateAirline('BJQ', 'Taxirey S.A. De C.V.');
CALL CreateAirline('BLQ', 'Air Bvi Limited');
CALL CreateAirline('BM', 'Belize Air International Ltd.');
CALL CreateAirline('BMT', 'Bremerton Aviation Inc.');
CALL CreateAirline('BN', 'Britannia Airways GmbH');
CALL CreateAirline('BN (1)', 'Braniff Inc.');
CALL CreateAirline('BNQ', 'NetJets Large Aircraft Company L.L.C.');
CALL CreateAirline('BOA', 'Boise Air Service');
CALL CreateAirline('BOI', 'Bo-S-Aire Airlines Inc.');
CALL CreateAirline('BOQ', 'Transp. Aereos Bolivianos');
CALL CreateAirline('BQ', 'Aeromar C. Por A.');
CALL CreateAirline('BR', 'Eva Airways Corporation');
CALL CreateAirline('BR (1)', 'Cal Air International Ltd.');
CALL CreateAirline('BRK', 'Barken International');
CALL CreateAirline('BRO', 'Brower Airways Inc.');
CALL CreateAirline('BRW', 'Barrow Air');
CALL CreateAirline('BTQ', 'Brasair Transportes Aereos');
CALL CreateAirline('BUH', 'Business Helicopters');
CALL CreateAirline('BUQ', 'Wrangler Aviation Inc.');
CALL CreateAirline('BUQ (1)', 'Blue Bell Inc.');
CALL CreateAirline('BUR', 'Burlington Airways Inc.');
CALL CreateAirline('BW', 'Caribbean Airlines Limited');
CALL CreateAirline('BXQ', 'Spantax S. A.');
CALL CreateAirline('BY', 'Britannia Airways Ltd.');
CALL CreateAirline('BYA', 'Bay Air');
CALL CreateAirline('BZQ', 'Abaco Air, Ltd.');
CALL CreateAirline('C5', 'Commutair Aka Champlain Enterprises, Inc.');
CALL CreateAirline('C6', 'Canjet Airlines');
CALL CreateAirline('C8', 'Cargolux Italia SpA');
CALL CreateAirline('C8 (1)', 'Chicago Express Airlines');
CALL CreateAirline('CA', 'Air China');
CALL CreateAirline('CAC', 'Coleman Air Transport');
CALL CreateAirline('CAF', 'California Seaboard');
CALL CreateAirline('CAI', 'Crawford Aviation Inc.');
CALL CreateAirline('CAM', 'C & M Airlines');
CALL CreateAirline('CAP', 'Metro Air Northeast N Y');
CALL CreateAirline('CAQ', 'Challenge Air Luftverkehrs GmbH');
CALL CreateAirline('CAT', 'Catalina Airlines Inc.');
CALL CreateAirline('CAV', 'Air Virginia');
CALL CreateAirline('CAZ', 'CAT Aviation');
CALL CreateAirline('CB', 'Air One Inc.');
CALL CreateAirline('CBA', 'Carriba Air Inc.');
CALL CreateAirline('CC', 'Air Atlanta Icelandic');
CALL CreateAirline('CC (1)', 'Air Atlanta Inc.');
CALL CreateAirline('CCA', 'Cityhop');
CALL CreateAirline('CCO', 'Chester County Aviation');
CALL CreateAirline('CDQ', 'Kitty Hawk International');
CALL CreateAirline('CEN', 'Cen-Tex Airlines Inc.');
CALL CreateAirline('CEQ', 'All Canada Express');
CALL CreateAirline('CET', 'Century Airlines (Cal)');
CALL CreateAirline('CF', 'Compan. De Aviacion Faucett');
CALL CreateAirline('CGA', 'Chicago Airlines');
CALL CreateAirline('CGL', 'Viking International Airlines Inc.');
CALL CreateAirline('CGO', 'Chicago Air Taxi');
CALL CreateAirline('CH', 'Bemidji Airlines');
CALL CreateAirline('CHD', 'Chandler Flyer');
CALL CreateAirline('CHE', 'Charter Airlines');
CALL CreateAirline('CHF', 'Hammonds Commuter Air Serv.');
CALL CreateAirline('CHI', 'Chitina Air Service');
CALL CreateAirline('CHL', 'Channel Flying Inc.');
CALL CreateAirline('CHO', 'Choi Aviation Inc.');
CALL CreateAirline('CHS', 'Christman Air System');
CALL CreateAirline('CHT', 'Charter One');
CALL CreateAirline('CI', 'China Airlines Ltd.');
CALL CreateAirline('CIQ', 'A/S Conair');
CALL CreateAirline('CIS', 'Cal Sierra Airlines');
CALL CreateAirline('CJ', 'Colgan Airways Inc.');
CALL CreateAirline('CK', 'China Cargo Airline');
CALL CreateAirline('CKI', 'Inlet Airlines');
CALL CreateAirline('CL', 'Capitol International Inc.');
CALL CreateAirline('CLB', 'Columbia Pacific Airlines');
CALL CreateAirline('CLD', 'Hawaii Pacific Helicopters');
CALL CreateAirline('CLF', 'California Air Shuttle');
CALL CreateAirline('CLQ', 'Aero Transcolombiana');
CALL CreateAirline('CM', 'Compania Panamena (Copa)');
CALL CreateAirline('CMB', 'Combs Airways Inc.');
CALL CreateAirline('CMD', 'Command Airways Inc.');
CALL CreateAirline('CMQ', 'Servicio De Carga Aerea Sa');
CALL CreateAirline('CMR', 'Commuter Airlines (Ca)');
CALL CreateAirline('CNN', 'Centennial Airlines');
CALL CreateAirline('CO', 'Continental Air Lines Inc.');
CALL CreateAirline('COB', 'Cotton Belt Aviation Inc.');
CALL CreateAirline('COC', 'Cochise Airlines Inc.');
CALL CreateAirline('COK', 'Coker Aviation Inc.');
CALL CreateAirline('COL', 'Presidential Express');
CALL CreateAirline('COM', 'Commutair');
CALL CreateAirline('COR', 'Coral Air Inc.');
CALL CreateAirline('COS', 'Cosmopolitan Comm. Airline');
CALL CreateAirline('COT', 'Southeastern Commuter');
CALL CreateAirline('COU', 'Courtesy Air Service Inc.');
CALL CreateAirline('CP', 'Compass Airlines');
CALL CreateAirline('CP (1)', 'Canadian Airlines International Ltd.');
CALL CreateAirline('CPA', 'Capitol Air Lines');
CALL CreateAirline('CPC', 'Coastal Plains Commuter Inc.');
CALL CreateAirline('CPQ', 'Capitol Air Express Inc.');
CALL CreateAirline('CPT', 'Capitol Air');
CALL CreateAirline('CQI', 'Conquest Airline Corp.');
CALL CreateAirline('CRA', 'Commuter Airlines');
CALL CreateAirline('CRB', 'Caribair');
CALL CreateAirline('CRE', 'Caribbean Express Inc.');
CALL CreateAirline('CRH', 'Cresent Medivac');
CALL CreateAirline('CRN', 'Crown Aviaiton Inc.');
CALL CreateAirline('CRO', 'Crown Airways Inc.');
CALL CreateAirline('CRP', 'Corporate Air');
CALL CreateAirline('CRT', 'Crested Butte Air Service');
CALL CreateAirline('CRV', 'Acropolis Aviation Ltd.');
CALL CreateAirline('CS', 'Continental Micronesia');
CALL CreateAirline('CSA', 'Casino Airlines');
CALL CreateAirline('CSK', 'Catskill Airways Inc.');
CALL CreateAirline('CSL', 'Central States Air Lines');
CALL CreateAirline('CSM', 'Chisum Flying Service');
CALL CreateAirline('CSN', 'Casino Airlines (1)');
CALL CreateAirline('CSQ', 'Celtic Tech Jet Ltd.');
CALL CreateAirline('CTA', 'Century Airlines');
CALL CreateAirline('CTH', 'Cothron Aviation');
CALL CreateAirline('CTL', 'Coastal Air Transport');
CALL CreateAirline('CTQ', 'Custom Air Transport');
CALL CreateAirline('CTR', 'Chartair');
CALL CreateAirline('CUQ', 'Caicos Caribbean Airways');
CALL CreateAirline('CUS', 'Custom Air Service');
CALL CreateAirline('CV', 'Cargolux Airlines International S.A');
CALL CreateAirline('CVA', 'Catalina-Vegas Airlines');
CALL CreateAirline('CVQ', 'Caraven S.A.');
CALL CreateAirline('CW', 'Air Marshall Islands Inc.');
CALL CreateAirline('CWQ', 'Canadian Aviation Express');
CALL CreateAirline('CX', 'Cathay Pacific Airways Ltd.');
CALL CreateAirline('CYQ', 'Corse Air International');
CALL CreateAirline('CZ', 'China Southern Airlines');
CALL CreateAirline('CZ (1)', 'Cascade Airways Inc.');
CALL CreateAirline('CZQ', 'Aviation Concepts');
CALL CreateAirline('DA', 'Dan Air Services');
CALL CreateAirline('DAN', 'Danbury Airlines');
CALL CreateAirline('DAU', 'Dauphin Island Airways');
CALL CreateAirline('DC', 'Caribbean Air Cargo Co Ltd.');
CALL CreateAirline('DE', 'Condor Flugdienst');
CALL CreateAirline('DEA', 'Downeast Airlines Inc.');
CALL CreateAirline('DEC', 'Decatur Aviation');
CALL CreateAirline('DFS', 'Downeast Flying Service');
CALL CreateAirline('DH', 'Independence Air');
CALL CreateAirline('DH (1)', 'Discovery Airways Inc.');
CALL CreateAirline('DHL', 'DHL Airlines Inc.');
CALL CreateAirline('DHQ', 'DHL Aero Expresso');
CALL CreateAirline('DIA', 'Drummond Island Air');
CALL CreateAirline('DIC', 'Dickman Aviation Services');
CALL CreateAirline('DIR', 'Northern Star');
CALL CreateAirline('DL', 'Delta Air Lines Inc.');
CALL CreateAirline('DM', 'Maersk Air I/S');
CALL CreateAirline('DO', 'Compania Dominicana De Avia');
CALL CreateAirline('DOL', 'Dolphin Airways Inc.');
CALL CreateAirline('DOQ', 'Aerolineas Dominicanas S A');
CALL CreateAirline('DPA', 'Desert Pacific Airways');
CALL CreateAirline('DPI', 'Desert Pacific Airlines Inc.');
CALL CreateAirline('DQQ', 'Caribwest Airways Ltd.');
CALL CreateAirline('DSA', 'Desert Sun Airlines');
CALL CreateAirline('DST', 'Desert Airlines');
CALL CreateAirline('DUL', 'Dulles Express');
CALL CreateAirline('DUZ', 'Summit Airlines Inc.');
CALL CreateAirline('DVO', 'Devoe Airlines');
CALL CreateAirline('DWN', 'Dawn Air');
CALL CreateAirline('DXA', 'Dolphin Express');
CALL CreateAirline('DY', 'Norwegian Air Shuttle ASA');
CALL CreateAirline('E0', 'EOS Airlines, Inc.');
CALL CreateAirline('E7', 'Estafeta Carga Aereas');
CALL CreateAirline('E72', 'European Aviation Air Charter');
CALL CreateAirline('E8', 'USAfrica Airways Inc.');
CALL CreateAirline('E9', 'Boston-Maine Airways');
CALL CreateAirline('EA', 'Eastern Air Lines Inc.');
CALL CreateAirline('EAI', 'Executive Aviation Inc.');
CALL CreateAirline('EAQ', 'Executive Airlines, SL');
CALL CreateAirline('EAS', 'Eastern Caribbean Airways');
CALL CreateAirline('EAT', 'Eastman Airways Inc.');
CALL CreateAirline('EBQ', 'Execaire Aviation Ltd.');
CALL CreateAirline('ECA', 'Eagle Airlines (1)');
CALL CreateAirline('ECI', 'Eastern Carolina Aviation');
CALL CreateAirline('ECL', 'Eclipse Airlines');
CALL CreateAirline('ECQ', 'Trans American Charter');
CALL CreateAirline('ECR', 'East Coast Airways');
CALL CreateAirline('ED', 'Andes');
CALL CreateAirline('EDE', 'Ede Aire');
CALL CreateAirline('EET', 'Exec Express II');
CALL CreateAirline('EEX', 'Exec Express');
CALL CreateAirline('EEZ', 'Eagle Aviation Inc.');
CALL CreateAirline('EFA', 'Executive Four Winds');
CALL CreateAirline('EFQ', 'Trans Europ. Airways France');
CALL CreateAirline('EGA', 'Eagle Airline');
CALL CreateAirline('EGJ', 'Eagle Jet Charter');
CALL CreateAirline('EGL', 'Eagle Commuter Airlines Inc.');
CALL CreateAirline('EH', 'Saeta Airlines');
CALL CreateAirline('EHA', 'East Hampton Aire Inc.');
CALL CreateAirline('EI', 'Aer Lingus Plc');
CALL CreateAirline('EIA', 'East. Indiana Aviation Sale');
CALL CreateAirline('EJQ', 'Aeroejecutivos C.A.');
CALL CreateAirline('EK', 'Emirates');
CALL CreateAirline('EKA', 'Air Pacific Inc.');
CALL CreateAirline('ELL', 'Ellis Air Taxi Inc.');
CALL CreateAirline('EM', 'Empire Airlines Inc.');
CALL CreateAirline('EMA', 'Emerald Airlines');
CALL CreateAirline('EME', 'Metro Express');
CALL CreateAirline('EMP', 'Empire Airlines Inc. (2)');
CALL CreateAirline('ENT', 'Enterprise Airlines Inc.');
CALL CreateAirline('EOQ', 'Aeroservicios Ecuatorianos');
CALL CreateAirline('EP', 'All Star Airlines Inc.');
CALL CreateAirline('EQ', 'Tame Linea Aerea del Ecuador Tme EP');
CALL CreateAirline('ER', 'Astar USA, LLC');
CALL CreateAirline('ERI', 'Erie Airways Inc.');
CALL CreateAirline('ERO', 'Empire Aero Service');
CALL CreateAirline('ERQ', 'Aero Trades (Western) Ltd.');
CALL CreateAirline('ESQ', 'Seagreen Air Transport');
CALL CreateAirline('ET', 'Ethiopian Airlines');
CALL CreateAirline('EU', 'Ecuatoriana De Aviacion');
CALL CreateAirline('EUQ', 'Air Atlanta Europe');
CALL CreateAirline('EV', 'ExpressJet Airlines Inc.');
CALL CreateAirline('EVA', 'Evanston Aviation');
CALL CreateAirline('EWA', 'Rio Grande Air');
CALL CreateAirline('EXA', 'Columbia Pacific Airlines (1)');
CALL CreateAirline('EXC', 'Hapag-Lloyd Executive GmbH');
CALL CreateAirline('EXC (1)', 'Executive Charter');
CALL CreateAirline('EXP', 'Express Airlines II');
CALL CreateAirline('EXQ', 'Export Air Del Peru S.A.');
CALL CreateAirline('EXR', 'Executive Transport');
CALL CreateAirline('EY', 'Etihad Airways');
CALL CreateAirline('EZ', 'Evergreen International Inc.');
CALL CreateAirline('F2', 'Omega Air Holdings d/b/a Focus Air');
CALL CreateAirline('F8', 'Freedom Airlines d/b/a HP Expr');
CALL CreateAirline('F9', 'Frontier Airlines Inc.');
CALL CreateAirline('FAA', 'Falwell Aviation Inc.');
CALL CreateAirline('FAC', 'Falcon Airways Inc.');
CALL CreateAirline('FAQ', 'Fast Air Carrier Ltd. (1)');
CALL CreateAirline('FAR', 'Federal Armored Service Inc.');
CALL CreateAirline('FB', 'Translift Airways Limited');
CALL CreateAirline('FBI', 'Young Flying Service');
CALL CreateAirline('FCA', 'Southern Airlines Inc.');
CALL CreateAirline('FCQ', 'Falcon Air Express');
CALL CreateAirline('FD', 'Air Puerto Rico Airlines');
CALL CreateAirline('FDA', 'Florida Airlines Inc.');
CALL CreateAirline('FDM', 'Freedom Airlines Inc.');
CALL CreateAirline('FDQ', 'Great American Airways');
CALL CreateAirline('FE', 'Primaris Airlines Inc.');
CALL CreateAirline('FF', 'Tower Air Inc.');
CALL CreateAirline('FFQ', 'Five Star Airlines');
CALL CreateAirline('FH', 'Frontier Horizon Inc.');
CALL CreateAirline('FI', 'Icelandair');
CALL CreateAirline('FJ', 'Air Pacific Ltd.');
CALL CreateAirline('FJ (1)', 'Air Pacific Ltd. (1)');
CALL CreateAirline('FL', 'AirTran Airways Corporation');
CALL CreateAirline('FL (1)', 'Frontier Airlines Inc. (1)');
CALL CreateAirline('FLA', 'Florida Air');
CALL CreateAirline('FLM', 'Flamenco Airways Inc.');
CALL CreateAirline('FLR', 'Flirite Inc.');
CALL CreateAirline('FNQ', 'Fine Airlines Inc.');
CALL CreateAirline('FOR', 'Ford-Aire Inc.');
CALL CreateAirline('FOS', 'Foster Aviation');
CALL CreateAirline('FP', 'TAG Aviation S.A.');
CALL CreateAirline('FQ', 'Air Aruba');
CALL CreateAirline('FRA', 'Freedom Air');
CALL CreateAirline('FRS', 'Four Star Aviation');
CALL CreateAirline('FRT', 'Frontier Commuter');
CALL CreateAirline('FRW', 'Farwest Airlines');
CALL CreateAirline('FS', 'Serv De Trans Aereos Fuegui');
CALL CreateAirline('FSA', 'F.S. Air Service');
CALL CreateAirline('FT', 'Flying Tiger Line Inc.');
CALL CreateAirline('FTI', 'Southern Airways');
CALL CreateAirline('FVA', 'Skycraft Inc.');
CALL CreateAirline('FW', 'Skybus Inc.');
CALL CreateAirline('FWA', 'Far West Airlines');
CALL CreateAirline('FX', 'Federal Express Corporation');
CALL CreateAirline('FYB', 'Flying Boat');
CALL CreateAirline('G3', 'VRG Linhas Aereas S A');
CALL CreateAirline('G3 (1)', 'Aerochago S.A.');
CALL CreateAirline('G4', 'Allegiant Air');
CALL CreateAirline('G7', 'GoJet Airlines, LLC d/b/a United Express');
CALL CreateAirline('GA', 'P.T. Garuda Indonesian Arwy');
CALL CreateAirline('GAL', 'Galena Air Service');
CALL CreateAirline('GAQ', 'Galaxy Airlines Inc.');
CALL CreateAirline('GAS', 'General Aviation Inc.');
CALL CreateAirline('GAT', 'Gulf Air Taxi');
CALL CreateAirline('GAV', 'Gromer Aviation Inc.');
CALL CreateAirline('GBA', 'Central States Airline');
CALL CreateAirline('GBQ', 'G5 Executive Ag');
CALL CreateAirline('GCA', 'Golden Carriage Aire');
CALL CreateAirline('GCH', 'Grand Canyon Helicopters');
CALL CreateAirline('GCQ', 'General Air Cargo');
CALL CreateAirline('GCS', 'Midway Commuter');
CALL CreateAirline('GD', 'Transp. Aereos Ejecutivos');
CALL CreateAirline('GDW', 'Golden West Airlines Inc.');
CALL CreateAirline('GE', 'Lufthansa Cargo Airlines');
CALL CreateAirline('GF', 'Gulf Air Company');
CALL CreateAirline('GF (1)', 'Gulf Air Transport Inc.');
CALL CreateAirline('GFC', 'Gulf Flite Center');
CALL CreateAirline('GFQ', 'Gulf And Caribbean Cargo');
CALL CreateAirline('GG', 'Cargo 360, Inc.');
CALL CreateAirline('GG (1)', 'Tropical Airways Inc.');
CALL CreateAirline('GG (2)', 'Grenada Airways Ltd.');
CALL CreateAirline('GH', 'Ghana Airways Corporation');
CALL CreateAirline('GHA', 'Green Hills Aviation Ltd.');
CALL CreateAirline('GIQ', 'Global International Airways Corp.');
CALL CreateAirline('GJ', 'Eurofly S.p.A');
CALL CreateAirline('GJ (1)', 'Mexicargo');
CALL CreateAirline('GKQ', 'Laker Airways');
CALL CreateAirline('GL', 'Miami Air International');
CALL CreateAirline('GLW', 'Golden West Airlines Co.');
CALL CreateAirline('GM', 'Air America');
CALL CreateAirline('GMA', 'Green Mountain Airlines Ltd.');
CALL CreateAirline('GOF', 'Copper State Airlines');
CALL CreateAirline('GPA', 'GP Express Airlines');
CALL CreateAirline('GQ', 'Big Sky Airlines Inc.');
CALL CreateAirline('GR', 'Gemini Air Cargo Airways');
CALL CreateAirline('GRA', 'Gorda Aero Service');
CALL CreateAirline('GRD', 'Grand Canyon Airlines');
CALL CreateAirline('GRO', 'Isle Royale Seaplane Serv.');
CALL CreateAirline('GS', 'Air Foyle Limited');
CALL CreateAirline('GSA', 'Golden Gate Airlines Inc.');
CALL CreateAirline('GSC', 'GCS Air Service');
CALL CreateAirline('GSL', 'Golden South Airlines Inc.');
CALL CreateAirline('GSQ', 'Global Supply System');
CALL CreateAirline('GST', 'Golden State Airlines');
CALL CreateAirline('GU', 'Aviateca');
CALL CreateAirline('GUL', 'Gull Air Inc.');
CALL CreateAirline('GUN', 'Gunnel Aviation Inc.');
CALL CreateAirline('GV', 'Grant Aviation');
CALL CreateAirline('GW', 'Central American Airlines');
CALL CreateAirline('GWA', 'Great Western Aviation');
CALL CreateAirline('GWE', 'Ross Aviation Inc.');
CALL CreateAirline('GX', 'Air Ontario Limited');
CALL CreateAirline('GY', 'Guyana Airways Corporation');
CALL CreateAirline('H2', 'City Bird');
CALL CreateAirline('H5', 'Magadan Airlines');
CALL CreateAirline('H6', 'Hageland Aviation Service');
CALL CreateAirline('HA', 'Hawaiian Airlines Inc.');
CALL CreateAirline('HAQ', 'Hapag Lloyd Flug.');
CALL CreateAirline('HAR', 'Friendship Air Alaska');
CALL CreateAirline('HB', 'Homer Air');
CALL CreateAirline('HB (1)', 'Air Club International');
CALL CreateAirline('HBQ', 'Harris Air Services');
CALL CreateAirline('HCQ', 'Av Atlantic');
CALL CreateAirline('HEL', 'Helitrans');
CALL CreateAirline('HEP', 'Hub Express');
CALL CreateAirline('HER', 'Markair Express');
CALL CreateAirline('HET', 'Helitac Aviation');
CALL CreateAirline('HEU', 'Heussler Air Service Corp');
CALL CreateAirline('HFQ', 'Haiti Air Freight Intl');
CALL CreateAirline('HFS', 'Hensley Flying Service Inc.');
CALL CreateAirline('HIQ', 'Business Flights Ltd.');
CALL CreateAirline('HJ', 'Air Haiti S. A.');
CALL CreateAirline('HK', 'Time Air Sweden Ab');
CALL CreateAirline('HLQ', 'Heavylift Cargo Airlines Lt');
CALL CreateAirline('HMZ', 'Long Island Airlines');
CALL CreateAirline('HNS', 'Haines Airways');
CALL CreateAirline('HOL', 'Holiday Airlines Inc.');
CALL CreateAirline('HOQ', 'Holidair Airways');
CALL CreateAirline('HOR', 'Iowa Airlines');
CALL CreateAirline('HP', 'America West Airlines Inc. (Merged with US Airways 9/05. Stopped reporting 10/07.)');
CALL CreateAirline('HPZ', 'Pacific Coast Airlines');
CALL CreateAirline('HQ', 'Harmony Airways');
CALL CreateAirline('HQ (1)', 'Business Express');
CALL CreateAirline('HQQ', 'Harlequin Air Corporation');
CALL CreateAirline('HRA', 'Trans-National Airlines Haw');
CALL CreateAirline('HRG', 'Heritage Airlines');
CALL CreateAirline('HRQ', 'Tar Airlines');
CALL CreateAirline('HRZ', 'Allegheny Airlines');
CALL CreateAirline('HSV', 'Harbor Air Service');
CALL CreateAirline('HSZ', 'Scenic Airlines Inc.');
CALL CreateAirline('HU', 'Hainan Airlines Company Limited');
CALL CreateAirline('HUB', 'Skystream Airlines');
CALL CreateAirline('HVQ', 'Transavia Holland B. V.');
CALL CreateAirline('HWK', 'Hawking Corporation');
CALL CreateAirline('HX', 'Guy-America Airways Inc.');
CALL CreateAirline('HY', 'Uzbekistan Airways');
CALL CreateAirline('HYA', 'Hyannis Aviation');
CALL CreateAirline('IA', 'Iraqi Airways');
CALL CreateAirline('IB', 'Iberia Air Lines Of Spain');
CALL CreateAirline('ICF', 'Iowa City Flying Service');
CALL CreateAirline('ICH', 'Island Air Charters');
CALL CreateAirline('ICQ', 'Iscargo Hf');
CALL CreateAirline('IDQ', 'Intl Air Service Co. Ltd.');
CALL CreateAirline('IEX', 'Island Air Express');
CALL CreateAirline('IG', 'Meridiana S.p.A');
CALL CreateAirline('IGA', 'Global Jet Austria, GmbH');
CALL CreateAirline('III', 'Idee Industries Inc.');
CALL CreateAirline('IJ', 'Great Wall Airlines Company Limited');
CALL CreateAirline('IKQ', 'Tradewinds Airways Ltd.');
CALL CreateAirline('IMP', 'Imperial Airlines Inc.');
CALL CreateAirline('IN', 'Aerlinte Eireann Teoranta');
CALL CreateAirline('INA', 'Inland Empire Airlines Inc.');
CALL CreateAirline('IND', 'Indiana Airways Inc. (Pa)');
CALL CreateAirline('INQ', 'Independent Air Inc.');
CALL CreateAirline('IOW', 'Iowa Airways');
CALL CreateAirline('IPI', 'Indo-Pacific International');
CALL CreateAirline('IPQ', 'Aruba Cargo');
CALL CreateAirline('IPS', 'Island Express');
CALL CreateAirline('IR', 'Iran National Airlines Corp');
CALL CreateAirline('IRQ', 'Interstate Airlines Inc.');
CALL CreateAirline('ISL', 'Island Airlines');
CALL CreateAirline('ITQ', 'Interamericana De Aviacion');
CALL CreateAirline('IW', 'Air Liberte Aka Aom Minerve');
CALL CreateAirline('IW (1)', 'Best Airlines Inc.');
CALL CreateAirline('IXQ', 'Inair');
CALL CreateAirline('J5', 'Alaska Seaplane Service');
CALL CreateAirline('J6', 'Larrys Flying Service');
CALL CreateAirline('J7', 'Valujet Airlines Inc.');
CALL CreateAirline('JAG', 'JetAlliance Flugbetriebs d/b/a JAF Airservice');
CALL CreateAirline('JAM', 'Sunbelt Airlines Inc.');
CALL CreateAirline('JAQ', 'Jamaica Air Freighters');
CALL CreateAirline('JB', 'Helijet International Inc.');
CALL CreateAirline('JCM', 'Air Chico');
CALL CreateAirline('JCQ', 'Jet Connection Businessflight Ag');
CALL CreateAirline('JCZ', 'Rocky Mountain Airways Inc.');
CALL CreateAirline('JD', 'Japan Air System Co. Ltd.');
CALL CreateAirline('JER', 'Jer-Don Air');
CALL CreateAirline('JF', 'L.A.B. Flying Service Inc.');
CALL CreateAirline('JI', 'Jade Cargo International');
CALL CreateAirline('JI (1)', 'Midway Airlines Inc.');
CALL CreateAirline('JIQ', 'Jet Fleet Intl. Airlines');
CALL CreateAirline('JJ', 'Transportes Aeros Meridiona');
CALL CreateAirline('JK', 'Spanair S.A.');
CALL CreateAirline('JK (1)', 'Sunworld International Airways Inc.');
CALL CreateAirline('JKQ', 'Express One International Inc.');
CALL CreateAirline('JL', 'Japan Air Lines Co. Ltd.');
CALL CreateAirline('JM', 'Air Jamaica Limited');
CALL CreateAirline('JMA', 'Jim Air Inc.');
CALL CreateAirline('JN', 'Excel Airways');
CALL CreateAirline('JO', 'Jalways Co. Ltd.');
CALL CreateAirline('JQ', 'Jetstar Airways Pty Limited');
CALL CreateAirline('JR', 'Aero California');
CALL CreateAirline('JTA', 'Jetaire Airlines Inc.');
CALL CreateAirline('JU', 'Yugoslav Airlines');
CALL CreateAirline('JW', 'Arrow Air Inc.');
CALL CreateAirline('JX', 'Southeast Airlines');
CALL CreateAirline('JX (1)', 'Jes Air Ltd.');
CALL CreateAirline('JXQ', 'Allarco Developments Ltd.');
CALL CreateAirline('JZ', 'Japan Air Charter Co. Ltd.');
CALL CreateAirline('K3', 'Venture Travel LLC d/b/a Taquan Air Service');
CALL CreateAirline('K5', 'SeaPort Airlines, Inc. d/b/a Wings of Alaska');
CALL CreateAirline('K7', 'Arizona Express');
CALL CreateAirline('K8', 'Caribbean Sun Airlines, Inc. d/b/a World Atlantic Airlines');
CALL CreateAirline('K8 (1)', 'Dutch Caribbean Airlines');
CALL CreateAirline('KA', 'Hong Kong Dragonair');
CALL CreateAirline('KAH', 'Kenmore Air Harbor');
CALL CreateAirline('KAI', 'Knight Airlines Inc.');
CALL CreateAirline('KAQ', 'Kalitta Air LLC');
CALL CreateAirline('KAT', 'Katmai Air');
CALL CreateAirline('KB', 'Haiti Air');
CALL CreateAirline('KE', 'Korean Air Lines Co. Ltd.');
CALL CreateAirline('KEA', 'Keene Airways');
CALL CreateAirline('KEE', 'Key Airlines');
CALL CreateAirline('KET', 'Ketchikan Air Service');
CALL CreateAirline('KFS', 'King Flying Service');
CALL CreateAirline('KH', 'Aloha Air Cargo');
CALL CreateAirline('KI', 'Time Air Ltd.');
CALL CreateAirline('KIN', 'Golden Pacific Airlines');
CALL CreateAirline('KKQ', 'Transmeridian Air Cargo Ltd.');
CALL CreateAirline('KL', 'Klm Royal Dutch Airlines');
CALL CreateAirline('KLQ', 'Kalitta Charters II');
CALL CreateAirline('KM', 'Air Malta');
CALL CreateAirline('KN', 'Morris Air Corporation');
CALL CreateAirline('KO', 'Alaska Central Express');
CALL CreateAirline('KOD', 'Kodiak Airways Inc.');
CALL CreateAirline('KP', 'Kiwi International');
CALL CreateAirline('KR', 'Kitty Hawk Aircargo');
CALL CreateAirline('KR (1)', 'Kar-Air Oy');
CALL CreateAirline('KS', 'Peninsula Airways Inc.');
CALL CreateAirline('KTQ', 'Turks Air Ltd.');
CALL CreateAirline('KU', 'Kuwait Airways Corp.');
CALL CreateAirline('KW', 'Carnival Air Lines Inc.');
CALL CreateAirline('KWQ', 'Kelowna Flightcraft Air Cha');
CALL CreateAirline('KWZ', 'Crown Air');
CALL CreateAirline('KX', 'Cayman Airways Limited');
CALL CreateAirline('KXZ', 'Chaparral Airlines Inc.');
CALL CreateAirline('KZ', 'Nippon Cargo Airlines');
CALL CreateAirline('L2', 'Lynden Air Cargo Airlines');
CALL CreateAirline('L3', 'Lynx Aviation d/b/a Frontier Airlines');
CALL CreateAirline('L7', 'Lan Colombia');
CALL CreateAirline('LA', 'Lan-Chile Airlines');
CALL CreateAirline('LAA', 'La Skycab Airline');
CALL CreateAirline('LAH', 'La Helicopter');
CALL CreateAirline('LAN', 'Lancer Aviation Inc.');
CALL CreateAirline('LAP', 'Lapsa');
CALL CreateAirline('LAR', 'Laredo Air');
CALL CreateAirline('LAS', 'Lake Union Air Service');
CALL CreateAirline('LAW', 'Lawrence Aviation');
CALL CreateAirline('LB', 'Lloyd Aereo Boliviano S. A.');
CALL CreateAirline('LBQ', 'Millon Air Inc.');
CALL CreateAirline('LC', 'Varig Logistica S/A');
CALL CreateAirline('LC (1)', 'Lineas Aereas Del Caribe');
CALL CreateAirline('LC (2)', 'Legend Airlines');
CALL CreateAirline('LCQ', 'Latcr');
CALL CreateAirline('LCT', 'Lake Coastal');
CALL CreateAirline('LEQ', 'Le Point Air');
CALL CreateAirline('LEX', 'L''Express');
CALL CreateAirline('LF', 'Jettrain Airlines');
CALL CreateAirline('LG', 'Luxair');
CALL CreateAirline('LGQ', 'Lineas Aereas Allegro');
CALL CreateAirline('LH', 'Lufthansa German Airlines');
CALL CreateAirline('LHA', 'Havasu Airlines');
CALL CreateAirline('LIQ', 'Liat (1974) Limited');
CALL CreateAirline('LJ', 'Jin Air Co Ltd.');
CALL CreateAirline('LKN', 'Loken Aviation');
CALL CreateAirline('LLA', 'Lakeland Aviation');
CALL CreateAirline('LNQ', 'Aerolineas Latinas');
CALL CreateAirline('LO', 'Polskie Linie Lotnicze');
CALL CreateAirline('LOQ', 'Lorair Ltd.');
CALL CreateAirline('LOS', 'Aero Commuter');
CALL CreateAirline('LP', 'Lan Peru Airlines');
CALL CreateAirline('LP (1)', 'The Hawaii Express Inc.');
CALL CreateAirline('LR', 'Lacsa');
CALL CreateAirline('LRQ', 'Air Liberte');
CALL CreateAirline('LSQ', 'Lineas Aereas Suramerican');
CALL CreateAirline('LSZ', 'Alaska Island Air Inc.');
CALL CreateAirline('LT', 'Luftransport-Unternehmen');
CALL CreateAirline('LU', 'Air Atlantic Dominicana');
CALL CreateAirline('LUQ', 'Lineas Aereas La-Tur Sa');
CALL CreateAirline('LVA', 'Las Vegas Airlines');
CALL CreateAirline('LW', 'Pacific Wings Airlines');
CALL CreateAirline('LX', 'Swiss International Airlines');
CALL CreateAirline('LXQ', 'Translux Intl Airlines');
CALL CreateAirline('LY', 'El Al Israel Airlines Ltd.');
CALL CreateAirline('LZ', 'Balkan Bulgarian Airlines');
CALL CreateAirline('LZQ', 'Leisure International Airways Ltd.');
CALL CreateAirline('M3', 'ABSA-Aerolinhas Brasileiras');
CALL CreateAirline('M6', 'Amerijet International');
CALL CreateAirline('M7', 'Aerotransportes Mas De Crga');
CALL CreateAirline('MA', 'Malev Hungarian Airlines');
CALL CreateAirline('MAA', 'Maui Airlines');
CALL CreateAirline('MAC', 'Mackey International Inc.');
CALL CreateAirline('MAE', 'Mid-Atlantic Exp. Airlines');
CALL CreateAirline('MAG', 'Magum Airlines');
CALL CreateAirline('MAI', 'The Maui Commuter');
CALL CreateAirline('MAQ', 'Millardair Limited');
CALL CreateAirline('MAR', 'Marshall''s Air Inc.');
CALL CreateAirline('MAV', 'Maverick Airways');
CALL CreateAirline('MAX', 'Maxair Inc.');
CALL CreateAirline('MB', 'Samoa Airlines Inc.');
CALL CreateAirline('MC', 'Transtar Airlines Corp.');
CALL CreateAirline('MCO', 'Mid Continental Airlines In');
CALL CreateAirline('MDC', 'Midcontinent Airlines');
CALL CreateAirline('MDU', 'Metro Airlines');
CALL CreateAirline('ME', 'Middle East Airlines S.A.L.');
CALL CreateAirline('MEA', 'Manhattan Express');
CALL CreateAirline('MET', 'Metroplex Airlines');
CALL CreateAirline('MEX', 'Metro Express 11');
CALL CreateAirline('MG', 'Champion Air');
CALL CreateAirline('MGQ', 'Montana Austria Flugetrieb');
CALL CreateAirline('MH', 'Malaysian Airline System');
CALL CreateAirline('MHK', 'Mohawk Airlines');
CALL CreateAirline('MHO', 'Mahalo Air');
CALL CreateAirline('MIN', 'Minuteman Aviation Inc.');
CALL CreateAirline('MIS', 'Midstate Airlines Inc.');
CALL CreateAirline('MIY', 'Midway Aviation Inc.');
CALL CreateAirline('MJ', 'Lapa-Lineas Aereas Privadas');
CALL CreateAirline('MKQ', 'Airmark Corporation');
CALL CreateAirline('ML', 'Aero Costa Rica');
CALL CreateAirline('ML (1)', 'Midway Airlines Inc. (1)');
CALL CreateAirline('MLL', 'Miller Air Transportersinc');
CALL CreateAirline('MLX', 'Merlin Express');
CALL CreateAirline('MM', 'Euro Atlantic Airways');
CALL CreateAirline('MM (1)', 'Sociedad Aeronautica De Med');
CALL CreateAirline('MMH', 'Ocean Airways Inc.');
CALL CreateAirline('MNA', 'M & N Aviation');
CALL CreateAirline('MNZ', 'Cumberland Airlines');
CALL CreateAirline('MOQ', 'Morningstar Air Express');
CALL CreateAirline('MP', 'Martinair Holland N.V.');
CALL CreateAirline('MPA', 'Mid Pacific Airlines Inc.');
CALL CreateAirline('MPC', 'Mid Pacific Air Corp.');
CALL CreateAirline('MQ', 'Envoy Air');
CALL CreateAirline('MRC', 'Marco Island Airways Inc.');
CALL CreateAirline('MRQ', 'National Air Cargo Group, Inc. d/b/a Murray Air');
CALL CreateAirline('MRR', 'Merrimack Aviation Inc.');
CALL CreateAirline('MS', 'Egyptair');
CALL CreateAirline('MST', 'Midwest Aviation');
CALL CreateAirline('MT', 'Thomas Cook Airlines Uk Ltd.');
CALL CreateAirline('MT (1)', 'Flying Colours Airlines Ltd.');
CALL CreateAirline('MTA', 'Arkansas Traveler Airline');
CALL CreateAirline('MTR', 'Metroflight Airlines');
CALL CreateAirline('MTV', 'Mst Aviation');
CALL CreateAirline('MTX', 'Mountain Air Express');
CALL CreateAirline('MU', 'China Eastern Airlines');
CALL CreateAirline('MU (1)', 'Mcclain Airlines Inc.');
CALL CreateAirline('MUA', 'Manu''a Air Transport');
CALL CreateAirline('MUQ', 'Aerolineas Mundo');
CALL CreateAirline('MVA', 'Mississippi Valley Airlines');
CALL CreateAirline('MW', 'Mokulele Flight Services, Inc.');
CALL CreateAirline('MWA', 'Mountain West Airlines');
CALL CreateAirline('MX', 'Compania Mexicana De Aviaci');
CALL CreateAirline('MY', 'MAXjet');
CALL CreateAirline('MYQ', 'Lineas Aereas Mayas (Lamsa)');
CALL CreateAirline('MZ', 'P.N. Merpati Nusantara Air.');
CALL CreateAirline('N5', 'Skagway Air Service');
CALL CreateAirline('N5 (1)', 'Nations Air Express Inc.');
CALL CreateAirline('N6', 'Aero Continente');
CALL CreateAirline('N7', 'National Airlines');
CALL CreateAirline('NA', 'North American Airlines');
CALL CreateAirline('NAC', 'National Air Commuter Inc.');
CALL CreateAirline('NAP', 'Npa Inc.');
CALL CreateAirline('NAQ', 'Nationair');
CALL CreateAirline('NAS', 'Nasville Eagle');
CALL CreateAirline('NAT', 'National Air');
CALL CreateAirline('NB', 'Sterling Cargo');
CALL CreateAirline('NBQ', 'Sterling Airways A/S');
CALL CreateAirline('NC', 'Northern Air Cargo Inc.');
CALL CreateAirline('NCA', 'National Commuter Airlines');
CALL CreateAirline('NCE', 'Northcoast Executive');
CALL CreateAirline('ND', 'Intair');
CALL CreateAirline('NEB', 'New Born Wings Inc.');
CALL CreateAirline('NEC', 'Nor East Commuter Airlines');
CALL CreateAirline('NEQ', 'North East Cargo Airlines');
CALL CreateAirline('NER', 'Northeast Express Regional (1)');
CALL CreateAirline('NET', 'Nacnet');
CALL CreateAirline('NEV', 'Nevada Airlines');
CALL CreateAirline('NEW', 'New England Airlines Inc.');
CALL CreateAirline('NEX', 'Northeast Express Regional');
CALL CreateAirline('NFA', 'National Florida Airlines');
CALL CreateAirline('NFQ', 'North Cariboo Flying Serv.');
CALL CreateAirline('NG', 'Lauda Air Luftfahrt Ag');
CALL CreateAirline('NGL', 'Northern Eagle Airways Inc.');
CALL CreateAirline('NH', 'All Nippon Airways Co.');
CALL CreateAirline('NHA', 'Newair Flight Inc.');
CALL CreateAirline('NI', 'Lanica');
CALL CreateAirline('NI (1)', 'American International Airways Inc.');
CALL CreateAirline('NJ', 'Vanguard Airlines Inc.');
CALL CreateAirline('NJA', 'N. J. Merrimack Airlines');
CALL CreateAirline('NJE', 'NetJets Transportes Aereos, S.A.');
CALL CreateAirline('NK', 'Spirit Air Lines');
CALL CreateAirline('NKQ', 'Norcanair');
CALL CreateAirline('NLQ', 'Nolinor Aviation');
CALL CreateAirline('NN', 'Northward Airlines Ltd.');
CALL CreateAirline('NOQ', 'Novair Airlines Ab');
CALL CreateAirline('NPA', 'North Pacific Airlines Inc.');
CALL CreateAirline('NPT', 'E. J. A. Newport Inc.');
CALL CreateAirline('NQ', 'Air Japan Co');
CALL CreateAirline('NRN', 'Northern Airlines Inc.');
CALL CreateAirline('NSQ', 'North Coast Air Services');
CALL CreateAirline('NTH', 'Northaire');
CALL CreateAirline('NTQ', 'National Aviation Consult.');
CALL CreateAirline('NUM', 'Lake State Airways');
CALL CreateAirline('NUQ', 'Air Niugini');
CALL CreateAirline('NVQ', 'Novair International Airways Ltd.');
CALL CreateAirline('NVX', 'Nevis Express');
CALL CreateAirline('NW', 'Northwest Airlines Inc.');
CALL CreateAirline('NWQ', 'N. W. Territorial Airways');
CALL CreateAirline('NWS', 'Northwest Seaplanes');
CALL CreateAirline('NXQ', 'North Vancouver Air');
CALL CreateAirline('NY', 'New York Air Inc.');
CALL CreateAirline('NYH', 'New York Helicopter Corp.');
CALL CreateAirline('NZ', 'Air New Zealand');
CALL CreateAirline('OA', 'Olympic Airways');
CALL CreateAirline('OAK', 'Harbor Airlines Inc.');
CALL CreateAirline('OB', 'Oasis International Airlines S.A.');
CALL CreateAirline('OC', 'Air California Inc.');
CALL CreateAirline('OCR', 'Ocean Reef Airways Inc.');
CALL CreateAirline('OD', 'Emerald Airlines Inc.');
CALL CreateAirline('OD (1)', 'Aerocondor');
CALL CreateAirline('OE', 'Westair Airlines Inc.');
CALL CreateAirline('OF', 'Air Finland Ltd.');
CALL CreateAirline('OFF', 'Offshore Logistics');
CALL CreateAirline('OH', 'Comair Inc.');
CALL CreateAirline('OHA', 'Omaha Aviation');
CALL CreateAirline('OHZ', 'Caribbean Air Services Inc.');
CALL CreateAirline('OI', 'Prestige Airways');
CALL CreateAirline('OIZ', 'Corporate Air Inc.');
CALL CreateAirline('OJ', 'Fly Jamaica Airways Limited');
CALL CreateAirline('OK', 'Czech Airlines');
CALL CreateAirline('OMH', 'Omniflight Helicopters');
CALL CreateAirline('OMI', 'Omniflight Airways');
CALL CreateAirline('OMK', 'Omak Aviation Airlines');
CALL CreateAirline('OMN', 'Omni Pacific Airline');
CALL CreateAirline('OMQ', 'Quassar De Mexico');
CALL CreateAirline('ON', 'Air Nauru');
CALL CreateAirline('ONQ', 'Nunasi-Central Airlines Ltd.');
CALL CreateAirline('OO', 'SkyWest Airlines Inc.');
CALL CreateAirline('OOZ', 'Sun Aire Lines');
CALL CreateAirline('OP', 'Flying Boat Inc.');
CALL CreateAirline('OP (1)', 'Air Panama Internacional');
CALL CreateAirline('OPQ', 'Orion Air');
CALL CreateAirline('OR', 'TUI Airlines Nederland B.V.');
CALL CreateAirline('ORI', 'Orion Air Inc.');
CALL CreateAirline('OS', 'Austrian Airlines');
CALL CreateAirline('OTT', 'Otter Air');
CALL CreateAirline('OV', 'Aeromaritime');
CALL CreateAirline('OW', 'Executive Airlines');
CALL CreateAirline('OWQ', 'Ontario Worldair Limited');
CALL CreateAirline('OWS', 'Air Kentucky Air Lines');
CALL CreateAirline('OZ', 'Asiana Airlines Inc.');
CALL CreateAirline('OZ (1)', 'Ozark Air Lines Inc. (1)');
CALL CreateAirline('OZA', 'Ozark Air Lines Inc.');
CALL CreateAirline('P9', 'Pro Air Inc.');
CALL CreateAirline('PA', 'Florida Coastal Airlines');
CALL CreateAirline('PA (1)', 'Pan American World Airways (1)');
CALL CreateAirline('PA (2)', 'Pan American World Airways');
CALL CreateAirline('PAI', 'Permian Airways Inc.');
CALL CreateAirline('PAQ', 'Patriot Airlines Inc.');
CALL CreateAirline('PAT', 'Panorama Air Tours');
CALL CreateAirline('PBA', 'Provincetown Boston');
CALL CreateAirline('PBQ', 'Privatair');
CALL CreateAirline('PCA', 'Piasa Commuter Airlines');
CALL CreateAirline('PCL', 'Pacific Cal Air');
CALL CreateAirline('PCQ', 'Pace Airlines');
CALL CreateAirline('PCR', 'Pacair');
CALL CreateAirline('PD', 'Porter Airlines, Inc.');
CALL CreateAirline('PD (1)', 'Pem-Air Limited');
CALL CreateAirline('PDA', 'Trans Southern Airways');
CALL CreateAirline('PDQ', 'Antigua Paradise Airways');
CALL CreateAirline('PE', 'Air Europe S.P.A.');
CALL CreateAirline('PE (1)', 'People Express Airlines Inc.');
CALL CreateAirline('PEA', 'Pearson Aircraft');
CALL CreateAirline('PEQ', 'SkyLink Express Inc.');
CALL CreateAirline('PER', 'Air Pennsylvania');
CALL CreateAirline('PET', 'Petro Aviation Corp.');
CALL CreateAirline('PFA', 'Pacificair');
CALL CreateAirline('PFQ', 'Asia Pacific');
CALL CreateAirline('PH', 'Polynesian Airlines Ltd.');
CALL CreateAirline('PHL', 'Phillips Airlines');
CALL CreateAirline('PHR', 'Pinehurst Airlines Inc.');
CALL CreateAirline('PHX', 'Phoenix Airlines');
CALL CreateAirline('PI', 'Piedmont Aviation Inc.');
CALL CreateAirline('PIA', 'Pacific Island Airways');
CALL CreateAirline('PIQ', 'Pacific International Airlines');
CALL CreateAirline('PK', 'Pakistan International Airlines');
CALL CreateAirline('PKQ', 'Skyworld Airlines Inc.');
CALL CreateAirline('PL', 'Aero Peru');
CALL CreateAirline('PLA', 'Planes Inc.');
CALL CreateAirline('PLQ', 'Planet Airways');
CALL CreateAirline('PLZ', 'Polar Airways Inc.');
CALL CreateAirline('PM', 'Prescott Support Company, Inc.');
CALL CreateAirline('PMA', 'Pacific Missionary Aviation');
CALL CreateAirline('PMT', 'Pilgrim Aviation & Airlines');
CALL CreateAirline('PN', 'Pan American Airways Corp.');
CALL CreateAirline('PNM', 'Panama Aviation');
CALL CreateAirline('PNQ', 'Panagra Airways');
CALL CreateAirline('PNR', 'Pioneer Airways');
CALL CreateAirline('PNS', 'Pine State Airlines');
CALL CreateAirline('PO', 'Polar Air Cargo Airways');
CALL CreateAirline('POA', 'Potomac Air');
CALL CreateAirline('POC', 'Pocono Airlines Inc.');
CALL CreateAirline('POL', 'Polar International');
CALL CreateAirline('POM', 'Pompano Airways');
CALL CreateAirline('PON', 'Ponderosa Aviation Inc.');
CALL CreateAirline('POQ', 'Polyot Airlines');
CALL CreateAirline('PP', 'Jet Aviation Business Jets AG');
CALL CreateAirline('PPQ', 'Propair');
CALL CreateAirline('PR', 'Philippine Airlines Inc.');
CALL CreateAirline('PRA', 'Princeton Aviation Corp');
CALL CreateAirline('PRD', 'Paradise Island Airlines');
CALL CreateAirline('PRM', 'Prime Air Inc.');
CALL CreateAirline('PRN', 'Puerto Rico Intl Airlines');
CALL CreateAirline('PRO', 'Sundance Airlines');
CALL CreateAirline('PRP', 'Propheter Aviation');
CALL CreateAirline('PRQ', 'Florida West Airlines Inc.');
CALL CreateAirline('PRR', 'Pro Air Services');
CALL CreateAirline('PS', 'Ukraine International Airlines');
CALL CreateAirline('PS (1)', 'Pacific Southwest Airlines');
CALL CreateAirline('PSA', 'P.S. Air Freight Inc.');
CALL CreateAirline('PT', 'Capital Cargo International');
CALL CreateAirline('PTQ', 'Flight International');
CALL CreateAirline('PU', 'Primeras Lineas Uruguays For International');
CALL CreateAirline('PUQ', 'Aeropuma');
CALL CreateAirline('PV', 'Eastern Provincial Airways');
CALL CreateAirline('PVA', 'Precision Valley Aviation');
CALL CreateAirline('PW', 'Pacific Western Airlines');
CALL CreateAirline('PY', 'Surinam Airways Limited');
CALL CreateAirline('PZ', 'Lineas Aereas Paraguayas');
CALL CreateAirline('Q2', 'Zambia Airways Corp.');
CALL CreateAirline('Q4', 'Master Top Linhas Aereas, Ltda.');
CALL CreateAirline('Q5', '40-Mile Air');
CALL CreateAirline('Q7', 'Sobelair');
CALL CreateAirline('QB', 'Inter-Quebec (Intair)');
CALL CreateAirline('QD', 'Grand Airways Inc.');
CALL CreateAirline('QF', 'Qantas Airways Ltd.');
CALL CreateAirline('QG', 'Sky West Aviation Inc.');
CALL CreateAirline('QH', 'Air Florida Inc.');
CALL CreateAirline('QK', 'Jazz Aviation LP');
CALL CreateAirline('QN', 'Royal Air');
CALL CreateAirline('QO', 'Aeromexpress');
CALL CreateAirline('QOZ', 'Bar Harbor Airways');
CALL CreateAirline('QQ', 'Reno Air Inc.');
CALL CreateAirline('QR', 'Qatar Airways (Q.C.S.C)');
CALL CreateAirline('QS', 'Travel Service, a.s.');
CALL CreateAirline('QS (1)', 'Northeastern International Airways');
CALL CreateAirline('QT', 'Transportes Aereos Mercantiles Panamericanos S.A');
CALL CreateAirline('QTQ', 'Aer Turas Teoranta');
CALL CreateAirline('QWE', 'Qwest Commuter');
CALL CreateAirline('QX', 'Horizon Air');
CALL CreateAirline('R3', 'Air Company Yakutia');
CALL CreateAirline('RAL', 'Royal-Air Ltd.');
CALL CreateAirline('RAN', 'Pan Am Express');
CALL CreateAirline('RAQ', 'Arista International Airlines Inc.');
CALL CreateAirline('RAY', 'Royale Airlines Inc.');
CALL CreateAirline('RB', 'Syrian Arab Airlines');
CALL CreateAirline('RC', 'Republic Airlines Inc.');
CALL CreateAirline('RCA', 'Mid-South Aviation Inc. (1)');
CALL CreateAirline('RD', 'Ryan International Airlines');
CALL CreateAirline('RD (1)', 'Airlift International Inc.');
CALL CreateAirline('RDR', 'Rader Aviation');
CALL CreateAirline('RDW', 'Redwing Airways');
CALL CreateAirline('REA', 'Realwest Airlines');
CALL CreateAirline('RED', 'Aerosun International Airlines Inc.');
CALL CreateAirline('REQ', 'Renown Aviation');
CALL CreateAirline('RES', 'Resort Airlines Inc.');
CALL CreateAirline('RG', 'Varig S. A.');
CALL CreateAirline('RGQ', 'Regency Air');
CALL CreateAirline('RHA', 'Royal Hawaiian Airways Inc.');
CALL CreateAirline('RIA', 'Trump Air');
CALL CreateAirline('RIC', 'Richardson Aviation');
CALL CreateAirline('RID', 'Indiana Airways Inc. (Reid');
CALL CreateAirline('RIO', 'Rio Airways Inc.');
CALL CreateAirline('RIQ', 'Rich International Airways');
CALL CreateAirline('RIV', 'Riverside Air Service');
CALL CreateAirline('RJ', 'Alia-(The) Royal Jordanian');
CALL CreateAirline('RJS', 'Michigan Airways Inc.');
CALL CreateAirline('RK', 'Air Afrique');
CALL CreateAirline('RL', 'UltrAir');
CALL CreateAirline('RL (1)', 'Aerolineas Nicaraguenses');
CALL CreateAirline('RLQ', 'Reliant Airlines');
CALL CreateAirline('RMH', 'Rocky Mountain Helicopters');
CALL CreateAirline('RMV', 'Ram Aviation');
CALL CreateAirline('RNQ', 'Mytravel Airways');
CALL CreateAirline('RO', 'Tarom Romanian Air Transpor');
CALL CreateAirline('ROA', 'Royal West Airways Inc.');
CALL CreateAirline('ROE', 'Roederer Aviation Inc.');
CALL CreateAirline('ROQ', 'Aero Uruguay (1)');
CALL CreateAirline('ROS', 'Great Western Airlines Inc.');
CALL CreateAirline('ROY', 'Royal American Airways Inc.');
CALL CreateAirline('RP', 'Chautauqua Airlines Inc.');
CALL CreateAirline('RRT', 'Air Freight Express');
CALL CreateAirline('RS', 'Sky Regional Airlines Inc.');
CALL CreateAirline('RSC', 'Resort Commuter');
CALL CreateAirline('RSQ', 'Aerotransportes Entre Rios');
CALL CreateAirline('RSV', 'Air-Serve');
CALL CreateAirline('RTQ', 'Aerotour Dominicano Cxa');
CALL CreateAirline('RU', 'AirBridgeCargo Airlines Limited');
CALL CreateAirline('RV', 'Air Canada rouge LP');
CALL CreateAirline('RV (1)', 'Reeve Aleutian Airways Inc.');
CALL CreateAirline('RVA', 'Reeves Air');
CALL CreateAirline('RVQ', 'Reeve Air Alaska, LLC');
CALL CreateAirline('RWG', 'Air Rovers Inc.');
CALL CreateAirline('RY', 'Redcoat Air Cargo Limited');
CALL CreateAirline('RZZ', 'Aeromech Inc.');
CALL CreateAirline('S3', 'Santa Barbara Airlines, C.A');
CALL CreateAirline('S4', 'Sata Internacional');
CALL CreateAirline('S5', 'Shuttle America Corp.');
CALL CreateAirline('S6', 'Star Air A/S');
CALL CreateAirline('S6 (1)', 'Mountain Bird/Salmon Air');
CALL CreateAirline('SA', 'South African Airways');
CALL CreateAirline('SAC', 'Sundorph Aeronautical Corp.');
CALL CreateAirline('SAH', 'Sea Air Shuttle');
CALL CreateAirline('SAI', 'Seair Alaska Airlines Inc.');
CALL CreateAirline('SAJ', 'Sajen Air Inc.');
CALL CreateAirline('SAL', 'Sallee''s Aviation');
CALL CreateAirline('SAM', 'Samoan Airlines Inc.');
CALL CreateAirline('SAQ', 'Southern Air Transport Inc.');
CALL CreateAirline('SAS', 'Air Cortez International');
CALL CreateAirline('SAX', 'Air Americana');
CALL CreateAirline('SBA', 'Saber Aviation Inc.');
CALL CreateAirline('SBN', 'Suburban Airlines');
CALL CreateAirline('SBQ', 'Skyjet S.A.');
CALL CreateAirline('SCN', 'Scott Aviation');
CALL CreateAirline('SCO', 'Seaco Airlines Inc.');
CALL CreateAirline('SCT', 'Skyline Airlines');
CALL CreateAirline('SCY', 'South Coast Airways');
CALL CreateAirline('SDQ', 'St. Lucia Airways Limited');
CALL CreateAirline('SE', 'XL Airways France');
CALL CreateAirline('SE (1)', 'Das Air Cargo');
CALL CreateAirline('SEB', 'Seaborne Aviation');
CALL CreateAirline('SEG', 'Seagull Air Service');
CALL CreateAirline('SEM', 'Semo Aviation Inc.');
CALL CreateAirline('SEP', 'Southern Express Airways');
CALL CreateAirline('SEQ', 'Sky Service F.B.O.');
CALL CreateAirline('SER', 'Service Aviation Inc.');
CALL CreateAirline('SFI', 'Stahmannfarms Inc.');
CALL CreateAirline('SFO', 'Sfo Helicopter Airlines Inc.');
CALL CreateAirline('SFQ', 'Pacific International Airlines Inc.');
CALL CreateAirline('SFQ (1)', 'Southern Frontier Air Trans');
CALL CreateAirline('SFS', 'Sierra Flite Service Inc.');
CALL CreateAirline('SG', 'Jetsgo');
CALL CreateAirline('SH', 'Servicio Aereo De Honduras');
CALL CreateAirline('SHS', 'Shasta Air Inc.');
CALL CreateAirline('SHV', 'Shavano Air Inc.');
CALL CreateAirline('SI', 'Sierra Pacific Airlines');
CALL CreateAirline('SI (1)', 'Jet America Airlines Inc.');
CALL CreateAirline('SIA', 'Silver State Airlines');
CALL CreateAirline('SIQ', 'Premiair');
CALL CreateAirline('SIQ (1)', 'Scanair');
CALL CreateAirline('SJA', 'San Juan Airlines Inc.');
CALL CreateAirline('SJQ', 'Skycharter (Malton) Ltd.');
CALL CreateAirline('SK', 'Scandinavian Airlines Sys.');
CALL CreateAirline('SKI', 'Sunbird Inc.');
CALL CreateAirline('SKJ', 'Sky-Jet');
CALL CreateAirline('SKL', 'Bas Airlines');
CALL CreateAirline('SKM', 'Scheduled Skyways');
CALL CreateAirline('SKS', 'Silver Kris Services Ltd.');
CALL CreateAirline('SKT', 'Skytrain');
CALL CreateAirline('SLO', 'Slocum Air Inc.');
CALL CreateAirline('SLQ', 'Sky King Inc.');
CALL CreateAirline('SLR', 'Salair');
CALL CreateAirline('SLZ', 'Southeast Airlines Inc.');
CALL CreateAirline('SM', 'Sunworld International Airlines');
CALL CreateAirline('SMC', 'Stopher Mechanical Inc.');
CALL CreateAirline('SMO', 'Samoa Aviation Inc.');
CALL CreateAirline('SMQ', 'Serv. Aerolineas Mexicanas');
CALL CreateAirline('SN', 'Brussels Airlines N.V.');
CALL CreateAirline('SN (1)', 'Sabena Belgian World Air.');
CALL CreateAirline('SNA', 'Aviation Associates');
CALL CreateAirline('SNB', 'Ccair');
CALL CreateAirline('SNC', 'Gelco Courier Services Inc.');
CALL CreateAirline('SNE', 'Shawnee Airlines');
CALL CreateAirline('SNK', 'Spernak Airways Inc.');
CALL CreateAirline('SNV', 'Sierra Nevada Airways');
CALL CreateAirline('SO', 'Swiss World Airways');
CALL CreateAirline('SOA', 'Mall Airways Inc.');
CALL CreateAirline('SOE', 'Sky One Express');
CALL CreateAirline('SOL', 'Soonair Lines Inc.');
CALL CreateAirline('SOP', 'South Pacific Island Airway');
CALL CreateAirline('SPF', 'Springfield Air Service');
CALL CreateAirline('SPG', 'Springdale Air');
CALL CreateAirline('SPH', 'Spirit Helicopter');
CALL CreateAirline('SPQ', 'Sun Pacific International');
CALL CreateAirline('SPR', 'Sportsman Flying Service');
CALL CreateAirline('SQ', 'Singapore Airlines Ltd.');
CALL CreateAirline('SR', 'Swissair Transport Co. Ltd.');
CALL CreateAirline('SRA', 'Star Aviation');
CALL CreateAirline('SRL', 'Sterling Air Service');
CALL CreateAirline('SS', 'Corsair International');
CALL CreateAirline('SSA', 'S. S. Airways Inc.');
CALL CreateAirline('SSP', 'Southern Seaplane');
CALL CreateAirline('SSQ', 'Superior Airways Limited');
CALL CreateAirline('SSS', 'Sierra Express Inc.');
CALL CreateAirline('SST', 'Seaplane Shuttle Transport');
CALL CreateAirline('ST', 'Belize Airways Limited');
CALL CreateAirline('STA', 'State Airlines Inc.');
CALL CreateAirline('STF', 'Trans East International');
CALL CreateAirline('STG', 'Sedalia Marshall Boonvl Stg');
CALL CreateAirline('STQ', 'Skycraft Air Transport Inc.');
CALL CreateAirline('STR', 'Star Aviation Corporation');
CALL CreateAirline('STW', 'Stateswest Airlines');
CALL CreateAirline('STZ', 'Air America Inc.');
CALL CreateAirline('SU', 'Aeroflot Russian Airlines');
CALL CreateAirline('SUA', 'Sunshine Airlines');
CALL CreateAirline('SUI', 'Sun International Airways');
CALL CreateAirline('SUT', 'Sunbelt');
CALL CreateAirline('SUX', 'Sunair Express LLC');
CALL CreateAirline('SV', 'Saudi Arabian Airlines Corp');
CALL CreateAirline('SVL', 'Sun Valley Airlines');
CALL CreateAirline('SVW', 'Global Jet Luxembourg, Sa');
CALL CreateAirline('SWA', 'Sunwest Airlines');
CALL CreateAirline('SWT', 'Swift Aire Lines Inc.');
CALL CreateAirline('SX', 'Skybus Airlines, Inc.');
CALL CreateAirline('SX (1)', 'Aeroejecutivo S.A.');
CALL CreateAirline('SXP', 'Sierra Expressway');
CALL CreateAirline('SY', 'Sun Country Airlines d/b/a MN Airlines');
CALL CreateAirline('SYB', 'Skybus Express Airlines');
CALL CreateAirline('SYM', 'Skymaster');
CALL CreateAirline('SZQ', 'Aerolineas El Salvador S A');
CALL CreateAirline('T3', 'Tristar Airlines Inc.');
CALL CreateAirline('T9', 'TransMeridian Airlines');
CALL CreateAirline('TA', 'Taca International Airlines');
CALL CreateAirline('TAC', 'Air Colorado');
CALL CreateAirline('TAF', 'Tri Air Freight');
CALL CreateAirline('TAL', 'Tejas Airlines Inc.');
CALL CreateAirline('TAQ', 'Taquan Air Service');
CALL CreateAirline('TAS', 'Yosemite Airlines Inc.');
CALL CreateAirline('TAT', 'Talarik Creek Air Taxi');
CALL CreateAirline('TB', 'TUI Airlines Belgium N.V. d/b/a Jetairfly');
CALL CreateAirline('TB (1)', 'USAir Shuttle');
CALL CreateAirline('TBQ', 'Triair Bermuda Flt Operations');
CALL CreateAirline('TCA', 'Trans Catalina Airlines');
CALL CreateAirline('TCE', 'Oceanair Line');
CALL CreateAirline('TCI', 'Trans California Airlines');
CALL CreateAirline('TCL', 'Trans-Central Airlines Inc.');
CALL CreateAirline('TCO', 'Trans-Colorado Airlines');
CALL CreateAirline('TCQ', 'Express.Net Airlines');
CALL CreateAirline('TDQ', 'Venexcargo');
CALL CreateAirline('TDQ (1)', 'Transcarga');
CALL CreateAirline('TEN', 'Tennessee Airways Inc.');
CALL CreateAirline('TER', 'Terre Haute Air Commuter');
CALL CreateAirline('TFQ', 'Trans International Airlines Inc.');
CALL CreateAirline('TFZ', 'Tri-State Airlines Inc.');
CALL CreateAirline('TG', 'Thai Airways International Ltd.');
CALL CreateAirline('TGO', 'Trans Air Cargo Inc.');
CALL CreateAirline('TGQ', 'Tranps Aereos Guatemaltecos');
CALL CreateAirline('TH', 'Transmile Air Service');
CALL CreateAirline('THA', 'Tropical Helicopter Airways');
CALL CreateAirline('THO', 'Thorson Aviation');
CALL CreateAirline('THQ', 'T-Bird Air Inc.');
CALL CreateAirline('TIA', 'Trans Air Inc.');
CALL CreateAirline('TIE', 'Trans International Express');
CALL CreateAirline('TIQ', 'Tyrolean Jet Service');
CALL CreateAirline('TIS', 'Skyfreight');
CALL CreateAirline('TJ', 'Jet Charter Service Inc.');
CALL CreateAirline('TK', 'Turk Hava Yollari A.O.');
CALL CreateAirline('TKQ', 'Trans-Air-Link Corporation');
CALL CreateAirline('TLQ', 'Trans-Mediterranean Airways');
CALL CreateAirline('TMA', 'Trans Mo Airlines');
CALL CreateAirline('TN', 'Air Tahiti Nui');
CALL CreateAirline('TNQ', 'Emery Worldwide Airlines');
CALL CreateAirline('TNS', 'Transtate Aviation');
CALL CreateAirline('TP', 'Tap-Portuguese Airlines');
CALL CreateAirline('TPQ', 'Aerial Transit Company');
CALL CreateAirline('TQQ', 'Taca Peru');
CALL CreateAirline('TR', 'Transbrasil S.A.');
CALL CreateAirline('TRA', 'Aeromexico Travel');
CALL CreateAirline('TRI', 'Great Plains Airlines Inc.');
CALL CreateAirline('TRO', 'Air Molakai');
CALL CreateAirline('TRP', 'Trans Pennsylvania Airlines');
CALL CreateAirline('TRQ', 'Blue Scandinavia Ab');
CALL CreateAirline('TRR', 'Territorial Airlines');
CALL CreateAirline('TS', 'Air Transat');
CALL CreateAirline('TSF', 'American Central Airlines');
CALL CreateAirline('TSI', 'Trans Sierra Airlines Inc.');
CALL CreateAirline('TSQ', 'TPI International Airways');
CALL CreateAirline('TTM', 'The Time Machine');
CALL CreateAirline('TUL', 'Tulsair Beechcraft Inc.');
CALL CreateAirline('TUR', 'Turner Aire');
CALL CreateAirline('TV', 'Haiti Trans Air');
CALL CreateAirline('TV (1)', 'Transamerica Airlines Inc.');
CALL CreateAirline('TVL', 'Travelair');
CALL CreateAirline('TW', 'Trans World Airways LLC');
CALL CreateAirline('TWA', 'Trans Western Airlines Utah');
CALL CreateAirline('TWE', 'Trans World Express');
CALL CreateAirline('TX', 'Soc.Nouvelle Air Guadeloupe');
CALL CreateAirline('TX (1)', 'Transportes Aereos Nacional');
CALL CreateAirline('TXA', 'Texas National Airlines');
CALL CreateAirline('TXE', 'Trans Air (Hawaii)');
CALL CreateAirline('TXQ', 'British Caribbean Airways');
CALL CreateAirline('TXY', 'Texas Airways');
CALL CreateAirline('TYE', 'Temsco Airlines');
CALL CreateAirline('TZ', 'ATA Airlines d/b/a ATA');
CALL CreateAirline('TZQ', 'First Choice Airways');
CALL CreateAirline('U2', 'UFS Inc.');
CALL CreateAirline('U5', 'USA 3000 Airlines');
CALL CreateAirline('U7', 'USA Jet Airlines Inc.');
CALL CreateAirline('UA', 'United Air Lines Inc.');
CALL CreateAirline('UAI', 'Universal Airways Inc.');
CALL CreateAirline('UC', 'Ladeco');
CALL CreateAirline('UD', 'Fast Air Carrier Ltd.');
CALL CreateAirline('UH', 'US Helicopter Corporation');
CALL CreateAirline('UMQ', 'Air Manila Inc.');
CALL CreateAirline('UN', 'Transaero Airlines');
CALL CreateAirline('UNQ', 'Overseas National Airways');
CALL CreateAirline('UP', 'Bahamasair Holding Limited');
CALL CreateAirline('UR', 'Empire Airlines Inc. (1)');
CALL CreateAirline('URQ', 'Aero Uruguay');
CALL CreateAirline('US', 'US Airways Inc.');
CALL CreateAirline('USA', 'Air U.S.');
CALL CreateAirline('UT', 'Union De Transports Aeriens');
CALL CreateAirline('UTQ', 'Universal Airlines Inc.');
CALL CreateAirline('UX', 'Air Europa');
CALL CreateAirline('UX (1)', 'Air Illinois Inc.');
CALL CreateAirline('UYQ', 'Aerolineas Uruguayas S.A.');
CALL CreateAirline('V4', 'Vensecar International');
CALL CreateAirline('V5', 'J.D.Valenciana De Aviation');
CALL CreateAirline('V8', 'Iliamna Air Taxi');
CALL CreateAirline('V9', 'Eagle Airlines');
CALL CreateAirline('VA', 'Virgin Blue International Airlines t/a V Australia');
CALL CreateAirline('VA (1)', 'Venezuelan International Airways');
CALL CreateAirline('VAG', 'Vagabond Aviation Inc.');
CALL CreateAirline('VAQ', 'Vacationair');
CALL CreateAirline('VAS', 'Valley Air Services');
CALL CreateAirline('VB', 'Aeroenlaces Nacionales, S.A. de C.V. d/b/a VivaAerobus');
CALL CreateAirline('VB (1)', 'Pacific Express');
CALL CreateAirline('VC', 'Servicios Avensa');
CALL CreateAirline('VCQ', 'Victory Air Transport Inc.');
CALL CreateAirline('VE', 'Aerovias Venezolanas-Avensa');
CALL CreateAirline('VER', 'Britt Airlines Inc.');
CALL CreateAirline('VEZ', 'Valdez Airlines');
CALL CreateAirline('VH', 'Aeropostal Alas De Venezuel');
CALL CreateAirline('VI', 'Vieques Air Link Inc.');
CALL CreateAirline('VIG', 'Viking Express');
CALL CreateAirline('VIN', 'Vale International Airlines');
CALL CreateAirline('VIQ', 'Volga-Dnepr Airlines');
CALL CreateAirline('VIQ (1)', 'Viscount Air Service Inc.');
CALL CreateAirline('VIS', 'Virgin Islands Seaplane');
CALL CreateAirline('VJT', 'VistaJet Limited');
CALL CreateAirline('VK', 'Air Tungaru Corporation');
CALL CreateAirline('VL', 'Mid-South Aviation Inc.');
CALL CreateAirline('VLA', 'Village Aviation');
CALL CreateAirline('VLY', 'Valley Airlines');
CALL CreateAirline('VOQ', 'Avalon Aviation Ltd.');
CALL CreateAirline('VP', 'Viacao Aerea Sao Paulo');
CALL CreateAirline('VQ', 'Vintage Props & Jets Inc.');
CALL CreateAirline('VR', 'Transportes Aereos De Cabo');
CALL CreateAirline('VS', 'Virgin Atlantic Airways');
CALL CreateAirline('VSA', 'VistaJet Luftfahrtunternehmen GmbH');
CALL CreateAirline('VV', 'Aerosvit Ukranian Airlines');
CALL CreateAirline('VV (1)', 'Challenge Air Transport Inc.');
CALL CreateAirline('VV (2)', 'Challenge Air International Inc.');
CALL CreateAirline('VW', 'Transportes Aeromar S.A de C.V');
CALL CreateAirline('VX', 'Virgin America');
CALL CreateAirline('VX (1)', 'Aces Airlines');
CALL CreateAirline('VY', 'Highland Express Airways');
CALL CreateAirline('W3', 'Arik Air International');
CALL CreateAirline('W4', 'Mn Aviation, Inc.');
CALL CreateAirline('W7', 'Western Pacific Airlines');
CALL CreateAirline('W8', 'Cargojet Airways Ltd.');
CALL CreateAirline('W9', 'Eastwind Airlines Inc.');
CALL CreateAirline('WA', 'Worldwide Airlines Services');
CALL CreateAirline('WA (1)', 'Western Air Lines Inc.');
CALL CreateAirline('WAC', 'Air East Airlines');
CALL CreateAirline('WAI', 'Wise Airlines Inc.');
CALL CreateAirline('WAP', 'Arrow Panama');
CALL CreateAirline('WAQ', 'Air Charter Systems (Acs)');
CALL CreateAirline('WAR', 'Waring Air');
CALL CreateAirline('WAW', 'Westward Airways Inc.');
CALL CreateAirline('WC', 'Wien Air Alaska Inc.');
CALL CreateAirline('WCA', 'Walker''s International');
CALL CreateAirline('WCI', 'Mountainwest Airlines');
CALL CreateAirline('WD', 'Halisa Air');
CALL CreateAirline('WDQ', 'Wardair Canada Inc.');
CALL CreateAirline('WE', 'Centurion Cargo Inc.');
CALL CreateAirline('WEB', 'Southeast Alaska Airlines');
CALL CreateAirline('WEQ', 'Aero-Services-Corporate');
CALL CreateAirline('WES', 'Western Star Airlines Inc.');
CALL CreateAirline('WET', 'Western Charter Inc.');
CALL CreateAirline('WFS', 'Wheeler Airlines');
CALL CreateAirline('WFT', 'Westflight Aviation');
CALL CreateAirline('WG', 'Sunwing Airlines Inc.');
CALL CreateAirline('WGL', 'Wrangell Air Service');
CALL CreateAirline('WGQ', 'Gateway Aviation Limited');
CALL CreateAirline('WI', 'Tradewinds Airlines');
CALL CreateAirline('WIA', 'Wisc Air');
CALL CreateAirline('WIL', 'Will''s Air');
CALL CreateAirline('WIR', 'Williams Air Inc.');
CALL CreateAirline('WL', 'World Air Network');
CALL CreateAirline('WLH', 'Welch Aviation');
CALL CreateAirline('WLQ', 'Worldwide Airlines Inc.');
CALL CreateAirline('WM', 'Windward Islands Airways');
CALL CreateAirline('WN', 'Southwest Airlines Co.');
CALL CreateAirline('WNG', 'Wings Airways');
CALL CreateAirline('WNQ', 'Winair Inc.');
CALL CreateAirline('WO', 'World Airways Inc.');
CALL CreateAirline('WP', 'Island Air Hawaii');
CALL CreateAirline('WRA', 'Wra Inc.');
CALL CreateAirline('WRD', 'Ward Air');
CALL CreateAirline('WRT', 'Wright Airlines Inc.');
CALL CreateAirline('WS', 'Westjet');
CALL CreateAirline('WS (1)', 'Suncoast Airlines Inc.');
CALL CreateAirline('WSK', 'AAR Western Skyways');
CALL CreateAirline('WST', 'West Isle Air');
CALL CreateAirline('WSU', 'Mission Air');
CALL CreateAirline('WT', 'Nigeria Airways Ltd.');
CALL CreateAirline('WTA', 'Westates Airlines');
CALL CreateAirline('WV', 'Air Greco, Inc., d/b/a Wings Air');
CALL CreateAirline('WV (1)', 'Air South Inc. (1)');
CALL CreateAirline('WW', 'WOW Air ehf');
CALL CreateAirline('WWI', 'Wings West Airlines');
CALL CreateAirline('WWQ', 'Worldways Canada Ltd.');
CALL CreateAirline('X4', 'Air Excursions LLC');
CALL CreateAirline('X9', 'Omni Air Express');
CALL CreateAirline('XAA', 'Aero Union Corp');
CALL CreateAirline('XAB', 'Air Polynesia d/b/a DHL Cargo');
CALL CreateAirline('XAC', 'Air Express International Airlines');
CALL CreateAirline('XAE', 'Amerford Airways Inc.');
CALL CreateAirline('XAF', 'Astro-Wing Airlines Inc.');
CALL CreateAirline('XAG', 'Ball Brothers Inc.');
CALL CreateAirline('XAH', 'Hawaii Pacific Air');
CALL CreateAirline('XAI', 'Burlington Northern Inc.');
CALL CreateAirline('XAJ', 'Central American International');
CALL CreateAirline('XAK', 'Century Airlines Inc.');
CALL CreateAirline('XAM', 'Cohlmia Aviation');
CALL CreateAirline('XAO', 'Dallas Flight Center');
CALL CreateAirline('XAQ', 'Cam Air International Inc.');
CALL CreateAirline('XAR', 'Jet Way Inc.');
CALL CreateAirline('XAS', 'Klondike Air Inc.');
CALL CreateAirline('XAT', 'Michigan Peninsula Airways');
CALL CreateAirline('XAU', 'Flight Line Inc.');
CALL CreateAirline('XAY', 'Pat Air');
CALL CreateAirline('XAZ', 'Purolator Sky Courier Inc.');
CALL CreateAirline('XBC', 'Jet East Inc.');
CALL CreateAirline('XBF', 'WTC Airlines');
CALL CreateAirline('XBH', 'Profit Airlines Inc.');
CALL CreateAirline('XBI', 'CF Air Freight');
CALL CreateAirline('XBJ', 'International Air Service');
CALL CreateAirline('XBM', 'Phh Air Inc.');
CALL CreateAirline('XBP', 'Circle Airfreight Corp.');
CALL CreateAirline('XBQ', 'Aeronaves De Puerto Rico');
CALL CreateAirline('XBR', 'Allstates Air Cargo Inc.');
CALL CreateAirline('XBT', 'Pacific Alaska Airlines Inc.');
CALL CreateAirline('XBV', 'Nal Inc.');
CALL CreateAirline('XBX', 'Icb International Airlines');
CALL CreateAirline('XBZ', 'Air Natl Aircraft Sal & Ser');
CALL CreateAirline('XC', 'Air Caribbean (1)');
CALL CreateAirline('XCA', 'Hawkins And Powers Aviation');
CALL CreateAirline('XDA', 'Pacific Air Express Inc.');
CALL CreateAirline('XDC', 'Hemisphere Air Charter');
CALL CreateAirline('XDD', 'International Parcel Express Inc.');
CALL CreateAirline('XDE', 'Air Train Inc.');
CALL CreateAirline('XDF', 'Salair Inc.');
CALL CreateAirline('XDH', 'Kitty Hawk Air Cargo');
CALL CreateAirline('XE', 'ExpressJet Airlines Inc. (1)');
CALL CreateAirline('XF', 'Vladivostok Air');
CALL CreateAirline('XJ', 'Mesaba Airlines');
CALL CreateAirline('XK', 'Aerotal');
CALL CreateAirline('XL', 'Lan Ecuador');
CALL CreateAirline('XP', 'Casino Express');
CALL CreateAirline('XPA', 'Express Air d/b/a Sunrise');
CALL CreateAirline('XPE', 'Amira Air GmbH');
CALL CreateAirline('XPQ', 'International Cargo Xpress');
CALL CreateAirline('XV', 'Presidential Airways Inc.');
CALL CreateAirline('XY', 'Munz Northern Airlines Inc.');
CALL CreateAirline('XYZ', 'Airpac Inc.');
CALL CreateAirline('Y2', 'Globespan Airways Limited d/b/a Flyglobespan');
CALL CreateAirline('Y4', 'Concesionaria Vuela Compania De Aviacion SA de CV (Volaris)');
CALL CreateAirline('Y7', 'Flyjet Limited d/b/a Silverjet');
CALL CreateAirline('Y8', 'Yangtze River Express Airlines Company');
CALL CreateAirline('YB', 'Trans Continental Airlines');
CALL CreateAirline('YBQ', 'Yellow Bird Air');
CALL CreateAirline('YM', 'Royal West Airlines');
CALL CreateAirline('YR', 'Grand Canyon Airlines, Inc. d/b/a Grand Canyon Airlines d/b/a Scenic Airlines');
CALL CreateAirline('YV', 'Mesa Airlines Inc.');
CALL CreateAirline('YX', 'Republic Airlines');
CALL CreateAirline('YX (1)', 'Midwest Airline, Inc.');
CALL CreateAirline('Z3', 'PM Air, LLC');
CALL CreateAirline('Z3 (1)', 'Promech');
CALL CreateAirline('ZA', 'Accessair Holdings');
CALL CreateAirline('ZAQ', 'Zas Airline Of Egypt');
CALL CreateAirline('ZB', 'Monarch Airlines');
CALL CreateAirline('ZE', 'Lineas Aereas Azteca');
CALL CreateAirline('ZFZ', 'Mcphillips Flying Service');
CALL CreateAirline('ZIA', 'Air New Mexico');
CALL CreateAirline('ZK', 'Great Lakes Airlines');
CALL CreateAirline('ZKQ', 'Zantop International');
CALL CreateAirline('ZL', 'Affretair');
CALL CreateAirline('ZMZ', 'Winnipesaukee Aviation Inc.');
CALL CreateAirline('ZN', 'Key Airlines Inc.');
CALL CreateAirline('ZO', 'Florida Express Inc.');
CALL CreateAirline('ZP', 'Air St. Thomas');
CALL CreateAirline('ZS', 'Hispaniola Airways');
CALL CreateAirline('ZUQ', 'Zuliana De Aviacion');
CALL CreateAirline('ZV', 'Air Midwest Inc.');
CALL CreateAirline('ZW', 'Air Wisconsin Airlines Corp');
CALL CreateAirline('ZX', 'Air Georgian');
CALL CreateAirline('ZX (1)', 'Airbc Ltd.');
CALL CreateAirline('ZY', 'Atlantic Gulf Airlines');
CALL CreateAirline('ZYZ', 'Skyway Aviation Inc.');
