-- MySQL Script generated by MySQL Workbench
-- Wed Jul  7 17:58:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GlobetrotterV1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GlobetrotterV1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GlobetrotterV1` DEFAULT CHARACTER SET utf8 ;
USE `GlobetrotterV1` ;

-- -----------------------------------------------------
-- Table `GlobetrotterV1`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GlobetrotterV1`.`file` (
  `content_id` INT NOT NULL,
  `filepath` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`content_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GlobetrotterV1`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GlobetrotterV1`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(15) NOT NULL,
  `password_hashed` VARCHAR(128) NOT NULL,
  `address` VARCHAR(90) NULL DEFAULT NULL,
  `phone_country_code` VARCHAR(2) NULL DEFAULT NULL,
  `phone_number` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_registered_user_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `password_hashed_UNIQUE` (`password_hashed` ASC) VISIBLE)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Create user 'globetrotter' with password 'globetrotter'
-- -----------------------------------------------------
INSERT INTO GlobetrotterV1.users (username, password_hashed, email) values('globetrotter', '$2b$10$4TF8lwcJBfFW.tgew44ubOfQQCR7oZNxAg.UJXI.zwgdW5xMZd6US', 'support@globetrotter.com');


-- -----------------------------------------------------
-- Table `GlobetrotterV1`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GlobetrotterV1`.`album` (
  `album_id` INT NOT NULL AUTO_INCREMENT,
  `registered_user` INT NOT NULL,
  `content` INT NOT NULL,
  `date_created` DATETIME NOT NULL,
  `title` VARCHAR(30) NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`album_id`),
  UNIQUE INDEX `id_photo_album_UNIQUE` (`album_id` ASC) VISIBLE,
  INDEX `FK_ALBUM__idx` (`content` ASC) VISIBLE,
  INDEX `FK_ALBUM_USER_idx` (`registered_user` ASC) VISIBLE,
  CONSTRAINT `FK_ALBUM_CONTENT`
    FOREIGN KEY (`content`)
    REFERENCES `GlobetrotterV1`.`file` (`content_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ALBUM_USER`
    FOREIGN KEY (`registered_user`)
    REFERENCES `GlobetrotterV1`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GlobetrotterV1`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GlobetrotterV1`.`photo` (
  `photo_id` INT NOT NULL AUTO_INCREMENT,
  `photo_album` INT NOT NULL,
  `registered_user` INT NOT NULL,
  `content` INT NOT NULL,
  `date_created` DATETIME NOT NULL,
  `title` VARCHAR(30) NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`photo_id`),
  UNIQUE INDEX `photo_id_UNIQUE` (`photo_id` ASC) VISIBLE,
  INDEX `FK_PHOTO_USER_idx` (`registered_user` ASC) VISIBLE,
  INDEX `FK_PHOTO_CONTENT_idx` (`content` ASC) VISIBLE,
  CONSTRAINT `FK_PHOTO_USER`
    FOREIGN KEY (`registered_user`)
    REFERENCES `GlobetrotterV1`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PHOTO_CONTENT`
    FOREIGN KEY (`content`)
    REFERENCES `GlobetrotterV1`.`file` (`content_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GlobetrotterV1`.`photo_album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GlobetrotterV1`.`photo_album` (
  `photo_album_id` INT NOT NULL AUTO_INCREMENT,
  `album` INT NOT NULL,
  `photo` INT NOT NULL,
  PRIMARY KEY (`photo_album_id`),
  UNIQUE INDEX `photo_album_id_UNIQUE` (`photo_album_id` ASC) VISIBLE,
  INDEX `FK_PHOTOALBUM_ALBUM_idx` (`album` ASC) VISIBLE,
  INDEX `FK_PHOTOALBUM_PHOTO_idx` (`photo` ASC) VISIBLE,
  CONSTRAINT `FK_PHOTOALBUM_ALBUM`
    FOREIGN KEY (`album`)
    REFERENCES `GlobetrotterV1`.`album` (`album_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PHOTOALBUM_PHOTO`
    FOREIGN KEY (`photo`)
    REFERENCES `GlobetrotterV1`.`photo` (`photo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GlobetrotterV1`.`view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GlobetrotterV1`.`view` (
  `registered_user` INT NOT NULL,
  `content` INT NOT NULL,
  INDEX `FK_VIEW_USER_idx` (`registered_user` ASC) VISIBLE,
  INDEX `FK_VIEW_CONTENT_idx` (`content` ASC) VISIBLE,
  CONSTRAINT `FK_VIEW_USER`
    FOREIGN KEY (`registered_user`)
    REFERENCES `GlobetrotterV1`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_VIEW_CONTENT`
    FOREIGN KEY (`content`)
    REFERENCES `GlobetrotterV1`.`file` (`content_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'team2' IDENTIFIED WITH mysql_native_password BY 'YE2n4qh4wV';

GRANT ALL ON `GlobetrotterV1`.* TO 'team2';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
