CALL usp_create_airline('02Q', 'Titan Airways');
CALL usp_create_airline('04Q', 'Tradewind Aviation');
CALL usp_create_airline('05Q', 'Comlux Aviation, AG');
CALL usp_create_airline('06Q', 'Master Top Linhas Aereas Ltd.');
CALL usp_create_airline('07Q', 'Flair Airlines Ltd.');
CALL usp_create_airline('09Q', 'Swift Air, LLC');
CALL usp_create_airline('0BQ', 'DCA');
CALL usp_create_airline('0CQ', 'ACM AIR CHARTER GmbH');
CALL usp_create_airline('0GQ', 'Inter Island Airways, d/b/a Inter Island Air');
CALL usp_create_airline('0HQ', 'Polar Airlines de Mexico d/b/a Nova Air');
CALL usp_create_airline('0J', 'JetClub AG');
CALL usp_create_airline('0JQ', 'Vision Airlines');
CALL usp_create_airline('0LQ', 'Metropix UK, LLP.');
CALL usp_create_airline('0MQ', 'Multi-Aero, Inc. d/b/a Air Choice One');
CALL usp_create_airline('0OQ', 'Open Skies');
CALL usp_create_airline('0Q', 'Flying Service N.V.');
CALL usp_create_airline('0QQ', 'TAG Aviation (UK) Ltd.');
CALL usp_create_airline('0RQ', 'TAG Aviation Espana S.L.');
CALL usp_create_airline('0TQ', 'Corporatejets, XXI');
CALL usp_create_airline('0UQ', 'Comlux Malta, Ltd.');
CALL usp_create_airline('0VQ', 'Ocean Sky (UK) Limited');
CALL usp_create_airline('0WQ', 'Avjet Corporation');
CALL usp_create_airline('0YQ', 'Comlux Malta Ltd.');
CALL usp_create_airline('10Q', 'Swiss Air Ambulance');
CALL usp_create_airline('12Q', 'Unijet');
CALL usp_create_airline('13Q', 'Chartright Air Inc.');
CALL usp_create_airline('14Q', 'London Air Services Limited');
CALL usp_create_airline('15Q', 'Air Alsie A/S');
CALL usp_create_airline('16', 'PSA Airlines Inc.');
CALL usp_create_airline('17', 'Piedmont Airlines');
CALL usp_create_airline('17Q', 'Albinati Aeronautics SA');
CALL usp_create_airline('1AQ', 'Charter Air Transport, Inc.');
CALL usp_create_airline('1BQ', 'Dynamic Airways, LLC');
CALL usp_create_airline('1DQ', 'Island Airlines LLC');
CALL usp_create_airline('1EQ', 'KaiserAir, Inc.');
CALL usp_create_airline('1FQ', 'Alsek Air');
CALL usp_create_airline('1HQ', 'International Jet Management GmbH');
CALL usp_create_airline('1I', 'Sky Trek International Airlines');
CALL usp_create_airline('1IQ', 'Jet link AG');
CALL usp_create_airline('1JQ', 'Exec Direct Aviation Services Limited');
CALL usp_create_airline('1LQ', 'Bertelsmann Aviation GmbH');
CALL usp_create_airline('1MQ', 'Twin Cities Air Service LLC');
CALL usp_create_airline('1NQ', 'JSC The 224th Flight Unit State Airlines');
CALL usp_create_airline('1PQ', 'Makani Kai Air Charters');
CALL usp_create_airline('1QQ', 'City Wings Inc dba Seaflight');
CALL usp_create_airline('1RQ', 'Sun Air Express LLC dba Sun Air International');
CALL usp_create_airline('1SQ', 'Star Marianas Air Inc.');
CALL usp_create_airline('1TQ', 'Rhoades Aviation dba Transair');
CALL usp_create_airline('1UQ', 'Gainjet Aviation SA');
CALL usp_create_airline('1VQ', 'Scott Air LLC dba Island Air Express');
CALL usp_create_airline('1WQ', 'Ultimate JetCharters LLC dba Ultimate Air Shuttle');
CALL usp_create_airline('1XQ', 'Dassault Falcon Service');
CALL usp_create_airline('2E', 'Smokey Bay Air Inc.');
CALL usp_create_airline('2F', 'Frontier Flying Service');
CALL usp_create_airline('2K', 'Aerolineas Galapagos S A Aerogal');
CALL usp_create_airline('2M', 'Midway Express Airlines');
CALL usp_create_airline('2O', 'Island Air Service');
CALL usp_create_airline('2R', 'Regal Air');
CALL usp_create_airline('2T', 'Canada 3000 Airlines Ltd.');
CALL usp_create_airline('2U', 'Valley Air Express Inc.');
CALL usp_create_airline('37', 'Zeal 320');
CALL usp_create_airline('3C', 'Regions Air, Inc.');
CALL usp_create_airline('3F', 'Pacific Airways, Inc.');
CALL usp_create_airline('3M', 'Silver Airways');
CALL usp_create_airline('3S', 'AeroLogic GmbH');
CALL usp_create_airline('3U', 'Sichuan Airlines Co Ltd.');
CALL usp_create_airline('4B', 'Boutique Air');
CALL usp_create_airline('4B (1)', 'Olson Air Service');
CALL usp_create_airline('4C', 'Aerovias de Intergracian Regional');
CALL usp_create_airline('4E', 'Tanana Air Service');
CALL usp_create_airline('4E (1)', 'British Airtours Limited');
CALL usp_create_airline('4H', 'Belize Trans Air');
CALL usp_create_airline('4M', 'LAN Argentina');
CALL usp_create_airline('4M (1)', 'Lan Dominica');
CALL usp_create_airline('4N', 'Air North');
CALL usp_create_airline('4O', 'ABC Aerolineas SA de CV dba Interjet');
CALL usp_create_airline('4R', 'Regent Air Corporation');
CALL usp_create_airline('4S', 'Sol Air (Aero Hunduras)');
CALL usp_create_airline('4S (1)', 'Conner Air Lines Inc.');
CALL usp_create_airline('4T', 'Belair Airlines Ltd.');
CALL usp_create_airline('4W', 'Warbelow');
CALL usp_create_airline('4Y', 'Yute Air Aka Flight Alaska');
CALL usp_create_airline('5B', 'Bellair Inc.');
CALL usp_create_airline('5C', 'C.A.L Cargo Airlines');
CALL usp_create_airline('5D', 'Aerolitoral');
CALL usp_create_airline('5F', 'Arctic Circle Air Service');
CALL usp_create_airline('5G', 'Skyservice Airlines, Inc.');
CALL usp_create_airline('5G (1)', 'Queen Air');
CALL usp_create_airline('5J', 'Private Jet Expeditions');
CALL usp_create_airline('5L', 'Aerosur');
CALL usp_create_airline('5V', 'Tatonduk Outfitters Limited d/b/a Everts Air Alaska and Everts Air Cargo');
CALL usp_create_airline('5X', 'United Parcel Service');
CALL usp_create_airline('5Y', 'Atlas Air Inc.');
CALL usp_create_airline('6A', 'Aviacsa Airlines');
CALL usp_create_airline('6B', 'TUIfly Nordic A.B.');
CALL usp_create_airline('6C', 'Cape Smythe Air Service');
CALL usp_create_airline('6F', 'Laker Airways Inc.');
CALL usp_create_airline('6H', 'Israir Airlines');
CALL usp_create_airline('6P', 'Pacific East Air Inc.');
CALL usp_create_airline('6R', 'Aerounion Aerotransporte de Carga Union SA de CV');
CALL usp_create_airline('6U', 'Air Ukraine');
CALL usp_create_airline('6Y', 'Nicaraguense De Aviacion Sa');
CALL usp_create_airline('7B', 'Krasair');
CALL usp_create_airline('7C', 'Jeju Air Co Ltd.');
CALL usp_create_airline('7F', 'First Air');
CALL usp_create_airline('7G', 'MK Airlines Ltd.');
CALL usp_create_airline('7G (1)', 'Bellair Inc. (1)');
CALL usp_create_airline('7H', 'Era Aviation');
CALL usp_create_airline('7I', 'Insel Air International B V');
CALL usp_create_airline('7M', 'Aeromonterrey S.A.');
CALL usp_create_airline('7N', 'Inland Aviation Services');
CALL usp_create_airline('7P', 'Apa International Air S.A.');
CALL usp_create_airline('7Q', 'Pan American World Airways Dominicana');
CALL usp_create_airline('7S', 'Arctic Transportation');
CALL usp_create_airline('7S (1)', 'Skystar International Inc.');
CALL usp_create_airline('7Z', 'Lb Limited');
CALL usp_create_airline('8C', 'Air Transport International');
CALL usp_create_airline('8D', 'Servant Air Inc.');
CALL usp_create_airline('8E', 'Bering Air Inc.');
CALL usp_create_airline('8F', 'Wilburs Inc.');
CALL usp_create_airline('8J', 'Jetall Airways');
CALL usp_create_airline('8L', 'Servicio Aereo Leo Lopez');
CALL usp_create_airline('8N', 'Flagship Airlines Inc.');
CALL usp_create_airline('8Q', 'Baker Aviation Inc.');
CALL usp_create_airline('8R', 'Edelweiss Air Ag');
CALL usp_create_airline('8V', 'Wright Air Service');
CALL usp_create_airline('9E', 'Endeavor Air Inc.');
CALL usp_create_airline('9J', 'Pacific Island Aviation');
CALL usp_create_airline('9K', 'Cape Air');
CALL usp_create_airline('9L', 'Colgan Air');
CALL usp_create_airline('9M', 'Central Mountain Air');
CALL usp_create_airline('9N', 'ANA & JP Express Co. Ltd.');
CALL usp_create_airline('9R', 'Flagship Express Services');
CALL usp_create_airline('9S', 'Southern Air Inc.');
CALL usp_create_airline('9T', 'TravelspanGT, Inc. S.A.');
CALL usp_create_airline('9V', 'Avior Airlines, C.A.');
CALL usp_create_airline('9W', 'Jet Airways (India) Limited');
CALL usp_create_airline('A0', 'Elysair d/b/a L''Avion');
CALL usp_create_airline('A2', 'Cielos De Peru');
CALL usp_create_airline('A4', 'Southern Wind Airlines');
CALL usp_create_airline('A7', 'Air Comet S.A.');
CALL usp_create_airline('A7 (1)', 'Air 21');
CALL usp_create_airline('AA', 'American Airlines Inc.');
CALL usp_create_airline('AAA', 'Associated Aviation Act.');
CALL usp_create_airline('AAB', 'Antilles Air Boats Inc.');
CALL usp_create_airline('AAE', 'AAA Airlines');
CALL usp_create_airline('AAI', 'Audi Air Inc.');
CALL usp_create_airline('AAL', 'Argosy Air Lines Inc.');
CALL usp_create_airline('AAP', 'Armstrong Air Service Inc.');
CALL usp_create_airline('AAQ', 'Advance Air Charters');
CALL usp_create_airline('AAR', 'Altair Airlines Inc.');
CALL usp_create_airline('AAT', 'Air Sunshine Inc.');
CALL usp_create_airline('AAV', 'Alpine Air');
CALL usp_create_airline('AAZ', 'Alaska Aeronautical Indust.');
CALL usp_create_airline('AB', 'Air Berlin PLC and CO');
CALL usp_create_airline('ABH', 'Air Bahia');
CALL usp_create_airline('ABI', 'Airbama Incorporated');
CALL usp_create_airline('ABO', 'Aeronaves Boringuena Inc.');
CALL usp_create_airline('ABX', 'ABX Air, Inc.');
CALL usp_create_airline('AC', 'Air Canada');
CALL usp_create_airline('ACA', 'Alaska Central Airways Inc.');
CALL usp_create_airline('ACD', 'Academy Airlines');
CALL usp_create_airline('ACG', 'Air Cargo Express Inc.');
CALL usp_create_airline('ACH', 'Island Airlines Hawaii Inc.');
CALL usp_create_airline('ACI', 'AAA-Action Air Carrier Inc.');
CALL usp_create_airline('ACJ', 'Atlantic Coast Jet Inc.');
CALL usp_create_airline('ACK', 'Air Central Inc.');
CALL usp_create_airline('ACL', 'Check-Air Inc.');
CALL usp_create_airline('ACN', 'Alliance Airlines');
CALL usp_create_airline('ACO', 'Air Cargo Enterprises Inc.');
CALL usp_create_airline('ACP', 'Air Chaparral Inc.');
CALL usp_create_airline('ACQ', 'Aeronautica De Cancun');
CALL usp_create_airline('ACS', 'Alamo Commuter Airlines');
CALL usp_create_airline('ACT', 'Air Central Inc. (1)');
CALL usp_create_airline('ACW', 'Transwest Air Express');
CALL usp_create_airline('AD', 'Avia Leasing Company');
CALL usp_create_airline('ADB', 'Antonov Company');
CALL usp_create_airline('ADQ', 'Aeronaves Del Peru');
CALL usp_create_airline('ADR', 'Adirondack Airlines');
CALL usp_create_airline('ADV', 'Advantage Airlines');
CALL usp_create_airline('AE', 'Air Europe Limited');
CALL usp_create_airline('AEC', 'Astec Air East Inc.');
CALL usp_create_airline('AED', 'Air East Of Delaware Inc.');
CALL usp_create_airline('AEF', 'Aero Freight');
CALL usp_create_airline('AEO', 'Aero Coach');
CALL usp_create_airline('AEQ', 'Air Caravane Inc.');
CALL usp_create_airline('AEX', 'Air Excursions LLC (1)');
CALL usp_create_airline('AF', 'Compagnie Natl Air France');
CALL usp_create_airline('AFA', 'American Flag Airlines Inc.');
CALL usp_create_airline('AFE', 'Air Florida Express');
CALL usp_create_airline('AFG', 'American Flight Group');
CALL usp_create_airline('AFQ', 'Aero B Venezuela C.A.');
CALL usp_create_airline('AFS', 'Arcata Flying Service');
CALL usp_create_airline('AGA', 'Air Cargo America Inc.');
CALL usp_create_airline('AGQ', 'Argo S. A.');
CALL usp_create_airline('AHA', 'Air Alpha');
CALL usp_create_airline('AHC', 'Air Hawaii');
CALL usp_create_airline('AHQ', 'Air National');
CALL usp_create_airline('AI', 'National Aviation Company of India Limited d/b/a Air India');
CALL usp_create_airline('AIA', 'All Island Air');
CALL usp_create_airline('AIC', 'Air Caribbean');
CALL usp_create_airline('AIE', 'Air Express Inc.');
CALL usp_create_airline('AIG', 'Airgo Inc.');
CALL usp_create_airline('AIK', 'Air Ketchum Idaho Inc.');
CALL usp_create_airline('AIM', 'Air Mont. Inc.');
CALL usp_create_airline('AIN', 'Air Indiana');
CALL usp_create_airline('AIQ', 'Norontair');
CALL usp_create_airline('AIT', 'Airways International');
CALL usp_create_airline('AIY', 'Alliance Air');
CALL usp_create_airline('AJ', 'Air Micronesia Inc.');
CALL usp_create_airline('AJQ', 'Aerodynamics Inc.');
CALL usp_create_airline('AKQ', 'Airmark Airlines Inc.');
CALL usp_create_airline('AL', 'Skyway Airlines');
CALL usp_create_airline('ALD', 'Allied Airlines');
CALL usp_create_airline('ALE', 'Air-Lift Associates Inc.');
CALL usp_create_airline('ALI', 'Brandt Air');
CALL usp_create_airline('ALK', 'Air Link Airways');
CALL usp_create_airline('ALL', 'All Seasons Air Pacific');
CALL usp_create_airline('ALQ', 'Alberta Northern Airlines');
CALL usp_create_airline('ALS', 'Air L.A.');
CALL usp_create_airline('ALT', 'Altus Airlines');
CALL usp_create_airline('ALU', 'Aleutian Air');
CALL usp_create_airline('ALX', 'Atlanta Express');
CALL usp_create_airline('AM', 'Aeromexico');
CALL usp_create_airline('AMA', 'North American Airlines Inc.');
CALL usp_create_airline('AME', 'Americair Inc.');
CALL usp_create_airline('AMI', 'American Inter-Island Inc.');
CALL usp_create_airline('AMQ', 'Ameristar Air Cargo');
CALL usp_create_airline('AMR', 'AvAir');
CALL usp_create_airline('AMT', 'American Air Transport');
CALL usp_create_airline('ANB', 'Air Nebraska Inc.');
CALL usp_create_airline('ANC', 'Atlantic Air');
CALL usp_create_airline('AND', 'Southcentral Air Inc.');
CALL usp_create_airline('ANI', 'Dash Air Corporation');
CALL usp_create_airline('ANM', 'Airways Of New Mexico Inc.');
CALL usp_create_airline('ANO', 'Metro Air Northeast Vermont');
CALL usp_create_airline('ANT', 'Air North/Nenana');
CALL usp_create_airline('AO', 'Aviacion Y Comercio S.A.');
CALL usp_create_airline('AOI', 'Trans New York');
CALL usp_create_airline('AON', 'Action Airlines');
CALL usp_create_airline('AOQ', 'Aerovias S.A.');
CALL usp_create_airline('AOR', 'Air New Orleans');
CALL usp_create_airline('APE', 'Air Cape');
CALL usp_create_airline('APH', 'Alpha Air');
CALL usp_create_airline('API', 'Arizona Pacific Inc.');
CALL usp_create_airline('APL', 'Appalachian Flying Service');
CALL usp_create_airline('APN', 'Aspen Airways Inc.');
CALL usp_create_airline('APQ', 'Alas De Transporte International');
CALL usp_create_airline('APS', 'Air Spirit Inc.');
CALL usp_create_airline('APY', 'Air Polynesia Inc.');
CALL usp_create_airline('AQQ', 'Air Charter (Safa)');
CALL usp_create_airline('AR', 'Aerolineas Argentinas');
CALL usp_create_airline('ARA', 'Air Resorts Airlines');
CALL usp_create_airline('ARB', 'Air Caribe International');
CALL usp_create_airline('ARD', 'Airlift International');
CALL usp_create_airline('ARI', 'Arizona Aero Corp.');
CALL usp_create_airline('ARM', 'Airmarc Airlines Inc.');
CALL usp_create_airline('ARN', 'Arnold Aviation');
CALL usp_create_airline('ARO', 'Air Oregon');
CALL usp_create_airline('ARP', 'Airspur Helicopters Inc.');
CALL usp_create_airline('ARQ', 'Aerovias Colombianas Arca');
CALL usp_create_airline('ARR', 'Arrowhead Airways Inc.');
CALL usp_create_airline('ARS', 'Air Sedona');
CALL usp_create_airline('ARZ', 'Arizona Airways');
CALL usp_create_airline('AS', 'Alaska Airlines Inc.');
CALL usp_create_airline('ASC', 'Air South Inc.');
CALL usp_create_airline('ASD', 'Amistad Airlines');
CALL usp_create_airline('ASH', 'Air South');
CALL usp_create_airline('ASI', 'Alpine Air Services Inc.');
CALL usp_create_airline('ASN', 'Air Casino');
CALL usp_create_airline('ASP', 'Asap Air Inc.');
CALL usp_create_airline('ASQ', 'Aerosur (1)');
CALL usp_create_airline('ASR', 'Astor Air');
CALL usp_create_airline('AST', 'Astro Airways');
CALL usp_create_airline('ASU', 'Air South (1)');
CALL usp_create_airline('ASW', 'Sunrise Airlines Inc.');
CALL usp_create_airline('AT', 'Royal Air Maroc');
CALL usp_create_airline('ATH', 'Air Southeast');
CALL usp_create_airline('ATN', 'Air Atlantic Airlines Inc.');
CALL usp_create_airline('ATO', 'Pacific National Airways');
CALL usp_create_airline('ATQ', 'Aero Tranportes Panamenos');
CALL usp_create_airline('ATS', 'Atlantis Airlines Inc.');
CALL usp_create_airline('ATT', 'Aerotransit Inc.');
CALL usp_create_airline('ATX', 'Air Carolina');
CALL usp_create_airline('AUX', 'Austin Express Inc.');
CALL usp_create_airline('AV', 'Aerovias Nacl De Colombia');
CALL usp_create_airline('AVA', 'Air Vectors Airways');
CALL usp_create_airline('AVC', 'Av Center Inc.');
CALL usp_create_airline('AVG', 'Airvantage');
CALL usp_create_airline('AVI', 'Aero Virgin Islands Corp.');
CALL usp_create_airline('AVL', 'Aviation Sales');
CALL usp_create_airline('AVQ', 'Aero Laguna S.A. De C.V.');
CALL usp_create_airline('AVR', 'Air Vermont Inc.');
CALL usp_create_airline('AVS', 'Aviation Services');
CALL usp_create_airline('AVZ', 'Southern Jersey Airways');
CALL usp_create_airline('AWA', 'Air West Airlines');
CALL usp_create_airline('AWQ', 'Aermediterranea S.P.A.');
CALL usp_create_airline('AX', 'Trans States Airlines');
CALL usp_create_airline('AXQ', 'Aeron International Airlines Inc.');
CALL usp_create_airline('AY', 'Finnair Oy');
CALL usp_create_airline('AYQ', 'Aerodan S.A. De C.V.');
CALL usp_create_airline('AZ', 'Compagnia Aerea Italiana');
CALL usp_create_airline('AZP', 'Arizona Pacific Airways');
CALL usp_create_airline('AZQ', 'Anglo Airlines Ltd.');
CALL usp_create_airline('B6', 'JetBlue Airways');
CALL usp_create_airline('BA', 'British Airways Plc');
CALL usp_create_airline('BAA', 'Aero International Airlines');
CALL usp_create_airline('BAC', 'Business Aircraft Corp.');
CALL usp_create_airline('BAH', 'Brennan & Hargreaves Inc.');
CALL usp_create_airline('BAK', 'Bankair Inc.');
CALL usp_create_airline('BAN', 'Bangor International Air');
CALL usp_create_airline('BAQ', 'Aero Rentas De Coahuila S.A. De C.V.');
CALL usp_create_airline('BAR', 'Bard-Air Corp.');
CALL usp_create_airline('BAT', 'West Penn Commuter');
CALL usp_create_airline('BAY', 'Burlington Aeroplane Co.');
CALL usp_create_airline('BBQ', 'Balair Ag');
CALL usp_create_airline('BC', 'Skymark Airlines Inc.');
CALL usp_create_airline('BCA', 'Baja Cortez Airlines');
CALL usp_create_airline('BCQ', 'Bradley Air Services Ltd.');
CALL usp_create_airline('BD', 'British Midland Airways Ltd.');
CALL usp_create_airline('BDE', 'Jet Express');
CALL usp_create_airline('BDQ', 'Aerotaxis De Aguascalientes S.A. De C.V.');
CALL usp_create_airline('BE', 'Braniff International Airlines Inc.');
CALL usp_create_airline('BEA', 'Business Express Airlines');
CALL usp_create_airline('BEN', 'Bennington Aviation Inc.');
CALL usp_create_airline('BEQ', 'Air Belgium');
CALL usp_create_airline('BES', 'Aeroservices Executive');
CALL usp_create_airline('BEY', 'Beyer Aviation');
CALL usp_create_airline('BF', 'Markair Inc.');
CALL usp_create_airline('BFG', 'Million Air');
CALL usp_create_airline('BFQ', 'Buffalo Airways Inc.');
CALL usp_create_airline('BG', 'Biman Bangladesh Airlines');
CALL usp_create_airline('BGQ', 'Airbus Transport Internat''l');
CALL usp_create_airline('BHK', 'Blackhawk Airways Inc.');
CALL usp_create_airline('BHO', 'Bighorn Airways Inc.');
CALL usp_create_airline('BHQ', 'Turks Air Ltd. (1)');
CALL usp_create_airline('BIA', 'Big Island Air');
CALL usp_create_airline('BIQ', 'Servicios Aeronauticos Z S.A. De C.V.');
CALL usp_create_airline('BIR', 'Birchwood Air Service');
CALL usp_create_airline('BJQ', 'Taxirey S.A. De C.V.');
CALL usp_create_airline('BLQ', 'Air Bvi Limited');
CALL usp_create_airline('BM', 'Belize Air International Ltd.');
CALL usp_create_airline('BMT', 'Bremerton Aviation Inc.');
CALL usp_create_airline('BN', 'Britannia Airways GmbH');
CALL usp_create_airline('BN (1)', 'Braniff Inc.');
CALL usp_create_airline('BNQ', 'NetJets Large Aircraft Company L.L.C.');
CALL usp_create_airline('BOA', 'Boise Air Service');
CALL usp_create_airline('BOI', 'Bo-S-Aire Airlines Inc.');
CALL usp_create_airline('BOQ', 'Transp. Aereos Bolivianos');
CALL usp_create_airline('BQ', 'Aeromar C. Por A.');
CALL usp_create_airline('BR', 'Eva Airways Corporation');
CALL usp_create_airline('BR (1)', 'Cal Air International Ltd.');
CALL usp_create_airline('BRK', 'Barken International');
CALL usp_create_airline('BRO', 'Brower Airways Inc.');
CALL usp_create_airline('BRW', 'Barrow Air');
CALL usp_create_airline('BTQ', 'Brasair Transportes Aereos');
CALL usp_create_airline('BUH', 'Business Helicopters');
CALL usp_create_airline('BUQ', 'Wrangler Aviation Inc.');
CALL usp_create_airline('BUQ (1)', 'Blue Bell Inc.');
CALL usp_create_airline('BUR', 'Burlington Airways Inc.');
CALL usp_create_airline('BW', 'Caribbean Airlines Limited');
CALL usp_create_airline('BXQ', 'Spantax S. A.');
CALL usp_create_airline('BY', 'Britannia Airways Ltd.');
CALL usp_create_airline('BYA', 'Bay Air');
CALL usp_create_airline('BZQ', 'Abaco Air, Ltd.');
CALL usp_create_airline('C5', 'Commutair Aka Champlain Enterprises, Inc.');
CALL usp_create_airline('C6', 'Canjet Airlines');
CALL usp_create_airline('C8', 'Cargolux Italia SpA');
CALL usp_create_airline('C8 (1)', 'Chicago Express Airlines');
CALL usp_create_airline('CA', 'Air China');
CALL usp_create_airline('CAC', 'Coleman Air Transport');
CALL usp_create_airline('CAF', 'California Seaboard');
CALL usp_create_airline('CAI', 'Crawford Aviation Inc.');
CALL usp_create_airline('CAM', 'C & M Airlines');
CALL usp_create_airline('CAP', 'Metro Air Northeast N Y');
CALL usp_create_airline('CAQ', 'Challenge Air Luftverkehrs GmbH');
CALL usp_create_airline('CAT', 'Catalina Airlines Inc.');
CALL usp_create_airline('CAV', 'Air Virginia');
CALL usp_create_airline('CAZ', 'CAT Aviation');
CALL usp_create_airline('CB', 'Air One Inc.');
CALL usp_create_airline('CBA', 'Carriba Air Inc.');
CALL usp_create_airline('CC', 'Air Atlanta Icelandic');
CALL usp_create_airline('CC (1)', 'Air Atlanta Inc.');
CALL usp_create_airline('CCA', 'Cityhop');
CALL usp_create_airline('CCO', 'Chester County Aviation');
CALL usp_create_airline('CDQ', 'Kitty Hawk International');
CALL usp_create_airline('CEN', 'Cen-Tex Airlines Inc.');
CALL usp_create_airline('CEQ', 'All Canada Express');
CALL usp_create_airline('CET', 'Century Airlines (Cal)');
CALL usp_create_airline('CF', 'Compan. De Aviacion Faucett');
CALL usp_create_airline('CGA', 'Chicago Airlines');
CALL usp_create_airline('CGL', 'Viking International Airlines Inc.');
CALL usp_create_airline('CGO', 'Chicago Air Taxi');
CALL usp_create_airline('CH', 'Bemidji Airlines');
CALL usp_create_airline('CHD', 'Chandler Flyer');
CALL usp_create_airline('CHE', 'Charter Airlines');
CALL usp_create_airline('CHF', 'Hammonds Commuter Air Serv.');
CALL usp_create_airline('CHI', 'Chitina Air Service');
CALL usp_create_airline('CHL', 'Channel Flying Inc.');
CALL usp_create_airline('CHO', 'Choi Aviation Inc.');
CALL usp_create_airline('CHS', 'Christman Air System');
CALL usp_create_airline('CHT', 'Charter One');
CALL usp_create_airline('CI', 'China Airlines Ltd.');
CALL usp_create_airline('CIQ', 'A/S Conair');
CALL usp_create_airline('CIS', 'Cal Sierra Airlines');
CALL usp_create_airline('CJ', 'Colgan Airways Inc.');
CALL usp_create_airline('CK', 'China Cargo Airline');
CALL usp_create_airline('CKI', 'Inlet Airlines');
CALL usp_create_airline('CL', 'Capitol International Inc.');
CALL usp_create_airline('CLB', 'Columbia Pacific Airlines');
CALL usp_create_airline('CLD', 'Hawaii Pacific Helicopters');
CALL usp_create_airline('CLF', 'California Air Shuttle');
CALL usp_create_airline('CLQ', 'Aero Transcolombiana');
CALL usp_create_airline('CM', 'Compania Panamena (Copa)');
CALL usp_create_airline('CMB', 'Combs Airways Inc.');
CALL usp_create_airline('CMD', 'Command Airways Inc.');
CALL usp_create_airline('CMQ', 'Servicio De Carga Aerea Sa');
CALL usp_create_airline('CMR', 'Commuter Airlines (Ca)');
CALL usp_create_airline('CNN', 'Centennial Airlines');
CALL usp_create_airline('CO', 'Continental Air Lines Inc.');
CALL usp_create_airline('COB', 'Cotton Belt Aviation Inc.');
CALL usp_create_airline('COC', 'Cochise Airlines Inc.');
CALL usp_create_airline('COK', 'Coker Aviation Inc.');
CALL usp_create_airline('COL', 'Presidential Express');
CALL usp_create_airline('COM', 'Commutair');
CALL usp_create_airline('COR', 'Coral Air Inc.');
CALL usp_create_airline('COS', 'Cosmopolitan Comm. Airline');
CALL usp_create_airline('COT', 'Southeastern Commuter');
CALL usp_create_airline('COU', 'Courtesy Air Service Inc.');
CALL usp_create_airline('CP', 'Compass Airlines');
CALL usp_create_airline('CP (1)', 'Canadian Airlines International Ltd.');
CALL usp_create_airline('CPA', 'Capitol Air Lines');
CALL usp_create_airline('CPC', 'Coastal Plains Commuter Inc.');
CALL usp_create_airline('CPQ', 'Capitol Air Express Inc.');
CALL usp_create_airline('CPT', 'Capitol Air');
CALL usp_create_airline('CQI', 'Conquest Airline Corp.');
CALL usp_create_airline('CRA', 'Commuter Airlines');
CALL usp_create_airline('CRB', 'Caribair');
CALL usp_create_airline('CRE', 'Caribbean Express Inc.');
CALL usp_create_airline('CRH', 'Cresent Medivac');
CALL usp_create_airline('CRN', 'Crown Aviaiton Inc.');
CALL usp_create_airline('CRO', 'Crown Airways Inc.');
CALL usp_create_airline('CRP', 'Corporate Air');
CALL usp_create_airline('CRT', 'Crested Butte Air Service');
CALL usp_create_airline('CRV', 'Acropolis Aviation Ltd.');
CALL usp_create_airline('CS', 'Continental Micronesia');
CALL usp_create_airline('CSA', 'Casino Airlines');
CALL usp_create_airline('CSK', 'Catskill Airways Inc.');
CALL usp_create_airline('CSL', 'Central States Air Lines');
CALL usp_create_airline('CSM', 'Chisum Flying Service');
CALL usp_create_airline('CSN', 'Casino Airlines (1)');
CALL usp_create_airline('CSQ', 'Celtic Tech Jet Ltd.');
CALL usp_create_airline('CTA', 'Century Airlines');
CALL usp_create_airline('CTH', 'Cothron Aviation');
CALL usp_create_airline('CTL', 'Coastal Air Transport');
CALL usp_create_airline('CTQ', 'Custom Air Transport');
CALL usp_create_airline('CTR', 'Chartair');
CALL usp_create_airline('CUQ', 'Caicos Caribbean Airways');
CALL usp_create_airline('CUS', 'Custom Air Service');
CALL usp_create_airline('CV', 'Cargolux Airlines International S.A');
CALL usp_create_airline('CVA', 'Catalina-Vegas Airlines');
CALL usp_create_airline('CVQ', 'Caraven S.A.');
CALL usp_create_airline('CW', 'Air Marshall Islands Inc.');
CALL usp_create_airline('CWQ', 'Canadian Aviation Express');
CALL usp_create_airline('CX', 'Cathay Pacific Airways Ltd.');
CALL usp_create_airline('CYQ', 'Corse Air International');
CALL usp_create_airline('CZ', 'China Southern Airlines');
CALL usp_create_airline('CZ (1)', 'Cascade Airways Inc.');
CALL usp_create_airline('CZQ', 'Aviation Concepts');
CALL usp_create_airline('DA', 'Dan Air Services');
CALL usp_create_airline('DAN', 'Danbury Airlines');
CALL usp_create_airline('DAU', 'Dauphin Island Airways');
CALL usp_create_airline('DC', 'Caribbean Air Cargo Co Ltd.');
CALL usp_create_airline('DE', 'Condor Flugdienst');
CALL usp_create_airline('DEA', 'Downeast Airlines Inc.');
CALL usp_create_airline('DEC', 'Decatur Aviation');
CALL usp_create_airline('DFS', 'Downeast Flying Service');
CALL usp_create_airline('DH', 'Independence Air');
CALL usp_create_airline('DH (1)', 'Discovery Airways Inc.');
CALL usp_create_airline('DHL', 'DHL Airlines Inc.');
CALL usp_create_airline('DHQ', 'DHL Aero Expresso');
CALL usp_create_airline('DIA', 'Drummond Island Air');
CALL usp_create_airline('DIC', 'Dickman Aviation Services');
CALL usp_create_airline('DIR', 'Northern Star');
CALL usp_create_airline('DL', 'Delta Air Lines Inc.');
CALL usp_create_airline('DM', 'Maersk Air I/S');
CALL usp_create_airline('DO', 'Compania Dominicana De Avia');
CALL usp_create_airline('DOL', 'Dolphin Airways Inc.');
CALL usp_create_airline('DOQ', 'Aerolineas Dominicanas S A');
CALL usp_create_airline('DPA', 'Desert Pacific Airways');
CALL usp_create_airline('DPI', 'Desert Pacific Airlines Inc.');
CALL usp_create_airline('DQQ', 'Caribwest Airways Ltd.');
CALL usp_create_airline('DSA', 'Desert Sun Airlines');
CALL usp_create_airline('DST', 'Desert Airlines');
CALL usp_create_airline('DUL', 'Dulles Express');
CALL usp_create_airline('DUZ', 'Summit Airlines Inc.');
CALL usp_create_airline('DVO', 'Devoe Airlines');
CALL usp_create_airline('DWN', 'Dawn Air');
CALL usp_create_airline('DXA', 'Dolphin Express');
CALL usp_create_airline('DY', 'Norwegian Air Shuttle ASA');
CALL usp_create_airline('E0', 'EOS Airlines, Inc.');
CALL usp_create_airline('E7', 'Estafeta Carga Aereas');
CALL usp_create_airline('E72', 'European Aviation Air Charter');
CALL usp_create_airline('E8', 'USAfrica Airways Inc.');
CALL usp_create_airline('E9', 'Boston-Maine Airways');
CALL usp_create_airline('EA', 'Eastern Air Lines Inc.');
CALL usp_create_airline('EAI', 'Executive Aviation Inc.');
CALL usp_create_airline('EAQ', 'Executive Airlines, SL');
CALL usp_create_airline('EAS', 'Eastern Caribbean Airways');
CALL usp_create_airline('EAT', 'Eastman Airways Inc.');
CALL usp_create_airline('EBQ', 'Execaire Aviation Ltd.');
CALL usp_create_airline('ECA', 'Eagle Airlines (1)');
CALL usp_create_airline('ECI', 'Eastern Carolina Aviation');
CALL usp_create_airline('ECL', 'Eclipse Airlines');
CALL usp_create_airline('ECQ', 'Trans American Charter');
CALL usp_create_airline('ECR', 'East Coast Airways');
CALL usp_create_airline('ED', 'Andes');
CALL usp_create_airline('EDE', 'Ede Aire');
CALL usp_create_airline('EET', 'Exec Express II');
CALL usp_create_airline('EEX', 'Exec Express');
CALL usp_create_airline('EEZ', 'Eagle Aviation Inc.');
CALL usp_create_airline('EFA', 'Executive Four Winds');
CALL usp_create_airline('EFQ', 'Trans Europ. Airways France');
CALL usp_create_airline('EGA', 'Eagle Airline');
CALL usp_create_airline('EGJ', 'Eagle Jet Charter');
CALL usp_create_airline('EGL', 'Eagle Commuter Airlines Inc.');
CALL usp_create_airline('EH', 'Saeta Airlines');
CALL usp_create_airline('EHA', 'East Hampton Aire Inc.');
CALL usp_create_airline('EI', 'Aer Lingus Plc');
CALL usp_create_airline('EIA', 'East. Indiana Aviation Sale');
CALL usp_create_airline('EJQ', 'Aeroejecutivos C.A.');
CALL usp_create_airline('EK', 'Emirates');
CALL usp_create_airline('EKA', 'Air Pacific Inc.');
CALL usp_create_airline('ELL', 'Ellis Air Taxi Inc.');
CALL usp_create_airline('EM', 'Empire Airlines Inc.');
CALL usp_create_airline('EMA', 'Emerald Airlines');
CALL usp_create_airline('EME', 'Metro Express');
CALL usp_create_airline('EMP', 'Empire Airlines Inc. (2)');
CALL usp_create_airline('ENT', 'Enterprise Airlines Inc.');
CALL usp_create_airline('EOQ', 'Aeroservicios Ecuatorianos');
CALL usp_create_airline('EP', 'All Star Airlines Inc.');
CALL usp_create_airline('EQ', 'Tame Linea Aerea del Ecuador Tme EP');
CALL usp_create_airline('ER', 'Astar USA, LLC');
CALL usp_create_airline('ERI', 'Erie Airways Inc.');
CALL usp_create_airline('ERO', 'Empire Aero Service');
CALL usp_create_airline('ERQ', 'Aero Trades (Western) Ltd.');
CALL usp_create_airline('ESQ', 'Seagreen Air Transport');
CALL usp_create_airline('ET', 'Ethiopian Airlines');
CALL usp_create_airline('EU', 'Ecuatoriana De Aviacion');
CALL usp_create_airline('EUQ', 'Air Atlanta Europe');
CALL usp_create_airline('EV', 'ExpressJet Airlines Inc.');
CALL usp_create_airline('EVA', 'Evanston Aviation');
CALL usp_create_airline('EWA', 'Rio Grande Air');
CALL usp_create_airline('EXA', 'Columbia Pacific Airlines (1)');
CALL usp_create_airline('EXC', 'Hapag-Lloyd Executive GmbH');
CALL usp_create_airline('EXC (1)', 'Executive Charter');
CALL usp_create_airline('EXP', 'Express Airlines II');
CALL usp_create_airline('EXQ', 'Export Air Del Peru S.A.');
CALL usp_create_airline('EXR', 'Executive Transport');
CALL usp_create_airline('EY', 'Etihad Airways');
CALL usp_create_airline('EZ', 'Evergreen International Inc.');
CALL usp_create_airline('F2', 'Omega Air Holdings d/b/a Focus Air');
CALL usp_create_airline('F8', 'Freedom Airlines d/b/a HP Expr');
CALL usp_create_airline('F9', 'Frontier Airlines Inc.');
CALL usp_create_airline('FAA', 'Falwell Aviation Inc.');
CALL usp_create_airline('FAC', 'Falcon Airways Inc.');
CALL usp_create_airline('FAQ', 'Fast Air Carrier Ltd. (1)');
CALL usp_create_airline('FAR', 'Federal Armored Service Inc.');
CALL usp_create_airline('FB', 'Translift Airways Limited');
CALL usp_create_airline('FBI', 'Young Flying Service');
CALL usp_create_airline('FCA', 'Southern Airlines Inc.');
CALL usp_create_airline('FCQ', 'Falcon Air Express');
CALL usp_create_airline('FD', 'Air Puerto Rico Airlines');
CALL usp_create_airline('FDA', 'Florida Airlines Inc.');
CALL usp_create_airline('FDM', 'Freedom Airlines Inc.');
CALL usp_create_airline('FDQ', 'Great American Airways');
CALL usp_create_airline('FE', 'Primaris Airlines Inc.');
CALL usp_create_airline('FF', 'Tower Air Inc.');
CALL usp_create_airline('FFQ', 'Five Star Airlines');
CALL usp_create_airline('FH', 'Frontier Horizon Inc.');
CALL usp_create_airline('FI', 'Icelandair');
CALL usp_create_airline('FJ', 'Air Pacific Ltd.');
CALL usp_create_airline('FJ (1)', 'Air Pacific Ltd. (1)');
CALL usp_create_airline('FL', 'AirTran Airways Corporation');
CALL usp_create_airline('FL (1)', 'Frontier Airlines Inc. (1)');
CALL usp_create_airline('FLA', 'Florida Air');
CALL usp_create_airline('FLM', 'Flamenco Airways Inc.');
CALL usp_create_airline('FLR', 'Flirite Inc.');
CALL usp_create_airline('FNQ', 'Fine Airlines Inc.');
CALL usp_create_airline('FOR', 'Ford-Aire Inc.');
CALL usp_create_airline('FOS', 'Foster Aviation');
CALL usp_create_airline('FP', 'TAG Aviation S.A.');
CALL usp_create_airline('FQ', 'Air Aruba');
CALL usp_create_airline('FRA', 'Freedom Air');
CALL usp_create_airline('FRS', 'Four Star Aviation');
CALL usp_create_airline('FRT', 'Frontier Commuter');
CALL usp_create_airline('FRW', 'Farwest Airlines');
CALL usp_create_airline('FS', 'Serv De Trans Aereos Fuegui');
CALL usp_create_airline('FSA', 'F.S. Air Service');
CALL usp_create_airline('FT', 'Flying Tiger Line Inc.');
CALL usp_create_airline('FTI', 'Southern Airways');
CALL usp_create_airline('FVA', 'Skycraft Inc.');
CALL usp_create_airline('FW', 'Skybus Inc.');
CALL usp_create_airline('FWA', 'Far West Airlines');
CALL usp_create_airline('FX', 'Federal Express Corporation');
CALL usp_create_airline('FYB', 'Flying Boat');
CALL usp_create_airline('G3', 'VRG Linhas Aereas S A');
CALL usp_create_airline('G3 (1)', 'Aerochago S.A.');
CALL usp_create_airline('G4', 'Allegiant Air');
CALL usp_create_airline('G7', 'GoJet Airlines, LLC d/b/a United Express');
CALL usp_create_airline('GA', 'P.T. Garuda Indonesian Arwy');
CALL usp_create_airline('GAL', 'Galena Air Service');
CALL usp_create_airline('GAQ', 'Galaxy Airlines Inc.');
CALL usp_create_airline('GAS', 'General Aviation Inc.');
CALL usp_create_airline('GAT', 'Gulf Air Taxi');
CALL usp_create_airline('GAV', 'Gromer Aviation Inc.');
CALL usp_create_airline('GBA', 'Central States Airline');
CALL usp_create_airline('GBQ', 'G5 Executive Ag');
CALL usp_create_airline('GCA', 'Golden Carriage Aire');
CALL usp_create_airline('GCH', 'Grand Canyon Helicopters');
CALL usp_create_airline('GCQ', 'General Air Cargo');
CALL usp_create_airline('GCS', 'Midway Commuter');
CALL usp_create_airline('GD', 'Transp. Aereos Ejecutivos');
CALL usp_create_airline('GDW', 'Golden West Airlines Inc.');
CALL usp_create_airline('GE', 'Lufthansa Cargo Airlines');
CALL usp_create_airline('GF', 'Gulf Air Company');
CALL usp_create_airline('GF (1)', 'Gulf Air Transport Inc.');
CALL usp_create_airline('GFC', 'Gulf Flite Center');
CALL usp_create_airline('GFQ', 'Gulf And Caribbean Cargo');
CALL usp_create_airline('GG', 'Cargo 360, Inc.');
CALL usp_create_airline('GG (1)', 'Tropical Airways Inc.');
CALL usp_create_airline('GG (2)', 'Grenada Airways Ltd.');
CALL usp_create_airline('GH', 'Ghana Airways Corporation');
CALL usp_create_airline('GHA', 'Green Hills Aviation Ltd.');
CALL usp_create_airline('GIQ', 'Global International Airways Corp.');
CALL usp_create_airline('GJ', 'Eurofly S.p.A');
CALL usp_create_airline('GJ (1)', 'Mexicargo');
CALL usp_create_airline('GKQ', 'Laker Airways');
CALL usp_create_airline('GL', 'Miami Air International');
CALL usp_create_airline('GLW', 'Golden West Airlines Co.');
CALL usp_create_airline('GM', 'Air America');
CALL usp_create_airline('GMA', 'Green Mountain Airlines Ltd.');
CALL usp_create_airline('GOF', 'Copper State Airlines');
CALL usp_create_airline('GPA', 'GP Express Airlines');
CALL usp_create_airline('GQ', 'Big Sky Airlines Inc.');
CALL usp_create_airline('GR', 'Gemini Air Cargo Airways');
CALL usp_create_airline('GRA', 'Gorda Aero Service');
CALL usp_create_airline('GRD', 'Grand Canyon Airlines');
CALL usp_create_airline('GRO', 'Isle Royale Seaplane Serv.');
CALL usp_create_airline('GS', 'Air Foyle Limited');
CALL usp_create_airline('GSA', 'Golden Gate Airlines Inc.');
CALL usp_create_airline('GSC', 'GCS Air Service');
CALL usp_create_airline('GSL', 'Golden South Airlines Inc.');
CALL usp_create_airline('GSQ', 'Global Supply System');
CALL usp_create_airline('GST', 'Golden State Airlines');
CALL usp_create_airline('GU', 'Aviateca');
CALL usp_create_airline('GUL', 'Gull Air Inc.');
CALL usp_create_airline('GUN', 'Gunnel Aviation Inc.');
CALL usp_create_airline('GV', 'Grant Aviation');
CALL usp_create_airline('GW', 'Central American Airlines');
CALL usp_create_airline('GWA', 'Great Western Aviation');
CALL usp_create_airline('GWE', 'Ross Aviation Inc.');
CALL usp_create_airline('GX', 'Air Ontario Limited');
CALL usp_create_airline('GY', 'Guyana Airways Corporation');
CALL usp_create_airline('H2', 'City Bird');
CALL usp_create_airline('H5', 'Magadan Airlines');
CALL usp_create_airline('H6', 'Hageland Aviation Service');
CALL usp_create_airline('HA', 'Hawaiian Airlines Inc.');
CALL usp_create_airline('HAQ', 'Hapag Lloyd Flug.');
CALL usp_create_airline('HAR', 'Friendship Air Alaska');
CALL usp_create_airline('HB', 'Homer Air');
CALL usp_create_airline('HB (1)', 'Air Club International');
CALL usp_create_airline('HBQ', 'Harris Air Services');
CALL usp_create_airline('HCQ', 'Av Atlantic');
CALL usp_create_airline('HEL', 'Helitrans');
CALL usp_create_airline('HEP', 'Hub Express');
CALL usp_create_airline('HER', 'Markair Express');
CALL usp_create_airline('HET', 'Helitac Aviation');
CALL usp_create_airline('HEU', 'Heussler Air Service Corp');
CALL usp_create_airline('HFQ', 'Haiti Air Freight Intl');
CALL usp_create_airline('HFS', 'Hensley Flying Service Inc.');
CALL usp_create_airline('HIQ', 'Business Flights Ltd.');
CALL usp_create_airline('HJ', 'Air Haiti S. A.');
CALL usp_create_airline('HK', 'Time Air Sweden Ab');
CALL usp_create_airline('HLQ', 'Heavylift Cargo Airlines Lt');
CALL usp_create_airline('HMZ', 'Long Island Airlines');
CALL usp_create_airline('HNS', 'Haines Airways');
CALL usp_create_airline('HOL', 'Holiday Airlines Inc.');
CALL usp_create_airline('HOQ', 'Holidair Airways');
CALL usp_create_airline('HOR', 'Iowa Airlines');
CALL usp_create_airline('HP', 'America West Airlines Inc. (Merged with US Airways 9/05. Stopped reporting 10/07.)');
CALL usp_create_airline('HPZ', 'Pacific Coast Airlines');
CALL usp_create_airline('HQ', 'Harmony Airways');
CALL usp_create_airline('HQ (1)', 'Business Express');
CALL usp_create_airline('HQQ', 'Harlequin Air Corporation');
CALL usp_create_airline('HRA', 'Trans-National Airlines Haw');
CALL usp_create_airline('HRG', 'Heritage Airlines');
CALL usp_create_airline('HRQ', 'Tar Airlines');
CALL usp_create_airline('HRZ', 'Allegheny Airlines');
CALL usp_create_airline('HSV', 'Harbor Air Service');
CALL usp_create_airline('HSZ', 'Scenic Airlines Inc.');
CALL usp_create_airline('HU', 'Hainan Airlines Company Limited');
CALL usp_create_airline('HUB', 'Skystream Airlines');
CALL usp_create_airline('HVQ', 'Transavia Holland B. V.');
CALL usp_create_airline('HWK', 'Hawking Corporation');
CALL usp_create_airline('HX', 'Guy-America Airways Inc.');
CALL usp_create_airline('HY', 'Uzbekistan Airways');
CALL usp_create_airline('HYA', 'Hyannis Aviation');
CALL usp_create_airline('IA', 'Iraqi Airways');
CALL usp_create_airline('IB', 'Iberia Air Lines Of Spain');
CALL usp_create_airline('ICF', 'Iowa City Flying Service');
CALL usp_create_airline('ICH', 'Island Air Charters');
CALL usp_create_airline('ICQ', 'Iscargo Hf');
CALL usp_create_airline('IDQ', 'Intl Air Service Co. Ltd.');
CALL usp_create_airline('IEX', 'Island Air Express');
CALL usp_create_airline('IG', 'Meridiana S.p.A');
CALL usp_create_airline('IGA', 'Global Jet Austria, GmbH');
CALL usp_create_airline('III', 'Idee Industries Inc.');
CALL usp_create_airline('IJ', 'Great Wall Airlines Company Limited');
CALL usp_create_airline('IKQ', 'Tradewinds Airways Ltd.');
CALL usp_create_airline('IMP', 'Imperial Airlines Inc.');
CALL usp_create_airline('IN', 'Aerlinte Eireann Teoranta');
CALL usp_create_airline('INA', 'Inland Empire Airlines Inc.');
CALL usp_create_airline('IND', 'Indiana Airways Inc. (Pa)');
CALL usp_create_airline('INQ', 'Independent Air Inc.');
CALL usp_create_airline('IOW', 'Iowa Airways');
CALL usp_create_airline('IPI', 'Indo-Pacific International');
CALL usp_create_airline('IPQ', 'Aruba Cargo');
CALL usp_create_airline('IPS', 'Island Express');
CALL usp_create_airline('IR', 'Iran National Airlines Corp');
CALL usp_create_airline('IRQ', 'Interstate Airlines Inc.');
CALL usp_create_airline('ISL', 'Island Airlines');
CALL usp_create_airline('ITQ', 'Interamericana De Aviacion');
CALL usp_create_airline('IW', 'Air Liberte Aka Aom Minerve');
CALL usp_create_airline('IW (1)', 'Best Airlines Inc.');
CALL usp_create_airline('IXQ', 'Inair');
CALL usp_create_airline('J5', 'Alaska Seaplane Service');
CALL usp_create_airline('J6', 'Larrys Flying Service');
CALL usp_create_airline('J7', 'Valujet Airlines Inc.');
CALL usp_create_airline('JAG', 'JetAlliance Flugbetriebs d/b/a JAF Airservice');
CALL usp_create_airline('JAM', 'Sunbelt Airlines Inc.');
CALL usp_create_airline('JAQ', 'Jamaica Air Freighters');
CALL usp_create_airline('JB', 'Helijet International Inc.');
CALL usp_create_airline('JCM', 'Air Chico');
CALL usp_create_airline('JCQ', 'Jet Connection Businessflight Ag');
CALL usp_create_airline('JCZ', 'Rocky Mountain Airways Inc.');
CALL usp_create_airline('JD', 'Japan Air System Co. Ltd.');
CALL usp_create_airline('JER', 'Jer-Don Air');
CALL usp_create_airline('JF', 'L.A.B. Flying Service Inc.');
CALL usp_create_airline('JI', 'Jade Cargo International');
CALL usp_create_airline('JI (1)', 'Midway Airlines Inc.');
CALL usp_create_airline('JIQ', 'Jet Fleet Intl. Airlines');
CALL usp_create_airline('JJ', 'Transportes Aeros Meridiona');
CALL usp_create_airline('JK', 'Spanair S.A.');
CALL usp_create_airline('JK (1)', 'Sunworld International Airways Inc.');
CALL usp_create_airline('JKQ', 'Express One International Inc.');
CALL usp_create_airline('JL', 'Japan Air Lines Co. Ltd.');
CALL usp_create_airline('JM', 'Air Jamaica Limited');
CALL usp_create_airline('JMA', 'Jim Air Inc.');
CALL usp_create_airline('JN', 'Excel Airways');
CALL usp_create_airline('JO', 'Jalways Co. Ltd.');
CALL usp_create_airline('JQ', 'Jetstar Airways Pty Limited');
CALL usp_create_airline('JR', 'Aero California');
CALL usp_create_airline('JTA', 'Jetaire Airlines Inc.');
CALL usp_create_airline('JU', 'Yugoslav Airlines');
CALL usp_create_airline('JW', 'Arrow Air Inc.');
CALL usp_create_airline('JX', 'Southeast Airlines');
CALL usp_create_airline('JX (1)', 'Jes Air Ltd.');
CALL usp_create_airline('JXQ', 'Allarco Developments Ltd.');
CALL usp_create_airline('JZ', 'Japan Air Charter Co. Ltd.');
CALL usp_create_airline('K3', 'Venture Travel LLC d/b/a Taquan Air Service');
CALL usp_create_airline('K5', 'SeaPort Airlines, Inc. d/b/a Wings of Alaska');
CALL usp_create_airline('K7', 'Arizona Express');
CALL usp_create_airline('K8', 'Caribbean Sun Airlines, Inc. d/b/a World Atlantic Airlines');
CALL usp_create_airline('K8 (1)', 'Dutch Caribbean Airlines');
CALL usp_create_airline('KA', 'Hong Kong Dragonair');
CALL usp_create_airline('KAH', 'Kenmore Air Harbor');
CALL usp_create_airline('KAI', 'Knight Airlines Inc.');
CALL usp_create_airline('KAQ', 'Kalitta Air LLC');
CALL usp_create_airline('KAT', 'Katmai Air');
CALL usp_create_airline('KB', 'Haiti Air');
CALL usp_create_airline('KE', 'Korean Air Lines Co. Ltd.');
CALL usp_create_airline('KEA', 'Keene Airways');
CALL usp_create_airline('KEE', 'Key Airlines');
CALL usp_create_airline('KET', 'Ketchikan Air Service');
CALL usp_create_airline('KFS', 'King Flying Service');
CALL usp_create_airline('KH', 'Aloha Air Cargo');
CALL usp_create_airline('KI', 'Time Air Ltd.');
CALL usp_create_airline('KIN', 'Golden Pacific Airlines');
CALL usp_create_airline('KKQ', 'Transmeridian Air Cargo Ltd.');
CALL usp_create_airline('KL', 'Klm Royal Dutch Airlines');
CALL usp_create_airline('KLQ', 'Kalitta Charters II');
CALL usp_create_airline('KM', 'Air Malta');
CALL usp_create_airline('KN', 'Morris Air Corporation');
CALL usp_create_airline('KO', 'Alaska Central Express');
CALL usp_create_airline('KOD', 'Kodiak Airways Inc.');
CALL usp_create_airline('KP', 'Kiwi International');
CALL usp_create_airline('KR', 'Kitty Hawk Aircargo');
CALL usp_create_airline('KR (1)', 'Kar-Air Oy');
CALL usp_create_airline('KS', 'Peninsula Airways Inc.');
CALL usp_create_airline('KTQ', 'Turks Air Ltd.');
CALL usp_create_airline('KU', 'Kuwait Airways Corp.');
CALL usp_create_airline('KW', 'Carnival Air Lines Inc.');
CALL usp_create_airline('KWQ', 'Kelowna Flightcraft Air Cha');
CALL usp_create_airline('KWZ', 'Crown Air');
CALL usp_create_airline('KX', 'Cayman Airways Limited');
CALL usp_create_airline('KXZ', 'Chaparral Airlines Inc.');
CALL usp_create_airline('KZ', 'Nippon Cargo Airlines');
CALL usp_create_airline('L2', 'Lynden Air Cargo Airlines');
CALL usp_create_airline('L3', 'Lynx Aviation d/b/a Frontier Airlines');
CALL usp_create_airline('L7', 'Lan Colombia');
CALL usp_create_airline('LA', 'Lan-Chile Airlines');
CALL usp_create_airline('LAA', 'La Skycab Airline');
CALL usp_create_airline('LAH', 'La Helicopter');
CALL usp_create_airline('LAN', 'Lancer Aviation Inc.');
CALL usp_create_airline('LAP', 'Lapsa');
CALL usp_create_airline('LAR', 'Laredo Air');
CALL usp_create_airline('LAS', 'Lake Union Air Service');
CALL usp_create_airline('LAW', 'Lawrence Aviation');
CALL usp_create_airline('LB', 'Lloyd Aereo Boliviano S. A.');
CALL usp_create_airline('LBQ', 'Millon Air Inc.');
CALL usp_create_airline('LC', 'Varig Logistica S/A');
CALL usp_create_airline('LC (1)', 'Lineas Aereas Del Caribe');
CALL usp_create_airline('LC (2)', 'Legend Airlines');
CALL usp_create_airline('LCQ', 'Latcr');
CALL usp_create_airline('LCT', 'Lake Coastal');
CALL usp_create_airline('LEQ', 'Le Point Air');
CALL usp_create_airline('LEX', 'L''Express');
CALL usp_create_airline('LF', 'Jettrain Airlines');
CALL usp_create_airline('LG', 'Luxair');
CALL usp_create_airline('LGQ', 'Lineas Aereas Allegro');
CALL usp_create_airline('LH', 'Lufthansa German Airlines');
CALL usp_create_airline('LHA', 'Havasu Airlines');
CALL usp_create_airline('LIQ', 'Liat (1974) Limited');
CALL usp_create_airline('LJ', 'Jin Air Co Ltd.');
CALL usp_create_airline('LKN', 'Loken Aviation');
CALL usp_create_airline('LLA', 'Lakeland Aviation');
CALL usp_create_airline('LNQ', 'Aerolineas Latinas');
CALL usp_create_airline('LO', 'Polskie Linie Lotnicze');
CALL usp_create_airline('LOQ', 'Lorair Ltd.');
CALL usp_create_airline('LOS', 'Aero Commuter');
CALL usp_create_airline('LP', 'Lan Peru Airlines');
CALL usp_create_airline('LP (1)', 'The Hawaii Express Inc.');
CALL usp_create_airline('LR', 'Lacsa');
CALL usp_create_airline('LRQ', 'Air Liberte');
CALL usp_create_airline('LSQ', 'Lineas Aereas Suramerican');
CALL usp_create_airline('LSZ', 'Alaska Island Air Inc.');
CALL usp_create_airline('LT', 'Luftransport-Unternehmen');
CALL usp_create_airline('LU', 'Air Atlantic Dominicana');
CALL usp_create_airline('LUQ', 'Lineas Aereas La-Tur Sa');
CALL usp_create_airline('LVA', 'Las Vegas Airlines');
CALL usp_create_airline('LW', 'Pacific Wings Airlines');
CALL usp_create_airline('LX', 'Swiss International Airlines');
CALL usp_create_airline('LXQ', 'Translux Intl Airlines');
CALL usp_create_airline('LY', 'El Al Israel Airlines Ltd.');
CALL usp_create_airline('LZ', 'Balkan Bulgarian Airlines');
CALL usp_create_airline('LZQ', 'Leisure International Airways Ltd.');
CALL usp_create_airline('M3', 'ABSA-Aerolinhas Brasileiras');
CALL usp_create_airline('M6', 'Amerijet International');
CALL usp_create_airline('M7', 'Aerotransportes Mas De Crga');
CALL usp_create_airline('MA', 'Malev Hungarian Airlines');
CALL usp_create_airline('MAA', 'Maui Airlines');
CALL usp_create_airline('MAC', 'Mackey International Inc.');
CALL usp_create_airline('MAE', 'Mid-Atlantic Exp. Airlines');
CALL usp_create_airline('MAG', 'Magum Airlines');
CALL usp_create_airline('MAI', 'The Maui Commuter');
CALL usp_create_airline('MAQ', 'Millardair Limited');
CALL usp_create_airline('MAR', 'Marshall''s Air Inc.');
CALL usp_create_airline('MAV', 'Maverick Airways');
CALL usp_create_airline('MAX', 'Maxair Inc.');
CALL usp_create_airline('MB', 'Samoa Airlines Inc.');
CALL usp_create_airline('MC', 'Transtar Airlines Corp.');
CALL usp_create_airline('MCO', 'Mid Continental Airlines In');
CALL usp_create_airline('MDC', 'Midcontinent Airlines');
CALL usp_create_airline('MDU', 'Metro Airlines');
CALL usp_create_airline('ME', 'Middle East Airlines S.A.L.');
CALL usp_create_airline('MEA', 'Manhattan Express');
CALL usp_create_airline('MET', 'Metroplex Airlines');
CALL usp_create_airline('MEX', 'Metro Express 11');
CALL usp_create_airline('MG', 'Champion Air');
CALL usp_create_airline('MGQ', 'Montana Austria Flugetrieb');
CALL usp_create_airline('MH', 'Malaysian Airline System');
CALL usp_create_airline('MHK', 'Mohawk Airlines');
CALL usp_create_airline('MHO', 'Mahalo Air');
CALL usp_create_airline('MIN', 'Minuteman Aviation Inc.');
CALL usp_create_airline('MIS', 'Midstate Airlines Inc.');
CALL usp_create_airline('MIY', 'Midway Aviation Inc.');
CALL usp_create_airline('MJ', 'Lapa-Lineas Aereas Privadas');
CALL usp_create_airline('MKQ', 'Airmark Corporation');
CALL usp_create_airline('ML', 'Aero Costa Rica');
CALL usp_create_airline('ML (1)', 'Midway Airlines Inc. (1)');
CALL usp_create_airline('MLL', 'Miller Air Transportersinc');
CALL usp_create_airline('MLX', 'Merlin Express');
CALL usp_create_airline('MM', 'Euro Atlantic Airways');
CALL usp_create_airline('MM (1)', 'Sociedad Aeronautica De Med');
CALL usp_create_airline('MMH', 'Ocean Airways Inc.');
CALL usp_create_airline('MNA', 'M & N Aviation');
CALL usp_create_airline('MNZ', 'Cumberland Airlines');
CALL usp_create_airline('MOQ', 'Morningstar Air Express');
CALL usp_create_airline('MP', 'Martinair Holland N.V.');
CALL usp_create_airline('MPA', 'Mid Pacific Airlines Inc.');
CALL usp_create_airline('MPC', 'Mid Pacific Air Corp.');
CALL usp_create_airline('MQ', 'Envoy Air');
CALL usp_create_airline('MRC', 'Marco Island Airways Inc.');
CALL usp_create_airline('MRQ', 'National Air Cargo Group, Inc. d/b/a Murray Air');
CALL usp_create_airline('MRR', 'Merrimack Aviation Inc.');
CALL usp_create_airline('MS', 'Egyptair');
CALL usp_create_airline('MST', 'Midwest Aviation');
CALL usp_create_airline('MT', 'Thomas Cook Airlines Uk Ltd.');
CALL usp_create_airline('MT (1)', 'Flying Colours Airlines Ltd.');
CALL usp_create_airline('MTA', 'Arkansas Traveler Airline');
CALL usp_create_airline('MTR', 'Metroflight Airlines');
CALL usp_create_airline('MTV', 'Mst Aviation');
CALL usp_create_airline('MTX', 'Mountain Air Express');
CALL usp_create_airline('MU', 'China Eastern Airlines');
CALL usp_create_airline('MU (1)', 'Mcclain Airlines Inc.');
CALL usp_create_airline('MUA', 'Manu''a Air Transport');
CALL usp_create_airline('MUQ', 'Aerolineas Mundo');
CALL usp_create_airline('MVA', 'Mississippi Valley Airlines');
CALL usp_create_airline('MW', 'Mokulele Flight Services, Inc.');
CALL usp_create_airline('MWA', 'Mountain West Airlines');
CALL usp_create_airline('MX', 'Compania Mexicana De Aviaci');
CALL usp_create_airline('MY', 'MAXjet');
CALL usp_create_airline('MYQ', 'Lineas Aereas Mayas (Lamsa)');
CALL usp_create_airline('MZ', 'P.N. Merpati Nusantara Air.');
CALL usp_create_airline('N5', 'Skagway Air Service');
CALL usp_create_airline('N5 (1)', 'Nations Air Express Inc.');
CALL usp_create_airline('N6', 'Aero Continente');
CALL usp_create_airline('N7', 'National Airlines');
CALL usp_create_airline('NA', 'North American Airlines');
CALL usp_create_airline('NAC', 'National Air Commuter Inc.');
CALL usp_create_airline('NAP', 'Npa Inc.');
CALL usp_create_airline('NAQ', 'Nationair');
CALL usp_create_airline('NAS', 'Nasville Eagle');
CALL usp_create_airline('NAT', 'National Air');
CALL usp_create_airline('NB', 'Sterling Cargo');
CALL usp_create_airline('NBQ', 'Sterling Airways A/S');
CALL usp_create_airline('NC', 'Northern Air Cargo Inc.');
CALL usp_create_airline('NCA', 'National Commuter Airlines');
CALL usp_create_airline('NCE', 'Northcoast Executive');
CALL usp_create_airline('ND', 'Intair');
CALL usp_create_airline('NEB', 'New Born Wings Inc.');
CALL usp_create_airline('NEC', 'Nor East Commuter Airlines');
CALL usp_create_airline('NEQ', 'North East Cargo Airlines');
CALL usp_create_airline('NER', 'Northeast Express Regional (1)');
CALL usp_create_airline('NET', 'Nacnet');
CALL usp_create_airline('NEV', 'Nevada Airlines');
CALL usp_create_airline('NEW', 'New England Airlines Inc.');
CALL usp_create_airline('NEX', 'Northeast Express Regional');
CALL usp_create_airline('NFA', 'National Florida Airlines');
CALL usp_create_airline('NFQ', 'North Cariboo Flying Serv.');
CALL usp_create_airline('NG', 'Lauda Air Luftfahrt Ag');
CALL usp_create_airline('NGL', 'Northern Eagle Airways Inc.');
CALL usp_create_airline('NH', 'All Nippon Airways Co.');
CALL usp_create_airline('NHA', 'Newair Flight Inc.');
CALL usp_create_airline('NI', 'Lanica');
CALL usp_create_airline('NI (1)', 'American International Airways Inc.');
CALL usp_create_airline('NJ', 'Vanguard Airlines Inc.');
CALL usp_create_airline('NJA', 'N. J. Merrimack Airlines');
CALL usp_create_airline('NJE', 'NetJets Transportes Aereos, S.A.');
CALL usp_create_airline('NK', 'Spirit Air Lines');
CALL usp_create_airline('NKQ', 'Norcanair');
CALL usp_create_airline('NLQ', 'Nolinor Aviation');
CALL usp_create_airline('NN', 'Northward Airlines Ltd.');
CALL usp_create_airline('NOQ', 'Novair Airlines Ab');
CALL usp_create_airline('NPA', 'North Pacific Airlines Inc.');
CALL usp_create_airline('NPT', 'E. J. A. Newport Inc.');
CALL usp_create_airline('NQ', 'Air Japan Co');
CALL usp_create_airline('NRN', 'Northern Airlines Inc.');
CALL usp_create_airline('NSQ', 'North Coast Air Services');
CALL usp_create_airline('NTH', 'Northaire');
CALL usp_create_airline('NTQ', 'National Aviation Consult.');
CALL usp_create_airline('NUM', 'Lake State Airways');
CALL usp_create_airline('NUQ', 'Air Niugini');
CALL usp_create_airline('NVQ', 'Novair International Airways Ltd.');
CALL usp_create_airline('NVX', 'Nevis Express');
CALL usp_create_airline('NW', 'Northwest Airlines Inc.');
CALL usp_create_airline('NWQ', 'N. W. Territorial Airways');
CALL usp_create_airline('NWS', 'Northwest Seaplanes');
CALL usp_create_airline('NXQ', 'North Vancouver Air');
CALL usp_create_airline('NY', 'New York Air Inc.');
CALL usp_create_airline('NYH', 'New York Helicopter Corp.');
CALL usp_create_airline('NZ', 'Air New Zealand');
CALL usp_create_airline('OA', 'Olympic Airways');
CALL usp_create_airline('OAK', 'Harbor Airlines Inc.');
CALL usp_create_airline('OB', 'Oasis International Airlines S.A.');
CALL usp_create_airline('OC', 'Air California Inc.');
CALL usp_create_airline('OCR', 'Ocean Reef Airways Inc.');
CALL usp_create_airline('OD', 'Emerald Airlines Inc.');
CALL usp_create_airline('OD (1)', 'Aerocondor');
CALL usp_create_airline('OE', 'Westair Airlines Inc.');
CALL usp_create_airline('OF', 'Air Finland Ltd.');
CALL usp_create_airline('OFF', 'Offshore Logistics');
CALL usp_create_airline('OH', 'Comair Inc.');
CALL usp_create_airline('OHA', 'Omaha Aviation');
CALL usp_create_airline('OHZ', 'Caribbean Air Services Inc.');
CALL usp_create_airline('OI', 'Prestige Airways');
CALL usp_create_airline('OIZ', 'Corporate Air Inc.');
CALL usp_create_airline('OJ', 'Fly Jamaica Airways Limited');
CALL usp_create_airline('OK', 'Czech Airlines');
CALL usp_create_airline('OMH', 'Omniflight Helicopters');
CALL usp_create_airline('OMI', 'Omniflight Airways');
CALL usp_create_airline('OMK', 'Omak Aviation Airlines');
CALL usp_create_airline('OMN', 'Omni Pacific Airline');
CALL usp_create_airline('OMQ', 'Quassar De Mexico');
CALL usp_create_airline('ON', 'Air Nauru');
CALL usp_create_airline('ONQ', 'Nunasi-Central Airlines Ltd.');
CALL usp_create_airline('OO', 'SkyWest Airlines Inc.');
CALL usp_create_airline('OOZ', 'Sun Aire Lines');
CALL usp_create_airline('OP', 'Flying Boat Inc.');
CALL usp_create_airline('OP (1)', 'Air Panama Internacional');
CALL usp_create_airline('OPQ', 'Orion Air');
CALL usp_create_airline('OR', 'TUI Airlines Nederland B.V.');
CALL usp_create_airline('ORI', 'Orion Air Inc.');
CALL usp_create_airline('OS', 'Austrian Airlines');
CALL usp_create_airline('OTT', 'Otter Air');
CALL usp_create_airline('OV', 'Aeromaritime');
CALL usp_create_airline('OW', 'Executive Airlines');
CALL usp_create_airline('OWQ', 'Ontario Worldair Limited');
CALL usp_create_airline('OWS', 'Air Kentucky Air Lines');
CALL usp_create_airline('OZ', 'Asiana Airlines Inc.');
CALL usp_create_airline('OZ (1)', 'Ozark Air Lines Inc. (1)');
CALL usp_create_airline('OZA', 'Ozark Air Lines Inc.');
CALL usp_create_airline('P9', 'Pro Air Inc.');
CALL usp_create_airline('PA', 'Florida Coastal Airlines');
CALL usp_create_airline('PA (1)', 'Pan American World Airways (1)');
CALL usp_create_airline('PA (2)', 'Pan American World Airways');
CALL usp_create_airline('PAI', 'Permian Airways Inc.');
CALL usp_create_airline('PAQ', 'Patriot Airlines Inc.');
CALL usp_create_airline('PAT', 'Panorama Air Tours');
CALL usp_create_airline('PBA', 'Provincetown Boston');
CALL usp_create_airline('PBQ', 'Privatair');
CALL usp_create_airline('PCA', 'Piasa Commuter Airlines');
CALL usp_create_airline('PCL', 'Pacific Cal Air');
CALL usp_create_airline('PCQ', 'Pace Airlines');
CALL usp_create_airline('PCR', 'Pacair');
CALL usp_create_airline('PD', 'Porter Airlines, Inc.');
CALL usp_create_airline('PD (1)', 'Pem-Air Limited');
CALL usp_create_airline('PDA', 'Trans Southern Airways');
CALL usp_create_airline('PDQ', 'Antigua Paradise Airways');
CALL usp_create_airline('PE', 'Air Europe S.P.A.');
CALL usp_create_airline('PE (1)', 'People Express Airlines Inc.');
CALL usp_create_airline('PEA', 'Pearson Aircraft');
CALL usp_create_airline('PEQ', 'SkyLink Express Inc.');
CALL usp_create_airline('PER', 'Air Pennsylvania');
CALL usp_create_airline('PET', 'Petro Aviation Corp.');
CALL usp_create_airline('PFA', 'Pacificair');
CALL usp_create_airline('PFQ', 'Asia Pacific');
CALL usp_create_airline('PH', 'Polynesian Airlines Ltd.');
CALL usp_create_airline('PHL', 'Phillips Airlines');
CALL usp_create_airline('PHR', 'Pinehurst Airlines Inc.');
CALL usp_create_airline('PHX', 'Phoenix Airlines');
CALL usp_create_airline('PI', 'Piedmont Aviation Inc.');
CALL usp_create_airline('PIA', 'Pacific Island Airways');
CALL usp_create_airline('PIQ', 'Pacific International Airlines');
CALL usp_create_airline('PK', 'Pakistan International Airlines');
CALL usp_create_airline('PKQ', 'Skyworld Airlines Inc.');
CALL usp_create_airline('PL', 'Aero Peru');
CALL usp_create_airline('PLA', 'Planes Inc.');
CALL usp_create_airline('PLQ', 'Planet Airways');
CALL usp_create_airline('PLZ', 'Polar Airways Inc.');
CALL usp_create_airline('PM', 'Prescott Support Company, Inc.');
CALL usp_create_airline('PMA', 'Pacific Missionary Aviation');
CALL usp_create_airline('PMT', 'Pilgrim Aviation & Airlines');
CALL usp_create_airline('PN', 'Pan American Airways Corp.');
CALL usp_create_airline('PNM', 'Panama Aviation');
CALL usp_create_airline('PNQ', 'Panagra Airways');
CALL usp_create_airline('PNR', 'Pioneer Airways');
CALL usp_create_airline('PNS', 'Pine State Airlines');
CALL usp_create_airline('PO', 'Polar Air Cargo Airways');
CALL usp_create_airline('POA', 'Potomac Air');
CALL usp_create_airline('POC', 'Pocono Airlines Inc.');
CALL usp_create_airline('POL', 'Polar International');
CALL usp_create_airline('POM', 'Pompano Airways');
CALL usp_create_airline('PON', 'Ponderosa Aviation Inc.');
CALL usp_create_airline('POQ', 'Polyot Airlines');
CALL usp_create_airline('PP', 'Jet Aviation Business Jets AG');
CALL usp_create_airline('PPQ', 'Propair');
CALL usp_create_airline('PR', 'Philippine Airlines Inc.');
CALL usp_create_airline('PRA', 'Princeton Aviation Corp');
CALL usp_create_airline('PRD', 'Paradise Island Airlines');
CALL usp_create_airline('PRM', 'Prime Air Inc.');
CALL usp_create_airline('PRN', 'Puerto Rico Intl Airlines');
CALL usp_create_airline('PRO', 'Sundance Airlines');
CALL usp_create_airline('PRP', 'Propheter Aviation');
CALL usp_create_airline('PRQ', 'Florida West Airlines Inc.');
CALL usp_create_airline('PRR', 'Pro Air Services');
CALL usp_create_airline('PS', 'Ukraine International Airlines');
CALL usp_create_airline('PS (1)', 'Pacific Southwest Airlines');
CALL usp_create_airline('PSA', 'P.S. Air Freight Inc.');
CALL usp_create_airline('PT', 'Capital Cargo International');
CALL usp_create_airline('PTQ', 'Flight International');
CALL usp_create_airline('PU', 'Primeras Lineas Uruguays For International');
CALL usp_create_airline('PUQ', 'Aeropuma');
CALL usp_create_airline('PV', 'Eastern Provincial Airways');
CALL usp_create_airline('PVA', 'Precision Valley Aviation');
CALL usp_create_airline('PW', 'Pacific Western Airlines');
CALL usp_create_airline('PY', 'Surinam Airways Limited');
CALL usp_create_airline('PZ', 'Lineas Aereas Paraguayas');
CALL usp_create_airline('Q2', 'Zambia Airways Corp.');
CALL usp_create_airline('Q4', 'Master Top Linhas Aereas, Ltda.');
CALL usp_create_airline('Q5', '40-Mile Air');
CALL usp_create_airline('Q7', 'Sobelair');
CALL usp_create_airline('QB', 'Inter-Quebec (Intair)');
CALL usp_create_airline('QD', 'Grand Airways Inc.');
CALL usp_create_airline('QF', 'Qantas Airways Ltd.');
CALL usp_create_airline('QG', 'Sky West Aviation Inc.');
CALL usp_create_airline('QH', 'Air Florida Inc.');
CALL usp_create_airline('QK', 'Jazz Aviation LP');
CALL usp_create_airline('QN', 'Royal Air');
CALL usp_create_airline('QO', 'Aeromexpress');
CALL usp_create_airline('QOZ', 'Bar Harbor Airways');
CALL usp_create_airline('QQ', 'Reno Air Inc.');
CALL usp_create_airline('QR', 'Qatar Airways (Q.C.S.C)');
CALL usp_create_airline('QS', 'Travel Service, a.s.');
CALL usp_create_airline('QS (1)', 'Northeastern International Airways');
CALL usp_create_airline('QT', 'Transportes Aereos Mercantiles Panamericanos S.A');
CALL usp_create_airline('QTQ', 'Aer Turas Teoranta');
CALL usp_create_airline('QWE', 'Qwest Commuter');
CALL usp_create_airline('QX', 'Horizon Air');
CALL usp_create_airline('R3', 'Air Company Yakutia');
CALL usp_create_airline('RAL', 'Royal-Air Ltd.');
CALL usp_create_airline('RAN', 'Pan Am Express');
CALL usp_create_airline('RAQ', 'Arista International Airlines Inc.');
CALL usp_create_airline('RAY', 'Royale Airlines Inc.');
CALL usp_create_airline('RB', 'Syrian Arab Airlines');
CALL usp_create_airline('RC', 'Republic Airlines Inc.');
CALL usp_create_airline('RCA', 'Mid-South Aviation Inc. (1)');
CALL usp_create_airline('RD', 'Ryan International Airlines');
CALL usp_create_airline('RD (1)', 'Airlift International Inc.');
CALL usp_create_airline('RDR', 'Rader Aviation');
CALL usp_create_airline('RDW', 'Redwing Airways');
CALL usp_create_airline('REA', 'Realwest Airlines');
CALL usp_create_airline('RED', 'Aerosun International Airlines Inc.');
CALL usp_create_airline('REQ', 'Renown Aviation');
CALL usp_create_airline('RES', 'Resort Airlines Inc.');
CALL usp_create_airline('RG', 'Varig S. A.');
CALL usp_create_airline('RGQ', 'Regency Air');
CALL usp_create_airline('RHA', 'Royal Hawaiian Airways Inc.');
CALL usp_create_airline('RIA', 'Trump Air');
CALL usp_create_airline('RIC', 'Richardson Aviation');
CALL usp_create_airline('RID', 'Indiana Airways Inc. (Reid');
CALL usp_create_airline('RIO', 'Rio Airways Inc.');
CALL usp_create_airline('RIQ', 'Rich International Airways');
CALL usp_create_airline('RIV', 'Riverside Air Service');
CALL usp_create_airline('RJ', 'Alia-(The) Royal Jordanian');
CALL usp_create_airline('RJS', 'Michigan Airways Inc.');
CALL usp_create_airline('RK', 'Air Afrique');
CALL usp_create_airline('RL', 'UltrAir');
CALL usp_create_airline('RL (1)', 'Aerolineas Nicaraguenses');
CALL usp_create_airline('RLQ', 'Reliant Airlines');
CALL usp_create_airline('RMH', 'Rocky Mountain Helicopters');
CALL usp_create_airline('RMV', 'Ram Aviation');
CALL usp_create_airline('RNQ', 'Mytravel Airways');
CALL usp_create_airline('RO', 'Tarom Romanian Air Transpor');
CALL usp_create_airline('ROA', 'Royal West Airways Inc.');
CALL usp_create_airline('ROE', 'Roederer Aviation Inc.');
CALL usp_create_airline('ROQ', 'Aero Uruguay (1)');
CALL usp_create_airline('ROS', 'Great Western Airlines Inc.');
CALL usp_create_airline('ROY', 'Royal American Airways Inc.');
CALL usp_create_airline('RP', 'Chautauqua Airlines Inc.');
CALL usp_create_airline('RRT', 'Air Freight Express');
CALL usp_create_airline('RS', 'Sky Regional Airlines Inc.');
CALL usp_create_airline('RSC', 'Resort Commuter');
CALL usp_create_airline('RSQ', 'Aerotransportes Entre Rios');
CALL usp_create_airline('RSV', 'Air-Serve');
CALL usp_create_airline('RTQ', 'Aerotour Dominicano Cxa');
CALL usp_create_airline('RU', 'AirBridgeCargo Airlines Limited');
CALL usp_create_airline('RV', 'Air Canada rouge LP');
CALL usp_create_airline('RV (1)', 'Reeve Aleutian Airways Inc.');
CALL usp_create_airline('RVA', 'Reeves Air');
CALL usp_create_airline('RVQ', 'Reeve Air Alaska, LLC');
CALL usp_create_airline('RWG', 'Air Rovers Inc.');
CALL usp_create_airline('RY', 'Redcoat Air Cargo Limited');
CALL usp_create_airline('RZZ', 'Aeromech Inc.');
CALL usp_create_airline('S3', 'Santa Barbara Airlines, C.A');
CALL usp_create_airline('S4', 'Sata Internacional');
CALL usp_create_airline('S5', 'Shuttle America Corp.');
CALL usp_create_airline('S6', 'Star Air A/S');
CALL usp_create_airline('S6 (1)', 'Mountain Bird/Salmon Air');
CALL usp_create_airline('SA', 'South African Airways');
CALL usp_create_airline('SAC', 'Sundorph Aeronautical Corp.');
CALL usp_create_airline('SAH', 'Sea Air Shuttle');
CALL usp_create_airline('SAI', 'Seair Alaska Airlines Inc.');
CALL usp_create_airline('SAJ', 'Sajen Air Inc.');
CALL usp_create_airline('SAL', 'Sallee''s Aviation');
CALL usp_create_airline('SAM', 'Samoan Airlines Inc.');
CALL usp_create_airline('SAQ', 'Southern Air Transport Inc.');
CALL usp_create_airline('SAS', 'Air Cortez International');
CALL usp_create_airline('SAX', 'Air Americana');
CALL usp_create_airline('SBA', 'Saber Aviation Inc.');
CALL usp_create_airline('SBN', 'Suburban Airlines');
CALL usp_create_airline('SBQ', 'Skyjet S.A.');
CALL usp_create_airline('SCN', 'Scott Aviation');
CALL usp_create_airline('SCO', 'Seaco Airlines Inc.');
CALL usp_create_airline('SCT', 'Skyline Airlines');
CALL usp_create_airline('SCY', 'South Coast Airways');
CALL usp_create_airline('SDQ', 'St. Lucia Airways Limited');
CALL usp_create_airline('SE', 'XL Airways France');
CALL usp_create_airline('SE (1)', 'Das Air Cargo');
CALL usp_create_airline('SEB', 'Seaborne Aviation');
CALL usp_create_airline('SEG', 'Seagull Air Service');
CALL usp_create_airline('SEM', 'Semo Aviation Inc.');
CALL usp_create_airline('SEP', 'Southern Express Airways');
CALL usp_create_airline('SEQ', 'Sky Service F.B.O.');
CALL usp_create_airline('SER', 'Service Aviation Inc.');
CALL usp_create_airline('SFI', 'Stahmannfarms Inc.');
CALL usp_create_airline('SFO', 'Sfo Helicopter Airlines Inc.');
CALL usp_create_airline('SFQ', 'Pacific International Airlines Inc.');
CALL usp_create_airline('SFQ (1)', 'Southern Frontier Air Trans');
CALL usp_create_airline('SFS', 'Sierra Flite Service Inc.');
CALL usp_create_airline('SG', 'Jetsgo');
CALL usp_create_airline('SH', 'Servicio Aereo De Honduras');
CALL usp_create_airline('SHS', 'Shasta Air Inc.');
CALL usp_create_airline('SHV', 'Shavano Air Inc.');
CALL usp_create_airline('SI', 'Sierra Pacific Airlines');
CALL usp_create_airline('SI (1)', 'Jet America Airlines Inc.');
CALL usp_create_airline('SIA', 'Silver State Airlines');
CALL usp_create_airline('SIQ', 'Premiair');
CALL usp_create_airline('SIQ (1)', 'Scanair');
CALL usp_create_airline('SJA', 'San Juan Airlines Inc.');
CALL usp_create_airline('SJQ', 'Skycharter (Malton) Ltd.');
CALL usp_create_airline('SK', 'Scandinavian Airlines Sys.');
CALL usp_create_airline('SKI', 'Sunbird Inc.');
CALL usp_create_airline('SKJ', 'Sky-Jet');
CALL usp_create_airline('SKL', 'Bas Airlines');
CALL usp_create_airline('SKM', 'Scheduled Skyways');
CALL usp_create_airline('SKS', 'Silver Kris Services Ltd.');
CALL usp_create_airline('SKT', 'Skytrain');
CALL usp_create_airline('SLO', 'Slocum Air Inc.');
CALL usp_create_airline('SLQ', 'Sky King Inc.');
CALL usp_create_airline('SLR', 'Salair');
CALL usp_create_airline('SLZ', 'Southeast Airlines Inc.');
CALL usp_create_airline('SM', 'Sunworld International Airlines');
CALL usp_create_airline('SMC', 'Stopher Mechanical Inc.');
CALL usp_create_airline('SMO', 'Samoa Aviation Inc.');
CALL usp_create_airline('SMQ', 'Serv. Aerolineas Mexicanas');
CALL usp_create_airline('SN', 'Brussels Airlines N.V.');
CALL usp_create_airline('SN (1)', 'Sabena Belgian World Air.');
CALL usp_create_airline('SNA', 'Aviation Associates');
CALL usp_create_airline('SNB', 'Ccair');
CALL usp_create_airline('SNC', 'Gelco Courier Services Inc.');
CALL usp_create_airline('SNE', 'Shawnee Airlines');
CALL usp_create_airline('SNK', 'Spernak Airways Inc.');
CALL usp_create_airline('SNV', 'Sierra Nevada Airways');
CALL usp_create_airline('SO', 'Swiss World Airways');
CALL usp_create_airline('SOA', 'Mall Airways Inc.');
CALL usp_create_airline('SOE', 'Sky One Express');
CALL usp_create_airline('SOL', 'Soonair Lines Inc.');
CALL usp_create_airline('SOP', 'South Pacific Island Airway');
CALL usp_create_airline('SPF', 'Springfield Air Service');
CALL usp_create_airline('SPG', 'Springdale Air');
CALL usp_create_airline('SPH', 'Spirit Helicopter');
CALL usp_create_airline('SPQ', 'Sun Pacific International');
CALL usp_create_airline('SPR', 'Sportsman Flying Service');
CALL usp_create_airline('SQ', 'Singapore Airlines Ltd.');
CALL usp_create_airline('SR', 'Swissair Transport Co. Ltd.');
CALL usp_create_airline('SRA', 'Star Aviation');
CALL usp_create_airline('SRL', 'Sterling Air Service');
CALL usp_create_airline('SS', 'Corsair International');
CALL usp_create_airline('SSA', 'S. S. Airways Inc.');
CALL usp_create_airline('SSP', 'Southern Seaplane');
CALL usp_create_airline('SSQ', 'Superior Airways Limited');
CALL usp_create_airline('SSS', 'Sierra Express Inc.');
CALL usp_create_airline('SST', 'Seaplane Shuttle Transport');
CALL usp_create_airline('ST', 'Belize Airways Limited');
CALL usp_create_airline('STA', 'State Airlines Inc.');
CALL usp_create_airline('STF', 'Trans East International');
CALL usp_create_airline('STG', 'Sedalia Marshall Boonvl Stg');
CALL usp_create_airline('STQ', 'Skycraft Air Transport Inc.');
CALL usp_create_airline('STR', 'Star Aviation Corporation');
CALL usp_create_airline('STW', 'Stateswest Airlines');
CALL usp_create_airline('STZ', 'Air America Inc.');
CALL usp_create_airline('SU', 'Aeroflot Russian Airlines');
CALL usp_create_airline('SUA', 'Sunshine Airlines');
CALL usp_create_airline('SUI', 'Sun International Airways');
CALL usp_create_airline('SUT', 'Sunbelt');
CALL usp_create_airline('SUX', 'Sunair Express LLC');
CALL usp_create_airline('SV', 'Saudi Arabian Airlines Corp');
CALL usp_create_airline('SVL', 'Sun Valley Airlines');
CALL usp_create_airline('SVW', 'Global Jet Luxembourg, Sa');
CALL usp_create_airline('SWA', 'Sunwest Airlines');
CALL usp_create_airline('SWT', 'Swift Aire Lines Inc.');
CALL usp_create_airline('SX', 'Skybus Airlines, Inc.');
CALL usp_create_airline('SX (1)', 'Aeroejecutivo S.A.');
CALL usp_create_airline('SXP', 'Sierra Expressway');
CALL usp_create_airline('SY', 'Sun Country Airlines d/b/a MN Airlines');
CALL usp_create_airline('SYB', 'Skybus Express Airlines');
CALL usp_create_airline('SYM', 'Skymaster');
CALL usp_create_airline('SZQ', 'Aerolineas El Salvador S A');
CALL usp_create_airline('T3', 'Tristar Airlines Inc.');
CALL usp_create_airline('T9', 'TransMeridian Airlines');
CALL usp_create_airline('TA', 'Taca International Airlines');
CALL usp_create_airline('TAC', 'Air Colorado');
CALL usp_create_airline('TAF', 'Tri Air Freight');
CALL usp_create_airline('TAL', 'Tejas Airlines Inc.');
CALL usp_create_airline('TAQ', 'Taquan Air Service');
CALL usp_create_airline('TAS', 'Yosemite Airlines Inc.');
CALL usp_create_airline('TAT', 'Talarik Creek Air Taxi');
CALL usp_create_airline('TB', 'TUI Airlines Belgium N.V. d/b/a Jetairfly');
CALL usp_create_airline('TB (1)', 'USAir Shuttle');
CALL usp_create_airline('TBQ', 'Triair Bermuda Flt Operations');
CALL usp_create_airline('TCA', 'Trans Catalina Airlines');
CALL usp_create_airline('TCE', 'Oceanair Line');
CALL usp_create_airline('TCI', 'Trans California Airlines');
CALL usp_create_airline('TCL', 'Trans-Central Airlines Inc.');
CALL usp_create_airline('TCO', 'Trans-Colorado Airlines');
CALL usp_create_airline('TCQ', 'Express.Net Airlines');
CALL usp_create_airline('TDQ', 'Venexcargo');
CALL usp_create_airline('TDQ (1)', 'Transcarga');
CALL usp_create_airline('TEN', 'Tennessee Airways Inc.');
CALL usp_create_airline('TER', 'Terre Haute Air Commuter');
CALL usp_create_airline('TFQ', 'Trans International Airlines Inc.');
CALL usp_create_airline('TFZ', 'Tri-State Airlines Inc.');
CALL usp_create_airline('TG', 'Thai Airways International Ltd.');
CALL usp_create_airline('TGO', 'Trans Air Cargo Inc.');
CALL usp_create_airline('TGQ', 'Tranps Aereos Guatemaltecos');
CALL usp_create_airline('TH', 'Transmile Air Service');
CALL usp_create_airline('THA', 'Tropical Helicopter Airways');
CALL usp_create_airline('THO', 'Thorson Aviation');
CALL usp_create_airline('THQ', 'T-Bird Air Inc.');
CALL usp_create_airline('TIA', 'Trans Air Inc.');
CALL usp_create_airline('TIE', 'Trans International Express');
CALL usp_create_airline('TIQ', 'Tyrolean Jet Service');
CALL usp_create_airline('TIS', 'Skyfreight');
CALL usp_create_airline('TJ', 'Jet Charter Service Inc.');
CALL usp_create_airline('TK', 'Turk Hava Yollari A.O.');
CALL usp_create_airline('TKQ', 'Trans-Air-Link Corporation');
CALL usp_create_airline('TLQ', 'Trans-Mediterranean Airways');
CALL usp_create_airline('TMA', 'Trans Mo Airlines');
CALL usp_create_airline('TN', 'Air Tahiti Nui');
CALL usp_create_airline('TNQ', 'Emery Worldwide Airlines');
CALL usp_create_airline('TNS', 'Transtate Aviation');
CALL usp_create_airline('TP', 'Tap-Portuguese Airlines');
CALL usp_create_airline('TPQ', 'Aerial Transit Company');
CALL usp_create_airline('TQQ', 'Taca Peru');
CALL usp_create_airline('TR', 'Transbrasil S.A.');
CALL usp_create_airline('TRA', 'Aeromexico Travel');
CALL usp_create_airline('TRI', 'Great Plains Airlines Inc.');
CALL usp_create_airline('TRO', 'Air Molakai');
CALL usp_create_airline('TRP', 'Trans Pennsylvania Airlines');
CALL usp_create_airline('TRQ', 'Blue Scandinavia Ab');
CALL usp_create_airline('TRR', 'Territorial Airlines');
CALL usp_create_airline('TS', 'Air Transat');
CALL usp_create_airline('TSF', 'American Central Airlines');
CALL usp_create_airline('TSI', 'Trans Sierra Airlines Inc.');
CALL usp_create_airline('TSQ', 'TPI International Airways');
CALL usp_create_airline('TTM', 'The Time Machine');
CALL usp_create_airline('TUL', 'Tulsair Beechcraft Inc.');
CALL usp_create_airline('TUR', 'Turner Aire');
CALL usp_create_airline('TV', 'Haiti Trans Air');
CALL usp_create_airline('TV (1)', 'Transamerica Airlines Inc.');
CALL usp_create_airline('TVL', 'Travelair');
CALL usp_create_airline('TW', 'Trans World Airways LLC');
CALL usp_create_airline('TWA', 'Trans Western Airlines Utah');
CALL usp_create_airline('TWE', 'Trans World Express');
CALL usp_create_airline('TX', 'Soc.Nouvelle Air Guadeloupe');
CALL usp_create_airline('TX (1)', 'Transportes Aereos Nacional');
CALL usp_create_airline('TXA', 'Texas National Airlines');
CALL usp_create_airline('TXE', 'Trans Air (Hawaii)');
CALL usp_create_airline('TXQ', 'British Caribbean Airways');
CALL usp_create_airline('TXY', 'Texas Airways');
CALL usp_create_airline('TYE', 'Temsco Airlines');
CALL usp_create_airline('TZ', 'ATA Airlines d/b/a ATA');
CALL usp_create_airline('TZQ', 'First Choice Airways');
CALL usp_create_airline('U2', 'UFS Inc.');
CALL usp_create_airline('U5', 'USA 3000 Airlines');
CALL usp_create_airline('U7', 'USA Jet Airlines Inc.');
CALL usp_create_airline('UA', 'United Air Lines Inc.');
CALL usp_create_airline('UAI', 'Universal Airways Inc.');
CALL usp_create_airline('UC', 'Ladeco');
CALL usp_create_airline('UD', 'Fast Air Carrier Ltd.');
CALL usp_create_airline('UH', 'US Helicopter Corporation');
CALL usp_create_airline('UMQ', 'Air Manila Inc.');
CALL usp_create_airline('UN', 'Transaero Airlines');
CALL usp_create_airline('UNQ', 'Overseas National Airways');
CALL usp_create_airline('UP', 'Bahamasair Holding Limited');
CALL usp_create_airline('UR', 'Empire Airlines Inc. (1)');
CALL usp_create_airline('URQ', 'Aero Uruguay');
CALL usp_create_airline('US', 'US Airways Inc.');
CALL usp_create_airline('USA', 'Air U.S.');
CALL usp_create_airline('UT', 'Union De Transports Aeriens');
CALL usp_create_airline('UTQ', 'Universal Airlines Inc.');
CALL usp_create_airline('UX', 'Air Europa');
CALL usp_create_airline('UX (1)', 'Air Illinois Inc.');
CALL usp_create_airline('UYQ', 'Aerolineas Uruguayas S.A.');
CALL usp_create_airline('V4', 'Vensecar International');
CALL usp_create_airline('V5', 'J.D.Valenciana De Aviation');
CALL usp_create_airline('V8', 'Iliamna Air Taxi');
CALL usp_create_airline('V9', 'Eagle Airlines');
CALL usp_create_airline('VA', 'Virgin Blue International Airlines t/a V Australia');
CALL usp_create_airline('VA (1)', 'Venezuelan International Airways');
CALL usp_create_airline('VAG', 'Vagabond Aviation Inc.');
CALL usp_create_airline('VAQ', 'Vacationair');
CALL usp_create_airline('VAS', 'Valley Air Services');
CALL usp_create_airline('VB', 'Aeroenlaces Nacionales, S.A. de C.V. d/b/a VivaAerobus');
CALL usp_create_airline('VB (1)', 'Pacific Express');
CALL usp_create_airline('VC', 'Servicios Avensa');
CALL usp_create_airline('VCQ', 'Victory Air Transport Inc.');
CALL usp_create_airline('VE', 'Aerovias Venezolanas-Avensa');
CALL usp_create_airline('VER', 'Britt Airlines Inc.');
CALL usp_create_airline('VEZ', 'Valdez Airlines');
CALL usp_create_airline('VH', 'Aeropostal Alas De Venezuel');
CALL usp_create_airline('VI', 'Vieques Air Link Inc.');
CALL usp_create_airline('VIG', 'Viking Express');
CALL usp_create_airline('VIN', 'Vale International Airlines');
CALL usp_create_airline('VIQ', 'Volga-Dnepr Airlines');
CALL usp_create_airline('VIQ (1)', 'Viscount Air Service Inc.');
CALL usp_create_airline('VIS', 'Virgin Islands Seaplane');
CALL usp_create_airline('VJT', 'VistaJet Limited');
CALL usp_create_airline('VK', 'Air Tungaru Corporation');
CALL usp_create_airline('VL', 'Mid-South Aviation Inc.');
CALL usp_create_airline('VLA', 'Village Aviation');
CALL usp_create_airline('VLY', 'Valley Airlines');
CALL usp_create_airline('VOQ', 'Avalon Aviation Ltd.');
CALL usp_create_airline('VP', 'Viacao Aerea Sao Paulo');
CALL usp_create_airline('VQ', 'Vintage Props & Jets Inc.');
CALL usp_create_airline('VR', 'Transportes Aereos De Cabo');
CALL usp_create_airline('VS', 'Virgin Atlantic Airways');
CALL usp_create_airline('VSA', 'VistaJet Luftfahrtunternehmen GmbH');
CALL usp_create_airline('VV', 'Aerosvit Ukranian Airlines');
CALL usp_create_airline('VV (1)', 'Challenge Air Transport Inc.');
CALL usp_create_airline('VV (2)', 'Challenge Air International Inc.');
CALL usp_create_airline('VW', 'Transportes Aeromar S.A de C.V');
CALL usp_create_airline('VX', 'Virgin America');
CALL usp_create_airline('VX (1)', 'Aces Airlines');
CALL usp_create_airline('VY', 'Highland Express Airways');
CALL usp_create_airline('W3', 'Arik Air International');
CALL usp_create_airline('W4', 'Mn Aviation, Inc.');
CALL usp_create_airline('W7', 'Western Pacific Airlines');
CALL usp_create_airline('W8', 'Cargojet Airways Ltd.');
CALL usp_create_airline('W9', 'Eastwind Airlines Inc.');
CALL usp_create_airline('WA', 'Worldwide Airlines Services');
CALL usp_create_airline('WA (1)', 'Western Air Lines Inc.');
CALL usp_create_airline('WAC', 'Air East Airlines');
CALL usp_create_airline('WAI', 'Wise Airlines Inc.');
CALL usp_create_airline('WAP', 'Arrow Panama');
CALL usp_create_airline('WAQ', 'Air Charter Systems (Acs)');
CALL usp_create_airline('WAR', 'Waring Air');
CALL usp_create_airline('WAW', 'Westward Airways Inc.');
CALL usp_create_airline('WC', 'Wien Air Alaska Inc.');
CALL usp_create_airline('WCA', 'Walker''s International');
CALL usp_create_airline('WCI', 'Mountainwest Airlines');
CALL usp_create_airline('WD', 'Halisa Air');
CALL usp_create_airline('WDQ', 'Wardair Canada Inc.');
CALL usp_create_airline('WE', 'Centurion Cargo Inc.');
CALL usp_create_airline('WEB', 'Southeast Alaska Airlines');
CALL usp_create_airline('WEQ', 'Aero-Services-Corporate');
CALL usp_create_airline('WES', 'Western Star Airlines Inc.');
CALL usp_create_airline('WET', 'Western Charter Inc.');
CALL usp_create_airline('WFS', 'Wheeler Airlines');
CALL usp_create_airline('WFT', 'Westflight Aviation');
CALL usp_create_airline('WG', 'Sunwing Airlines Inc.');
CALL usp_create_airline('WGL', 'Wrangell Air Service');
CALL usp_create_airline('WGQ', 'Gateway Aviation Limited');
CALL usp_create_airline('WI', 'Tradewinds Airlines');
CALL usp_create_airline('WIA', 'Wisc Air');
CALL usp_create_airline('WIL', 'Will''s Air');
CALL usp_create_airline('WIR', 'Williams Air Inc.');
CALL usp_create_airline('WL', 'World Air Network');
CALL usp_create_airline('WLH', 'Welch Aviation');
CALL usp_create_airline('WLQ', 'Worldwide Airlines Inc.');
CALL usp_create_airline('WM', 'Windward Islands Airways');
CALL usp_create_airline('WN', 'Southwest Airlines Co.');
CALL usp_create_airline('WNG', 'Wings Airways');
CALL usp_create_airline('WNQ', 'Winair Inc.');
CALL usp_create_airline('WO', 'World Airways Inc.');
CALL usp_create_airline('WP', 'Island Air Hawaii');
CALL usp_create_airline('WRA', 'Wra Inc.');
CALL usp_create_airline('WRD', 'Ward Air');
CALL usp_create_airline('WRT', 'Wright Airlines Inc.');
CALL usp_create_airline('WS', 'Westjet');
CALL usp_create_airline('WS (1)', 'Suncoast Airlines Inc.');
CALL usp_create_airline('WSK', 'AAR Western Skyways');
CALL usp_create_airline('WST', 'West Isle Air');
CALL usp_create_airline('WSU', 'Mission Air');
CALL usp_create_airline('WT', 'Nigeria Airways Ltd.');
CALL usp_create_airline('WTA', 'Westates Airlines');
CALL usp_create_airline('WV', 'Air Greco, Inc., d/b/a Wings Air');
CALL usp_create_airline('WV (1)', 'Air South Inc. (1)');
CALL usp_create_airline('WW', 'WOW Air ehf');
CALL usp_create_airline('WWI', 'Wings West Airlines');
CALL usp_create_airline('WWQ', 'Worldways Canada Ltd.');
CALL usp_create_airline('X4', 'Air Excursions LLC');
CALL usp_create_airline('X9', 'Omni Air Express');
CALL usp_create_airline('XAA', 'Aero Union Corp');
CALL usp_create_airline('XAB', 'Air Polynesia d/b/a DHL Cargo');
CALL usp_create_airline('XAC', 'Air Express International Airlines');
CALL usp_create_airline('XAE', 'Amerford Airways Inc.');
CALL usp_create_airline('XAF', 'Astro-Wing Airlines Inc.');
CALL usp_create_airline('XAG', 'Ball Brothers Inc.');
CALL usp_create_airline('XAH', 'Hawaii Pacific Air');
CALL usp_create_airline('XAI', 'Burlington Northern Inc.');
CALL usp_create_airline('XAJ', 'Central American International');
CALL usp_create_airline('XAK', 'Century Airlines Inc.');
CALL usp_create_airline('XAM', 'Cohlmia Aviation');
CALL usp_create_airline('XAO', 'Dallas Flight Center');
CALL usp_create_airline('XAQ', 'Cam Air International Inc.');
CALL usp_create_airline('XAR', 'Jet Way Inc.');
CALL usp_create_airline('XAS', 'Klondike Air Inc.');
CALL usp_create_airline('XAT', 'Michigan Peninsula Airways');
CALL usp_create_airline('XAU', 'Flight Line Inc.');
CALL usp_create_airline('XAY', 'Pat Air');
CALL usp_create_airline('XAZ', 'Purolator Sky Courier Inc.');
CALL usp_create_airline('XBC', 'Jet East Inc.');
CALL usp_create_airline('XBF', 'WTC Airlines');
CALL usp_create_airline('XBH', 'Profit Airlines Inc.');
CALL usp_create_airline('XBI', 'CF Air Freight');
CALL usp_create_airline('XBJ', 'International Air Service');
CALL usp_create_airline('XBM', 'Phh Air Inc.');
CALL usp_create_airline('XBP', 'Circle Airfreight Corp.');
CALL usp_create_airline('XBQ', 'Aeronaves De Puerto Rico');
CALL usp_create_airline('XBR', 'Allstates Air Cargo Inc.');
CALL usp_create_airline('XBT', 'Pacific Alaska Airlines Inc.');
CALL usp_create_airline('XBV', 'Nal Inc.');
CALL usp_create_airline('XBX', 'Icb International Airlines');
CALL usp_create_airline('XBZ', 'Air Natl Aircraft Sal & Ser');
CALL usp_create_airline('XC', 'Air Caribbean (1)');
CALL usp_create_airline('XCA', 'Hawkins And Powers Aviation');
CALL usp_create_airline('XDA', 'Pacific Air Express Inc.');
CALL usp_create_airline('XDC', 'Hemisphere Air Charter');
CALL usp_create_airline('XDD', 'International Parcel Express Inc.');
CALL usp_create_airline('XDE', 'Air Train Inc.');
CALL usp_create_airline('XDF', 'Salair Inc.');
CALL usp_create_airline('XDH', 'Kitty Hawk Air Cargo');
CALL usp_create_airline('XE', 'ExpressJet Airlines Inc. (1)');
CALL usp_create_airline('XF', 'Vladivostok Air');
CALL usp_create_airline('XJ', 'Mesaba Airlines');
CALL usp_create_airline('XK', 'Aerotal');
CALL usp_create_airline('XL', 'Lan Ecuador');
CALL usp_create_airline('XP', 'Casino Express');
CALL usp_create_airline('XPA', 'Express Air d/b/a Sunrise');
CALL usp_create_airline('XPE', 'Amira Air GmbH');
CALL usp_create_airline('XPQ', 'International Cargo Xpress');
CALL usp_create_airline('XV', 'Presidential Airways Inc.');
CALL usp_create_airline('XY', 'Munz Northern Airlines Inc.');
CALL usp_create_airline('XYZ', 'Airpac Inc.');
CALL usp_create_airline('Y2', 'Globespan Airways Limited d/b/a Flyglobespan');
CALL usp_create_airline('Y4', 'Concesionaria Vuela Compania De Aviacion SA de CV (Volaris)');
CALL usp_create_airline('Y7', 'Flyjet Limited d/b/a Silverjet');
CALL usp_create_airline('Y8', 'Yangtze River Express Airlines Company');
CALL usp_create_airline('YB', 'Trans Continental Airlines');
CALL usp_create_airline('YBQ', 'Yellow Bird Air');
CALL usp_create_airline('YM', 'Royal West Airlines');
CALL usp_create_airline('YR', 'Grand Canyon Airlines, Inc. d/b/a Grand Canyon Airlines d/b/a Scenic Airlines');
CALL usp_create_airline('YV', 'Mesa Airlines Inc.');
CALL usp_create_airline('YX', 'Republic Airlines');
CALL usp_create_airline('YX (1)', 'Midwest Airline, Inc.');
CALL usp_create_airline('Z3', 'PM Air, LLC');
CALL usp_create_airline('Z3 (1)', 'Promech');
CALL usp_create_airline('ZA', 'Accessair Holdings');
CALL usp_create_airline('ZAQ', 'Zas Airline Of Egypt');
CALL usp_create_airline('ZB', 'Monarch Airlines');
CALL usp_create_airline('ZE', 'Lineas Aereas Azteca');
CALL usp_create_airline('ZFZ', 'Mcphillips Flying Service');
CALL usp_create_airline('ZIA', 'Air New Mexico');
CALL usp_create_airline('ZK', 'Great Lakes Airlines');
CALL usp_create_airline('ZKQ', 'Zantop International');
CALL usp_create_airline('ZL', 'Affretair');
CALL usp_create_airline('ZMZ', 'Winnipesaukee Aviation Inc.');
CALL usp_create_airline('ZN', 'Key Airlines Inc.');
CALL usp_create_airline('ZO', 'Florida Express Inc.');
CALL usp_create_airline('ZP', 'Air St. Thomas');
CALL usp_create_airline('ZS', 'Hispaniola Airways');
CALL usp_create_airline('ZUQ', 'Zuliana De Aviacion');
CALL usp_create_airline('ZV', 'Air Midwest Inc.');
CALL usp_create_airline('ZW', 'Air Wisconsin Airlines Corp');
CALL usp_create_airline('ZX', 'Air Georgian');
CALL usp_create_airline('ZX (1)', 'Airbc Ltd.');
CALL usp_create_airline('ZY', 'Atlantic Gulf Airlines');
CALL usp_create_airline('ZYZ', 'Skyway Aviation Inc.');
